### ISSUE TITLE
Cannot create account during checkout: Uncaught ArgumentCountError: Too few arguments to function wp_mail()

### ISSUE THREAD

**Issue by martincpt** [woothemes/woocommerce#31319]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When I try to create an account during the checkout, the procedure ends up in an email hook argument error.

```
2021-11-28 13:10:33.324993 [STDERR] PHP Warning:  Only arrays and Traversables can be unpacked in /www/mysite.eu/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php on line 655
2021-11-28 13:10:33.327590 [STDERR] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function wp_mail(), 0 passed in /www/mysite.eu/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php on line 655 and at least 3 expected in /www/mysite.eu/wp-includes/pluggable.php:182
Stack trace:
#0 /www/mysite.eu/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(655): wp_mail()
#1 /www/mysite.eu/wp-content/plugins/woocommerce/includes/emails/class-wc-email-customer-new-account.php(110): WC_Email->send()
#2 /www/mysite.eu/wp-content/plugins/woocommerce/includes/class-wc-emails.php(392): WC_Email_Customer_New_Account->trigger()
#3 /www/mysite.eu/wp-includes/class-wp-hook.php(303): WC_Emails->customer_new_account()
#4 /www/mysite.eu/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#5 /www/mysite.eu/wp-includes/plugin.php(518): WP_Hook->do_action()
#6 /www/mysite.eu/wp-content/plugins/woocommerce/includes/class-wc-emails.php(170): do_action_ref_array()
#7 /www/mysite.eu/wp-includes/ in /www/mysite.eu/wp-includes/pluggable.php on line 182
```

**Expected behavior**
Creates the user account, the system sends the new user notification email successfully, order placed along with, user receives order email confirmation and gets redirected to the thank you page.

**Actual behavior**
 The account itself created but email notification obviously not receiving. The order itself fails to placed as well. User stucks on checkout page. No redirection to thank you page.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Enable *Settings / Account & privacy / Allow customers* to be able to create an account during checkout.
2. Create an order with no user logged in, with ticked *Create user account* checkbox.
3. Fill the necessery fields and place the order.
4. See error.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://mysite.eu
Site address (URL): https://mysite.eu
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: ❌ 5.8.1 - There is a newer version of WordPress available (5.8.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.22
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.31-MariaDB-0ubuntu0.20.04.1
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 21.66MB
Database Data Size: 16.02MB
Database Index Size: 5.64MB
wp_woocommerce_sessions: Data: 0.46MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.07MB + Index: 0.05MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.05MB + Engine MyISAM
wp_cartbounty: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_db7_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gdpr_cc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 1.34MB + Index: 2.16MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_icl_translate: Data: 0.25MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.08MB + Index: 0.19MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.20MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_url_file: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.28MB + Index: 0.26MB + Engine MyISAM
wp_postmeta: Data: 3.27MB + Index: 1.05MB + Engine MyISAM
wp_posts: Data: 2.52MB + Index: 0.11MB + Engine MyISAM
wp_revslider_css: Data: 0.09MB + Index: 0.01MB + Engine MyISAM
wp_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 481
customize_changeset: 1
mailpoet_page: 1
nav_menu_item: 37
page: 28
post: 7
product: 22
product_variation: 1
revision: 200
stockie_portfolio: 44
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.5.1
Advanced Custom Fields PRO: by Delicious Brains – 5.10.2
Advanced noCaptcha & invisible Captcha: by WP White Security – 6.1.7
Classic Editor: by WordPress Contributors – 1.6.2
Contact Form 7: by Takayuki Miyoshi – 5.5.2
Contact Form CFDB7: by Arshid – 1.2.6.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.1.2
Email Encoder - Protect Email Addresses: by Ironikus – 2.1.2
GDPR Cookie Compliance (CCPA, PIPEDA ready): by Moove Agency – 4.6.1
WPBakery Page Builder: by Michael M - WPBakery.com – 6.7.0
LiteSpeed Cache: by LiteSpeed Technologies – 4.4.4
Stockie Extra: by Colabrio – 1.0.8
Stockie Portfolio: by Colabrio – 1.0.0
CartBounty - Save and recover abandoned carts for WooCommerce: by Streamline.lv – 7.0.8
WooCommerce Multilingual: by OnTheGoSystems – 4.12.1
WooCommerce: by Automattic – 5.9.0
WP Mail SMTP: by WPForms – 3.2.0
WP Migrate DB: by Delicious Brains – 2.2.1
SEOPress: by SEOPress – 5.2.0
WPML String Translation: by OnTheGoSystems – 3.2.0

### Inactive Plugins (6) ###

Demo Import: by Colabrio – 2.2.3
Google Listings and Ads: by WooCommerce – 1.6.0
Jetpack: by Automattic – 10.3
Mailchimp for WooCommerce: by Mailchimp – 2.5.3
MailPoet 3 (New): by MailPoet – 3.73.2
WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.3.7.1

### Must Use Plugins (1) ###

WP Migrate DB Compatibility: by Delicious Brains – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #6020103 - /my-account/
Terms and conditions: #6020112 - /tos/

### Theme ###

Name: Stockie-child
Version: 1.0.0
Author URL: http://colabr.io/
Child Theme: ✔
Parent Theme Name: Stockie
Parent Theme Version: 1.3.0
Parent Theme Author URL: http://clbthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: stockie/woocommerce/archive-product.php
stockie/woocommerce/cart/cart-empty.php
stockie/woocommerce/cart/cart-shipping.php
stockie/woocommerce/cart/cart-totals.php
stockie/woocommerce/cart/cart.php
stockie/woocommerce/cart/cross-sells.php
stockie/woocommerce/cart/mini-cart.php
stockie/woocommerce/cart/proceed-to-checkout-button.php
stockie/woocommerce/checkout/form-billing.php
stockie/woocommerce/checkout/form-checkout.php
stockie/woocommerce/checkout/form-coupon.php
stockie/woocommerce/checkout/form-login.php
stockie/woocommerce/checkout/form-pay.php
stockie/woocommerce/checkout/form-shipping.php
stockie/woocommerce/checkout/payment-method.php
stockie/woocommerce/checkout/payment.php
stockie/woocommerce/checkout/review-order.php
stockie/woocommerce/checkout/terms.php
stockie/woocommerce/checkout/thankyou.php
stockie/woocommerce/content-product.php
stockie/woocommerce/content-single-product.php
stockie/woocommerce/content-widget-product.php
stockie/woocommerce/global/breadcrumb.php
stockie/woocommerce/global/form-login.php
stockie/woocommerce/global/quantity-input.php
stockie/woocommerce/global/wrapper-end.php
stockie/woocommerce/global/wrapper-start.php
stockie/woocommerce/loop/add-to-cart.php
stockie/woocommerce/loop/loop-end.php
stockie/woocommerce/loop/loop-start.php
stockie/woocommerce/loop/no-products-found.php
stockie/woocommerce/loop/orderby.php
stockie/woocommerce/loop/pagination.php
stockie/woocommerce/loop/sale-flash.php
stockie/woocommerce/myaccount/dashboard.php
stockie/woocommerce/myaccount/downloads.php
stockie/woocommerce/myaccount/form-login.php
stockie/woocommerce/myaccount/form-lost-password.php
stockie/woocommerce/myaccount/form-reset-password.php
stockie/woocommerce/myaccount/my-account.php
stockie/woocommerce/myaccount/my-address.php
stockie/woocommerce/myaccount/my-orders.php
stockie/woocommerce/myaccount/navigation.php
stockie/woocommerce/myaccount/orders.php
stockie/woocommerce/myaccount/payment-methods.php
stockie/woocommerce/notices/error.php
stockie/woocommerce/notices/notice.php
stockie/woocommerce/notices/success.php
stockie/woocommerce/order/order-again.php
stockie/woocommerce/order/order-details-customer.php version 3.4.4 is out of date. The core version is 5.6.0
stockie/woocommerce/order/order-details-item.php
stockie/woocommerce/order/order-details.php
stockie/woocommerce/order/order-downloads.php
stockie/woocommerce/product-searchform.php
stockie/woocommerce/single-product/add-to-cart/external.php
stockie/woocommerce/single-product/add-to-cart/grouped.php
stockie/woocommerce/single-product/add-to-cart/simple.php
stockie/woocommerce/single-product/add-to-cart/variable.php
stockie/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
stockie/woocommerce/single-product/add-to-cart/variation.php
stockie/woocommerce/single-product/meta.php
stockie/woocommerce/single-product/price.php
stockie/woocommerce/single-product/product-attributes.php
stockie/woocommerce/single-product/product-image.php
stockie/woocommerce/single-product/product-thumbnails.php
stockie/woocommerce/single-product/rating.php
stockie/woocommerce/single-product/related.php
stockie/woocommerce/single-product/review-meta.php
stockie/woocommerce/single-product/review-rating.php
stockie/woocommerce/single-product/review.php
stockie/woocommerce/single-product/sale-flash.php
stockie/woocommerce/single-product/share.php
stockie/woocommerce/single-product/short-description.php
stockie/woocommerce/single-product/tabs/additional-information.php
stockie/woocommerce/single-product/tabs/description.php
stockie/woocommerce/single-product/tabs/tabs.php
stockie/woocommerce/single-product/title.php
stockie/woocommerce/single-product/up-sells.php
stockie/woocommerce/single-product-reviews.php
stockie/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 334
Oldest: 2021-10-29 09:30:25 +0000
Newest: 2021-11-28 13:01:55 +0000

Pending: 1
Oldest: 2021-11-29 20:39:56 +0000
Newest: 2021-11-29 20:39:56 +0000


### Status report information ###

Generated at: 2021-11-28 13:50:31 +00:00
`
```
</details>

**Comment by swatipawarGS** [comment]
Hi @martincpt ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 5.9.0 version.

Please find below screencast for reference :


https://user-images.githubusercontent.com/94531721/144201526-19b9e856-69c6-4a52-85dc-d562a7dc8962.mp4


Please provide us more detailed steps and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by martincpt** [comment]
Thank you for your answer! 

Sorry, but I've just figured out it was a poorly written hook what caused this but logs didn't give me any proper hints first.

I appreciate your help though. I'm closing the issue now.
