### ISSUE TITLE
Carts with a deleted coupon crash on Redis-enabled sites

### ISSUE THREAD

**Issue by tomslominski** [woothemes/woocommerce#34066]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On sites with Redis enabled (using the Redis Object Cache plugin in testing), trying to open checkout with a coupon applied which has since been deleted leads to a falal PHP error occurring, and a critical error being displayed, preventing the user from loading the checkout.

I originally found this on a site with WooCommerce Subscriptions and an auto-apply coupon plugin, but it also happens on a fresh WP/WooCommerce environment.

I looked into the code, but I wasn't able to work out what exactly is causing the issue, as the Redis cache should be cleared when a coupon is deleted. If the cache is manually cleared after deleting the coupon, the issue does not occur (see step 4a - the cart is accessible, but has an error message).

### Expected behavior

Either the coupon should be silently discarded, or an error telling the user the coupon is no longer valid should be shown in checkout.

### Actual behavior

A PHP Fatal error:  Uncaught Exception: Invalid coupon. occurs, and the checkout becomes inaccessible until the Redis cache is cleared. This is the stacktrace of the error:

```
[26-Jul-2022 09:56:29 UTC] PHP Fatal error:  Uncaught Exception: Invalid coupon. in /Users/tom/Sites/wc/app/public/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php:118
Stack trace:
#0 /Users/tom/Sites/wc/app/public/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Coupon_Data_Store_CPT->read(Object(WC_Coupon))
#1 /Users/tom/Sites/wc/app/public/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(134): WC_Data_Store->read(Object(WC_Coupon))
#2 /Users/tom/Sites/wc/app/public/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(122): WC_Coupon->read_object_from_database()
#3 /Users/tom/Sites/wc/app/public/wp-content/plugins/woocommerce/includes/class-wc-cart.php(723): WC_Coupon->__construct('test')
#4 /Users/tom/Sites/wc/app/public/wp-includes/class-wp-hook.php(307): WC_Cart->check_cart_coupons('')
#5 /Users/tom/Sites/wc/app/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(true, Array)
#6 /Users/tom/Sites/wc/app/public/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#7 /Users/tom/Sites/wc/app/public/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(292): do_action('woocommerce_che...')
#8 /Users/tom/Sites/wc/app/public/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(67): WC_Shortcode_Checkout::checkout()
#9 /Users/tom/Sites/wc/app/public/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_Checkout::output('')
#10 /Users/tom/Sites/wc/app/public/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(95): WC_Shortcodes::shortcode_wrapper(Array, '')
#11 /Users/tom/Sites/wc/app/public/wp-includes/shortcodes.php(356): WC_Shortcodes::checkout('', '', 'woocommerce_che...')
#12 [internal function]: do_shortcode_tag(Array)
#13 /Users/tom/Sites/wc/app/public/wp-includes/shortcodes.php(228): preg_replace_callback('/\\[(\\[?)(woocom...', 'do_shortcode_ta...', '[woocommerce_ch...')
#14 /Users/tom/Sites/wc/app/public/wp-includes/class-wp-hook.php(307): do_shortcode('[woocommerce_ch...')
#15 /Users/tom/Sites/wc/app/public/wp-includes/plugin.php(191): WP_Hook->apply_filters('[woocommerce_ch...', Array)
#16 /Users/tom/Sites/wc/app/public/wp-includes/blocks/post-content.php(55): apply_filters('the_content', '<!-- wp:shortco...')
#17 /Users/tom/Sites/wc/app/public/wp-includes/class-wp-block.php(255): render_block_core_post_content(Array, '<!-- wp:shortco...', Object(WP_Block))
#18 /Users/tom/Sites/wc/app/public/wp-includes/class-wp-block.php(241): WP_Block->render()
#19 /Users/tom/Sites/wc/app/public/wp-includes/blocks.php(901): WP_Block->render()
#20 /Users/tom/Sites/wc/app/public/wp-includes/blocks.php(939): render_block(Array)
#21 /Users/tom/Sites/wc/app/public/wp-includes/block-template.php(240): do_blocks('<!-- wp:templat...')
#22 /Users/tom/Sites/wc/app/public/wp-includes/template-canvas.php(12): get_the_block_template_html()
#23 /Users/tom/Sites/wc/app/public/wp-includes/template-loader.php(106): include('/Users/tom/Site...')
#24 /Users/tom/Sites/wc/app/public/wp-blog-header.php(19): require_once('/Users/tom/Site...')
#25 /Users/tom/Sites/wc/app/public/index.php(17): require('/Users/tom/Site...')
#26 {main}
  thrown in /Users/tom/Sites/wc/app/public/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php on line 118
```

### Steps to reproduce

1) Create a coupon in the back-end.
2) In a separate session, add a product to cart and apply the coupon.
3) Move the coupon to bin and then delete it permanently.
4) In the other session, go to checkout again and see that a critical error has occurred.
4a) The checkout is accessible again if Redis cache is cleared, albeit with the message "There are some issues with the items in your cart. Please go back to the cart page and resolve these issues before checking out."

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://wc.local
Site address (URL): http://wc.local
WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.8.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: wp_
Total Database Size: 4.80MB
Database Data Size: 3.37MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 2
product: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Redis Object Cache: by Till Krüss – 2.1.6
WooCommerce: by Automattic – 6.7.0

### Dropin Plugins (1) ###

object-cache.php: Redis Object Cache Drop-In

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-27 09:54:07 +00:00
Options: ✔
Notes: 36
Onboarding: completed

### Action Scheduler ###

Complete: 5
Oldest: 2022-07-26 09:55:25 +0000
Newest: 2022-07-26 09:55:25 +0000

Pending: 1
Oldest: 2022-07-27 09:55:25 +0000
Newest: 2022-07-27 09:55:25 +0000

### Status report information ###

Generated at: 2022-07-26 10:02:31 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jrick1229** [comment]
Verified I'm seeign the same on Pressable hosting.

**Comment by davewhitley** [comment]
I'm also seeing this error on my live site on WordPress.com.

**Comment by davewhitley** [comment]
This is actually affecting a handful of end customers on a site that I manage (all they see is a fatal error), and this issue was logged months ago. Is there a fix? Can it be bumped in priority?

**Comment by davewhitley** [comment]
Asking again for a bump in priority because customers are getting a "critical error" white screen of death because of this issue. Or, if there is a way to manually flush the cache after deleting a coupon that would be valuable information.

**Comment by opr** [comment]
I am reassigning this to Proton as I believe it's a Data Store issue, rather than an issue with the Cart/Checkout itself. Confirming that I can reproduce this though.

**Comment by marwankhanfar** [comment]
The issue is still happening, Redis is caching coupons and not updated on deletion

**Comment by johanmolen** [comment]
Having the same issue, in my opinion a critical issue.

**Comment by johanmolen** [comment]
For people running into this issue, adding this action to my code seems to "fix" it:

```php
        add_action('wp_trash_post', function ($post_id) {
            $post = get_post($post_id);

            if (
                $post &&
                $post->post_type === 'shop_coupon'
            ) {
                wp_cache_delete(\WC_Cache_Helper::get_cache_prefix('coupons').'coupon_id_from_code_'.$post->post_title, 'coupons');
            }
        });
```

**Comment by johanmolen** [comment]
Can we get a permanent fix for this?

**Comment by prettyboymp** [comment]
**Root-cause analysis** for whoever picks up the proper fix.

### The cache invalidation gap

The `coupon_id_from_code_*` lookup cache (set in `wc_get_coupon_id_by_code()`) is cleared in only two places:

- `WC_Coupon_Data_Store_CPT::delete()` — force-delete branch
- `WC_Coupon_Data_Store_CPT::update()` — when status changes away from `publish`

Nothing hooks WP's post-delete lifecycle for coupons:

- `class-wc-post-data.php` registers a `delete_post` handler, but its switch only handles `product`, `product_variation`, and `shop_order` — there's no `shop_coupon` case.
- No other code in core invalidates this cache on `delete_post`, `before_delete_post`, or `trashed_post`.

### When the bug triggers

Any deletion that bypasses `WC_Coupon::delete( true )` leaves a stale cache entry:

- Admin "Delete Permanently" on the coupons list (uses \`wp_delete_post\` directly — this is the path in the original repro)
- WP-CLI \`wp post delete <id> --force\`
- Empty Trash
- Plugin/theme code calling \`wp_delete_post()\`

The stale entry is invisible with an in-process cache (wiped per request) but persists with Redis/Memcached — which is why this only reproduces on sites with a persistent object cache.

### Suggested fix

Add a \`shop_coupon\` case to \`delete_post_data()\` (or a dedicated handler on \`delete_post\` / \`trashed_post\`) that clears \`coupon_id_from_code_<hashed-code>\` from the \`coupons\` cache group.

This invalidates the cache regardless of which deletion path is used, and removes the exposure for every \`new WC_Coupon( \$code )\` call site without per-call defenses, including:

- \`WC_Cart::check_cart_coupons\` (legacy shortcode checkout)
- \`CartController::validate_cart_coupons\` (Store API / Block Checkout)
- \`WC_Cart::get_coupons()\`, \`check_customer_coupons()\`
- \`wc_cart_totals_coupon_label\` / \`wc_cart_totals_coupon_html\`
- Several sites in \`abstract-wc-order.php\`

**Comment by pierorocca** [comment]
Hi @tomslominski - thanks for the report.

I know this has been open for a very long time, and I appreciate your patience. We're currently going through some older WooCommerce issues, identifying what still needs fixing, and tidying up what's already fixed or out of scope.

I've taken a look and marked this ready for the engineering team to pick up.

What I'm seeing: Current trunk still instantiates `new WC_Coupon( $code )` in `WC_Cart::check_cart_coupons()` without catching the invalid-coupon exception, and `delete_post_data()` still has no `shop_coupon` cache-invalidation path. Open PR #64403 is explicitly linked and targets this fatal path.
