### ISSUE TITLE
Fix `ContainerException` bug with running code-analyzer

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#34196]
When running the code-analyzer and starting `wp-env` the environment's crash with some kind of classloading issue. 

Its possible we're not running some kind of composer setup that is crucial for the classes to load.

The error:

```
Fatal error: Uncaught Automattic\WooCommerce\Vendor\League\Container\Exception\ContainerException: A service provider must be a fully qualified class name or instance of (\Automattic\WooCommerce\Vendor\League\Container\ServiceProvider\ServiceProviderInterface) in /var/www/html/wp-content/plugins/woocommerce/lib/packages/League/Container/ServiceProvider/ServiceProviderAggregate.php:52
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/lib/packages/League/Container/Container.php(146): Automattic\WooCommerce\Vendor\League\Container\ServiceProvider\ServiceProviderAggregate->add('Automattic\\WooC...')
#1 /var/www/html/wp-content/plugins/woocommerce/src/Container.php(83): Automattic\WooCommerce\Vendor\League\Container\Container->addServiceProvider('Automattic\\WooC...')
#2 /var/www/html/wp-content/plugins/woocommerce/woocommerce.php(38): Automattic\WooCommerce\Container->__construct()
#3 /var/www/html/wp-settings.php([42](https://github.com/woocommerce/woocommerce/runs/7681747514?check_suite_focus=true#step:4:43)8): include_once('/var/www/html/w...')
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/R in /var/www/html/wp-content/plugins/woocommerce/lib/packages/League/Container/ServiceProvider/ServiceProviderAggregate.php on line 52
```

**Comment by samueljseay** [comment]
I haven't been able to reproduce this since I last saw it. I'm going to close it for now and reopen if I manage to find a branch causing this issue.

**Comment by samueljseay** [comment]
I managed to reproduce this yesterday on trunk
