### ISSUE TITLE
Storybook: Tour Kit stories do not load and throw error

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#34753]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When Storybook is run (`pnpm --filter=@woocommerce/storybook storybook`), Tour Kit stories do not load. In addition, it shows an error in both the Actions tab and in the web dev console.

### Expected behavior

* Tour Kit stories appear in Storybook
* No errors when viewing other stories

### Actual behavior

* Tour Kit stories do not appear in Storybook
* Error when viewing other stories

### Steps to reproduce

1. Run Storybook: `pnpm --filter=@woocommerce/storybook storybook`
2. Go to any story
3. See the following error in the Actions tab in Storybook, and in the web browser dev console

```
error: "Unexpected error while loading ./tour-kit/stories/index.tsx: exports is not defined
 ReferenceError: exports is not defined
    at ../../node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/browser.js (http://localhost:6007/vendors-node_modules_pnpm_automattic_interpolate-components_1_2_1_adlholpkqbiq5amp2fy4vkqcli_-6aa8df.iframe.bundle.js:86363:1)
    at __webpack_require__ (http://localhost:6007/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6007/runtime~main.iframe.bundle.js:347:21)
    at ../../node_modules/.pnpm/@automattic+tour-kit@1.1.1_ewcciyhsqon3yluv5ntlvxyvvm/node_modules/@automattic/tour-kit/dist/esm/utils/index.js (http://localhost:6007/vendors-node_modules_pnpm_automattic_interpolate-components_1_2_1_adlholpkqbiq5amp2fy4vkqcli_-6aa8df.iframe.bundle.js:979:63)
    at __webpack_require__ (http://localhost:6007/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6007/runtime~main.iframe.bundle.js:347:21)
    at ../../node_modules/.pnpm/@automattic+tour-kit@1.1.1_ewcciyhsqon3yluv5ntlvxyvvm/node_modules/@automattic/tour-kit/dist/esm/components/tour-kit-frame.js (http://localhost:6007/vendors-node_modules_pnpm_automattic_interpolate-components_1_2_1_adlholpkqbiq5amp2fy4vkqcli_-6aa8df.iframe.bundle.js:282:64)
    at __webpack_require__ (http://localhost:6007/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6007/runtime~main.iframe.bundle.js:347:21)
    at ../../node_modules/.pnpm/@automattic+tour-kit@1.1.1_ewcciyhsqon3yluv5ntlvxyvvm/node_modules/@automattic/tour-kit/dist/esm/components/tour-kit.js (http://localhost:6007/vendors-node_modules_pnpm_automattic_interpolate-components_1_2_1_adlholpkqbiq5amp2fy4vkqcli_-6aa8df.iframe.bundle.js:688:73)"
```

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mattsherman** [comment]
@chihsuan Since you added the Tour Kit to Storybook initially (in #33229), I thought you might have some idea why they are no longer loading!
