### ISSUE TITLE
[COT] WC_Order::get_refunds() results in fatal error

### ISSUE THREAD

**Issue by DavidAnderson684** [woothemes/woocommerce#34912]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Using version: 7.0.0-hpos.dev.4

Calling WC_Order::get_refunds() results in a fatal error.

### Steps to reproduce

N.B. Order 1249 on this testing site does have a refund.

```
$ php80 -a
Interactive shell
php > echo PHP_VERSION;
8.0.23
php > require 'wp-load.php';
php > $order_id=1249;
php > $order = wc_get_order(1249);
php > $refunds = $order->get_refunds();
PHP Warning:  Uncaught TypeError: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore::init_order_record(): Argument #1 ($order) must be of type WC_Order, Automattic\WooCommerce\Admin\Overrides\OrderRefund given, called in wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php on line 960 and defined in wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:977
Stack trace:
#0 wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(960): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->init_order_record()
#1 wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableRefundDataStore.php(97): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->read_multiple()
#2 wp-content/plugins/woocommerce/includes/class-wc-data-store.php(171): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableRefundDataStore->read_multiple()
#3 wp-content/plugins/woocommerce/includes/class-wc-order-factory.php(119): WC_Data_Store->read_multiple()
#4 wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(2092): WC_Order_Factory::get_orders()
#5 wp-content/plugins/woocommerce/includes/class-wc-data-store.php(224): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->query()
#6 wp-content/plugins/woocommerce/includes/class-wc-order-query.php(87): WC_Data_Store->__call()
#7 wp-content/plugins/woocommerce/includes/wc-order-functions.php(68): WC_Order_Query->get_orders()
#8 wp-content/plugins/woocommerce/includes/class-wc-order.php(2001): wc_get_orders()
#9 php shell code(1): WC_Order->get_refunds()
#10 {main}
  thrown in wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php on line 977
```

### WordPress Environment

WC: 7.0.0-hpos.dev.4
WP: 6.0.2
PHP: 8.0.23

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
Thanks for reporting and testing!

This should be fixed as https://github.com/woocommerce/woocommerce/pull/34465 progressed and until it was merged. Please check and let us know if the [latest package](https://github.com/woocommerce/woocommerce/releases/tag/feature-custom-order-table) resolved the issue for you. Thanks!
