### ISSUE TITLE
Unable to instantiate WC_Order_Item by id (Uncaught Exception)

### ISSUE THREAD

**Issue by perrelet** [woothemes/woocommerce#35548]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Running

`new WC_Order_Item($order_item_id)`

Throws:

`Fatal error: Uncaught Exception: Invalid order. in /home/courses/public_html/site/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:104 Stack trace: #0 /home/courses/public_html/site/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order_Item))`

Despite the constructor docbock reading:

```
/**
* Constructor.
*
* @param int|object|array $item ID to load from the DB, or WC_Order_Item object.
*/
```

### Expected behavior

Instantiate WC_Order_Item  by id

### Actual behavior

Critical Exception

### Steps to reproduce

Run `new WC_Order_Item($order_item_id)`

### WordPress Environment

Core

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by petermorlion** [comment]
I had the same issue. Looking at the code, I believe the issue is caused because:

- WC_Order_Item's `get_type()` function returns ''
- In the same class, in the constructor, the data store is loaded, based on a certain key, which is `order-item-` + the type. The type is empty, so it's `order-item-`
- This data store is looked up in the `stores` in the WC_Data_Store class, which doesn't exist
- In the WC_Data_Store constructor, the `explode` function is then used to load the `order` store

And your id doesn't exist in the order store.

The issue is that you're trying to load a WC_Order_Item, but the type is implemented by child classes. The types you could load are:

- WC_Order_Item_Tax
- WC_Order_Item_Fee
- WC_Order_Item_Product
- WC_Order_Item_Shipping
- WC_Order_Item_Coupon

So I think the code is working as intended, but you need to load a more specific type? Or the code needs to change so the ending `-` is dropped and the `order-item` store is loaded.

**Comment by perrelet** [comment]
@petermorlion I agree with your assessment. For our use case `WC_Order_Item_Product` was the ticket.

Perhaps this is a candidate for a `doing_it_wrong` exception - saving future souls from falling into the same non-type abyss?

**Comment by tradesouthwest** [comment]
Tried to find a trac on this for `type: bug` but did not see any followup on this issue. Is it still on track for fixing.

similar errors:

`2023/08/19 00:00:25 [error] 56118#56118: *530702 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Invalid product. in /www/website/public/wp-content/plugins/woocommerce/
includes/data-stores/class-wc-product-data-store-cpt.php:167`

and:

`Stack trace:
#0 /www/website/public/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Product_Data_Store_CPT->read(Object(WC_Product_Simple))
#1 /www/website/public/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(138): WC_Data_Store->read(Object(WC_Product_Simple))
#2 /www/website/public/wp-content/plugins/woocommerce/includes/class-wc-product-simple.php(24): WC_Product->__construct(3883)
#3 /www/website/public/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php(383): WC_Product_Simple->__construct(3883)
#4 /www/website/public/wp-content/plugins/woocommerce/includes/
rest-api/Controllers/Version3/class-wc-rest-crud-controller.php(163): 
WC_REST_Products_Controller->prepare_object_f" while reading response header 
from upstream, client: 223.27.15.136, server: website.co.nz, 
request: "PUT /wp-json/wc/v3/products/3883 HTTP/2.0", 
upstream: "fastcgi://unix:/var/run/php8.0-fpm-website.sock:", 
host: "website.co.nz:50510"`

**Comment by barryhughes** [comment]
If it shouldn't be instantiated directly, we probably need to make that clearer (by throwing a more specific exception, etc).
