### ISSUE TITLE
`@woocommerce/e2e-environment` is not compatible with Node 16

### ISSUE THREAD

**Issue by tomalec** [woothemes/woocommerce#35650]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I was trying to upgrade our extension to follow `woocommerce/woocommerce` and use Node 16.
However, it fails to install due to `@woocommerce/e2e-environment` incompatibility

### Expected behavior

`@woocommerce/e2e-environment` should work at least with the Node version specified in WooCommerce's [`.nvmrc`](https://github.com/woocommerce/woocommerce/blob/trunk/.nvmrc)

### Actual behavior

Installation throws

### Steps to reproduce

0. Use node 16
1.  Start a new project from scratch, 
2. install `@woocommerce/e2e-environment`
```sh
nvm use 16
npm init
npm i @woocommerce/e2e-environment
```

```
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /home/tomalec/.nvm/versions/node/v16.18.0/bin/node /home/tomalec/.nvm/versions/node/v16.18.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/tomalec/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > @automattic/puppeteer-utils@0.0.1 postinstall
npm ERR! > npm run build
npm ERR! 
npm ERR! 
npm ERR! > @automattic/puppeteer-utils@0.0.1 build
npm ERR! > babel --presets=@babel/preset-env src -d lib
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN old lockfile 
npm ERR! npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm ERR! npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm ERR! npm WARN old lockfile 
npm ERR! npm WARN old lockfile This is a one-time fix-up, please be patient...
npm ERR! npm WARN old lockfile 
npm ERR! npm WARN old lockfile Error: Integrity checksum failed when using sha512: wanted sha512-mqAC2r1NDmRjG+z3KCJ/i61tycKlmADIjxnDhQab+KBxSAGbF/W7/zwB2guy/ypIeKrrftNsIYkNZZQKf3vJcg== but got sha512-s7PoyDv/II1ObgQunCbB9PdLmUcBZcnWOcxDh7O0N/UwDEsHyqkW+Qh28jW+mVuCdx7gLB0BotYI1Y6uI9iyew==.
npm ERR! npm WARN old lockfile     at RegistryFetcher.manifest (/home/tomalec/.nvm/versions/node/v16.18.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:152:35)
npm ERR! npm WARN old lockfile     at async Array.<anonymous> (/home/tomalec/.nvm/versions/node/v16.18.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:738:24)
npm ERR! npm WARN old lockfile  Could not fetch metadata for prettier@1.19.1 Error: Integrity checksum failed when using sha512: wanted sha512-mqAC2r1NDmRjG+z3KCJ/i61tycKlmADIjxnDhQab+KBxSAGbF/W7/zwB2guy/ypIeKrrftNsIYkNZZQKf3vJcg== but got sha512-s7PoyDv/II1ObgQunCbB9PdLmUcBZcnWOcxDh7O0N/UwDEsHyqkW+Qh28jW+mVuCdx7gLB0BotYI1Y6uI9iyew==.
npm ERR! npm WARN old lockfile     at RegistryFetcher.manifest (/home/tomalec/.nvm/versions/node/v16.18.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:152:35)
npm ERR! npm WARN old lockfile     at async Array.<anonymous> (/home/tomalec/.nvm/versions/node/v16.18.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:738:24) {
npm ERR! npm WARN old lockfile   code: 'EINTEGRITY'
npm ERR! npm WARN old lockfile }
npm ERR! npm WARN deprecated request-promise-native@1.0.8: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! npm WARN deprecated w3c-hr-time@1.0.1: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm ERR! npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm ERR! npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm ERR! npm WARN deprecated uuid@3.3.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated source-map-resolve@0.5.2: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! npm WARN deprecated puppeteer@2.0.0: Version no longer supported. Upgrade to @latest
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/tomalec/.npm/_cacache/tmp/git-clonepuBHxa/node_modules/@babel/helper-compilation-targets/package.json
npm ERR!     at new NodeError (node:internal/errors:387:5)
npm ERR!     at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
npm ERR!     at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
npm ERR!     at resolveExports (node:internal/modules/cjs/loader:522:36)
npm ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:562:31)
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:833:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1057:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at Object.<anonymous> (/home/tomalec/.npm/_cacache/tmp/git-clonepuBHxa/node_modules/@babel/preset-env/lib/debug.js:8:33) {
npm ERR!   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
npm ERR! }
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/tomalec/.npm/_cacache/tmp/git-clonepuBHxa
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c -- npm run build
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/tomalec/.npm/_logs/2022-11-20T17_37_25_127Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tomalec/.npm/_logs/2022-11-20T17_36_19_848Z-debug-0.log
```

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by thejamescollins** [comment]
We're also affected by this when trying to add E2E tests to our WooCommerce extension using the https://github.com/woocommerce/woocommerce-e2e-boilerplate.

It looks like the `@woocommerce/e2e-environment` package is being [maintained and improved in this monorepo](https://github.com/woocommerce/woocommerce/commits/trunk/packages/js/e2e-environment), but the [last release on npmjs.com was v0.3.0 on 2/3/2022](https://www.npmjs.com/package/@woocommerce/e2e-environment).

Likewise, the `@woocommerce/e2e-utils` package is being [maintained and improved in this monorepo](https://github.com/woocommerce/woocommerce/commits/trunk/packages/js/e2e-utils), but the [last release on npmjs.com was v0.2.0 on 2/3/2022](https://www.npmjs.com/package/@woocommerce/e2e-utils).

It is possible for the WooCommerce core team to release new versions of `@woocommerce/e2e-environment` and `@woocommerce/e2e-utils`, so that all of the changes made in this monorepo can be easily used by others in the WooCommerce ecosystem?

Thank you!

**Comment by tomalec** [comment]
ping @woocommerce/masamune

**Comment by Luc45** [comment]
> Contributor

Hi @om4james, in 2022, the WooCommerce Core E2E tests has gone through a major refactor, and was entirely rewritten using the [Playwright](https://playwright.dev/) Testing Framework.

The `@woocommerce/e2e-environment` and `@woocommerce/e2e-utils` packages are from the old E2E testing stack using [Puppeteer](https://pptr.dev/), that we don't use nor maintain anymore. We just haven't pulled it out yet because we don't have the Playwright Environment packages alternative to offer for third party developers.

That said, the support for those packages is limited for now, and only includes breaking changes.

We are working to make our E2E testing setup more flexible to be used by third-party developers in their own codebases.  I'd suggest taking a look at the new Playwright E2E tests for inspiration: https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/tests/e2e-pw - you can either wait until we have the Playwright packages available for third parties, or use a fresh installation of Playwright directly to mimick the E2E testing stack of WooCommerce Core.

**Comment by adimoldovan** [comment]
`@woocommerce/e2e-environment` package [has been deprecated](https://developer.woocommerce.com/2025/06/10/developer-advisory-deprecation-notice-for-unsupported-woocommerce-npm-packages/) and soon [will be removed](https://github.com/woocommerce/woocommerce/pull/58643). Closing this issue.
