### ISSUE TITLE
fatal wc_get_logger error in WooCommerce Beta Tester

### ISSUE THREAD

**Issue by samueljseay** [woothemes/woocommerce#35734]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Brought to my attention by @lanej0 :

GlobalStep brought my attention to the fact that trying to install the WooCommerce Beta Tester plugin (and activate it) causes a critical error on Jurassic Ninja.  

I was able to reproduce it, I created a JN site, installed WooCommerce (but didn’t activate it) and then installed WC Beta Tester and clicked Activate.  When I did, I saw:

```
Warning: Use of undefined constant WC_ABSPATH - assumed ‘WC_ABSPATH’ (this will throw an Error in a future version of PHP) in /srv/users/user74c02409/apps/user74c02409/public/wp-content/plugins/woocommerce-beta-tester/api/tracks/class-tracks-debug-log.php on line 30
Warning: include_once(WC_ABSPATHincludes/tracks/class-wc-tracks-client.php): failed to open stream: No such file or directory in /srv/users/user74c02409/apps/user74c02409/public/wp-content/plugins/woocommerce-beta-tester/api/tracks/class-tracks-debug-log.php on line 30
Warning: include_once(): Failed opening ‘WC_ABSPATHincludes/tracks/class-wc-tracks-client.php’ for inclusion (include_path=‘.:/opt/sp/php7.4/lib/php’) in /srv/users/user74c02409/apps/user74c02409/public/wp-content/plugins/woocommerce-beta-tester/api/tracks/class-tracks-debug-log.php on line 30
Warning: Use of undefined constant WC_ABSPATH - assumed ‘WC_ABSPATH’ (this will throw an Error in a future version of PHP) in /srv/users/user74c02409/apps/user74c02409/public/wp-content/plugins/woocommerce-beta-tester/api/tracks/class-tracks-debug-log.php on line 31
Warning: include_once(WC_ABSPATHincludes/tracks/class-wc-tracks-footer-pixel.php): failed to open stream: No such file or directory in /srv/users/user74c02409/apps/user74c02409/public/wp-content/plugins/woocommerce-beta-tester/api/tracks/class-tracks-debug-log.php on line 31
Warning: include_once(): Failed opening ‘WC_ABSPATHincludes/tracks/class-wc-tracks-footer-pixel.php’ for inclusion (include_path=‘.:/opt/sp/php7.4/lib/php’) in /srv/users/user74c02409/apps/user74c02409/public/wp-content/plugins/woocommerce-beta-tester/api/tracks/class-tracks-debug-log.php on line 31
Fatal error: Uncaught Error: Call to undefined function wc_get_logger() in /srv/users/user74c02409/apps/user74c02409/public/wp-content/plugins/woocommerce-beta-tester/api/tracks/class-tracks-debug-log.php:33 Stack trace: #0 /srv/users/user74c02409/apps/user74c02409/public/wp-content/plugins/woocommerce-beta-tester/api/tracks/class-tracks-debug-log.php(87): Tracks_Debug_Log->__construct() #1 /srv/users/user74c02409/apps/user74c02409/public/wp-content/plugins/woocommerce-beta-tester/api/api.php(53): require(‘/srv/users/user...‘) #2 /srv/users/user74c02409/apps/user74c02409/public/wp-content/plugins/woocommerce-beta-tester/plugin.php(15): require(‘/srv/users/user...‘) #3 /srv/users/user74c02409/apps/user74c02409/public/wp-includes/class-wp-hook.php(308): {closure}(‘’) #4 /srv/users/user74c02409/apps/user74c02409/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #5 /srv/users/user74c02409/apps/user74c02409/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #6 /srv/users/user74c02409/app in /srv/users/user74c02409/apps/user74c02409/public/wp-content/plugins/woocommerce-beta-tester/api/tracks/class-tracks-debug-log.php on line 33
```

### Expected behavior

Installing/Activating WC Beta Tester should not cause an error.

### Actual behavior

A fatal error happens (see the logs in description)

It's possible that when beta tester goes to install a different version of WooCommerce that there will be some time where wc_get_logger is not available and this would cause it to crash. Perhaps WooCommerce Beta Tester should not rely on wc_get_logger for this reason.

### Steps to reproduce

1. Create a local site with WooCommerce 7.1 
2. Instal and activate WC Beta Tester 
3. Then use the Beta Tester plugin to update to 7.2 beta and it will crash with `Fatal error: Uncaught Error: Call to undefined function wc_get_logger()`

### WordPress Environment

Jurassic Ninja

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment]
Draft fix [here.](https://github.com/woocommerce/woocommerce/pull/35742)
