### ISSUE TITLE
DownloadPermissionsAdjuster Fatal TypeError with PHP 8.0 when saving variable product and wp-cron runs

### ISSUE THREAD

**Issue by therealgilles** [woothemes/woocommerce#35916]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Here is the partial trace log:

```
[10-Dec-2022 23:59:05 UTC] [ERROR] lvl:1 | msg:Uncaught TypeError: Argument 1 passed to Automattic\WooCommerce\Internal\DownloadPermissionsAdjuster::get_download_files_and_permissions() must be an instance of WC_Product, bool given, called in .../public_html/wp-content/plugins/woocommerce/src/Internal/DownloadPermissionsAdjuster.php on line 103 and defined in .../public_html/wp-content/plugins/woocommerce/src/Internal/DownloadPermissionsAdjuster.php:138
Stack trace:
#0 .../public_html/wp-content/plugins/woocommerce/src/Internal/DownloadPermissionsAdjuster.php(103): Automattic\WooCommerce\Internal\DownloadPermissionsAdjuster->get_download_files_and_permissions(false)
#1 .../public_html/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Internal\DownloadPermissionsAdjuster->adjust_download_permissions(256174)
#2 .../public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#3 .../publ | file:.../public_html/wp-content/plugins/woocommerce/src/Internal/DownloadPermissionsAdjuster.php | ln:138
```

### Expected behavior

No PHP fatal error.

### Actual behavior

The type error triggers a PHP fatal error.

### Steps to reproduce

Not sure as this is triggered by wp-cron.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://mysite.com
Site address (URL): https://mysite.com
WC Version: 7.1.1
REST API Version: ✔ 7.1.1
WC Blocks Version: ✔ 8.7.6
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.23
PHP Post Max Size: 16 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.6.11-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.1
WC Database Prefix: wp_
Total Database Size: 1202.11MB
Database Data Size: 772.67MB
Database Index Size: 429.44MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 7.52MB + Index: 8.55MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.56MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 1.13MB + Engine InnoDB
wp_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_addactionsandfilters_plugin_usercode: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_admin_columns: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_bp_notifications: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf7dbplugin_st: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf7dbplugin_submits: Data: 0.48MB + Index: 0.28MB + Engine InnoDB
wp_cleanup_optimizer_block_range_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_block_single_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_db_scheduler: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_licensing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_login_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_plugin_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleanup_optimizer_wp_scheduler: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_comments: Data: 9.52MB + Index: 9.09MB + Engine InnoDB
wp_cptch_blacklist_ip: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cptch_track_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cptch_track_visitor: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_email_log: Data: 72.52MB + Index: 0.00MB + Engine InnoDB
wp_ewwwio_images: Data: 1.52MB + Index: 0.83MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hctpc_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hctpc_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hctpc_whitelist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_bans: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_itsec_dashboard_events: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 1.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 6.02MB + Index: 8.11MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_avatar: Data: 5.52MB + Index: 2.97MB + Engine InnoDB
wp_litespeed_crawler: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_litespeed_crawler_blacklist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url: Data: 5.52MB + Index: 9.06MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_oauth_access_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oauth_authorization_codes: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_oauth_jwt: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_public_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_refresh_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oauth_scopes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 16.45MB + Index: 1.31MB + Engine InnoDB
wp_podsrel: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_postexpirator_debug: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 71.59MB + Index: 46.14MB + Engine InnoDB
wp_posts: Data: 338.53MB + Index: 8.63MB + Engine InnoDB
wp_pum_subscribers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_redirection_404: Data: 1.02MB + Index: 2.09MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_relevanssi: Data: 7.36MB + Index: 11.64MB + Engine InnoDB
wp_relevanssi_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sm_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tec_events: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_tec_occurrences: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_tec_series_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_term_relationships: Data: 1.30MB + Index: 0.48MB + Engine InnoDB
wp_term_taxonomy: Data: 0.23MB + Index: 0.31MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_toolset_post_guid_id: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_updraftcentral_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_updraftcentral_sitemeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_updraftcentral_sites: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_updraftcentral_site_temporary_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_updraftcentral_user_cron: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_upme_post_features: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 10.52MB + Index: 8.03MB + Engine InnoDB
wp_users: Data: 0.33MB + Index: 0.27MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.31MB + Index: 0.30MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.31MB + Index: 0.45MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_wc_order_stats: Data: 0.39MB + Index: 3.94MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_osmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.09MB + Index: 0.17MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_status_action: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpfront_ure_post_type: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfront_ure_taxonomy: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wp_topbar_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Data: 149.20MB + Index: 279.22MB + Engine InnoDB
wp_wsal_occurrences: Data: 53.08MB + Index: 21.06MB + Engine InnoDB
wp_zerospam_blocked_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zerospam_log: Data: 0.16MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

_pods_field: 10
_pods_group: 6
_pods_pod: 6
action_monitor: 125
attachment: 851
curriculum-topic: 145
document: 34
flamingo_contact: 22232
flamingo_inbound: 877
internal-document: 64
itsec-dash-card: 4
itsec-dashboard: 1
jetpack_migration: 2
nav_menu_item: 72
oembed_cache: 1
page: 46
popup: 1
popup_theme: 7
pos_custom_product: 1
pos_temp_register_or: 5
post: 149
product: 355
product_config: 4
product_variation: 387
revision: 998
shop_coupon: 138
shop_order: 8302
shop_order_refund: 186
staff: 72
tablepress_table: 4
team_member: 1
templatera: 25
tribe_event_series: 67
tribe_events: 346
tribe_filters: 2
tribe_organizer: 39
tribe_venue: 7
tribe-ea-record: 2
um_directory: 1
um_form: 3
um_role: 2
user_request: 1
vc_grid_item: 3
vc_settings_preset: 3
wccpf: 1
wll_records: 1940
wo_client: 3
wp-rest-api-log: 2573
wpcf7_contact_form: 4
wpex_font: 1
wpex_widget_area: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (109) ###

Add Shortcodes Actions And Filters: by Michael Simpson – 2.0.9
Admin Columns Pro: by AdminColumns.com – 6.0.2
Admin Menu Editor: by Janis Elsts – 1.10.4
Advanced Post Manager: by Modern Tribe
Inc. – 4.5.3

iThemes Security: by iThemes – 8.1.4
Bootstrap Modals: by Neil Gee – 1.3.2
Five Star Business Profile and Schema: by Five Star Plugins – 2.2.5
Classic Editor: by WordPress Contributors – 1.6.2
Cloudflare: by Cloudflare
Inc. – 4.11.0

Honeypot for Contact Form 7: by Nocean – 2.1.1
Contact Form DB: by Michael Simpson – 2.10.29
Contact Form 7: by Takayuki Miyoshi – 5.7
Convert Post Types: by Stephanie Leary – 1.4
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.3
Custom Content Shortcode: by Eliot Akira – 4.0.2
Debug Bar: by wordpressdotorg – 1.1.4
Delete Me: by Clinton Caldwell – 3.0
Disable Cart Fragments: by Optimocha – 2.1.1
Disable Comments: by WPDeveloper – 2.4.2
Disable Elements for WPBakery Page Builder: by WPExplorer – 1.0
Disable Emojis (GDPR friendly): by Ryan Hellyer – 1.7.4
Duplicate Menu: by Jonathan Christopher – 0.2.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Duplicator: by Snap Creek – 1.5.1
Email Address Encoder: by Till Krüss – 1.0.22
Email Log: by Sudar – 2.4.8
Email Obfuscate Shortcode: by khromov – 2.0
Enable Media Replace: by ShortPixel – 4.0.1
Envato Market: by Envato – 2.0.7
The Events Calendar PRO: by The Events Calendar – 6.0.4
EWWW Image Optimizer: by Exactly WWW – 6.9.2
Flamingo: by Takayuki Miyoshi – 2.3
Google XML Sitemaps: by Auctollo – 4.1.7
Hello Dolly: by Matt Mullenweg – 1.7.2
Hikari Category Permalink: by Hikari – 1.00.08
Image Widget: by The Events Calendar – 4.4.8
WPBakery Page Builder: by Michael M - WPBakery.com – 6.9.0
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.7
Links in Captions: by Katz Web Services
Inc. – 1.2

LiteSpeed Cache: by LiteSpeed Technologies – 5.3
Log cleaner for iThemes Security: by Michael Ott – 1.3.5
Login With Ajax: by Marcus Sykes – 4.1
Logout Redirect: by Arefly – 1.0.2
Mailgun: by Mailgun – 1.8.7
Obfuscate Email: by Scott Reilly – 3.8.1
Passwordless Login: by Cozmoslabs
sareiodata – 1.1.2

Pods - Custom Content Types and Fields: by Pods Framework Team – 2.9.9
PublishPress Future: by PublishPress – 2.8.0
Post Tags and Categories for Pages: by curtismchale – 1.4.1
Post Type Switcher: by Triple J Software
Inc. – 3.2.1

Post Types Order: by Nsp Code – 1.9.9.2
QL Events: by kidunot89 – 0.0.1
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.38
Redirection: by John Godley – 5.3.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Relevanssi: by Mikko Saari – 4.18.2
Reveal IDs: by Oliver Schlöbe – 1.5.4
Revision Control: by Dion Hulse – 2.3.2
Rollbar: by Rollbar – 2.6.3
Shortcode in Menus: by Gagan Deep Singh – 3.5.1
Simple Tooltips: by Justin Saad – 2.1.3
TablePress: by Tobias Bäthge – 1.14
Tabsy for Visual Composer: by phpbits – 1.0
WP Tabsy: by phpbits – 1.4
Link/Obfuscate Telephone Numbers: by Grandadevans – 1.4.1
Templatera: by WPBakery – 2.0.5
Text Expander: by Alexander Zigelski – 0.3
The Events Calendar: by The Events Calendar – 6.0.5
Total Theme Core: by WPExplorer – 1.5.0
The Events Calendar Extension: Events Control: by Modern Tribe
Inc. – 1.3.0

The Events Calendar Extension: Events Happening Now: by Modern Tribe
Inc. – 1.0.0

The Events Calendar Extension: Open external links in a new tab.: by The Events Calendar – 1.0.1
The Events Calendar Extension: Don't Hide Recurring Instances on Month and Week View: by Modern Tribe
Inc. – 1.0.0

UpdraftCentral Dashboard: by David Anderson + Team Updraft – 0.8.22
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.22.23

UPME NoCaptcha reCaptcha: by Themefluent – 1.1
User Profiles Made Easy: by ThemeFluent – 2.3.09
User Switching: by John Blackbourn & contributors – 1.7.0
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.4.5
When Last Login: by Yoohoo Plugins – 1.2.1
Widget Importer & Exporter: by ChurchThemes.com – 1.6
Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.3
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.7
WooCommerce Colors: by WooThemes – 1.0.7
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Name Your Price: by Kathy Darling – 3.3.10
WooCommerce One Page Checkout: by Automattic – 1.9.8
WooCommerce Product Bundles: by WooCommerce – 6.17.3
WooCommerce Product Details Customiser: by jameskoster – 0.2.0
WooCommerce Smart Coupons: by StoreApps – 6.8.0
WooCommerce: by Automattic – 7.1.1
WooCommerce Donations Plugin: by Albdesign – 1.95
WooGraphQL Product Bundles: by Jacob Arriola – 0.0.4
WP Activity Log for WooCommerce: by WP White Security – 1.5.0
WP Block Admin: by Callum Macdonald – 0.2.3.0
Combined Query: by birgire – 1.2.2
Contact Form 7 Email Spam Blocker: by Hardik Kalathiya – 1.0.0
WP Crontrol: by John Blackbourn & crontributors – 1.15.0
WP First Letter Avatar: by Dev49.net – 2.2.8
WP Gatsby: by GatsbyJS
Jason Bahl
Tyler Barnes – 2.3.3

WPGraphQL CORS: by  – 2.0
WPGraphQL WooCommerce (WooGraphQL): by kidunot89 – 0.11.2
WP GraphQL: by WPGraphQL – 1.13.7
WP Menu Cart Pro: by WP Overnight – 3.9.0
WP OAuth Server - Pro: by WP OAuth Server – 4.2.3
REST API Log: by Pete Nelson – 1.6.9
WP Activity Log: by WP White Security – 4.4.3
WP Session Manager: by Eric Mann – 4.2.0
WPFront User Role Editor: by Syam Mohan – 3.2.1.11184

### Inactive Plugins (12) ###

Admin Columns Pro - Events Calendar: by AdminColumns.com – 1.7.1
Admin Columns Pro - WooCommerce: by AdminColumns.com – 3.7.3
Better Search Replace: by Delicious Brains – 1.4.1
Bulk Delete: by Sudar – 6.0.2
Git Updater: by Andy Fragen – 11.1.9
Media Deduper: by Cornershop Creative – 1.5.5
No Clear Password in Email: by Paul Newman (modified by ....) – 1.00
Query Monitor: by John Blackbourn – 3.10.1
The Events Calendar: Virtual Events: by The Events Calendar – 1.9.0
WooCommerce Dynamic Pricing: by Element Stark – 3.1.29
WP Bulk Delete: by Xylus Themes – 1.2.3
WPGraphQL JWT Authentication: by WPGraphQL
Jason Bahl – 0.4.1

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #218 - /shop/
Cart: #219 - /cart/
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: ❌ Page does not contain the [woocommerce_my_account] shortcode.
Terms and conditions: #11138 - /store-terms-conditions/

### Theme ###

Name: THEME
Version: 1.3.6
Author URL: ...
Child Theme: ✔
Parent Theme Name: Total
Parent Theme Version: 5.6.0
Parent Theme Author URL: https://www.wpexplorer.com/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: THEME/woocommerce/archive-product.php
THEME/woocommerce/checkout/form-checkout.php
THEME/woocommerce/loop/loop-start.php
THEME/woocommerce/loop/orderby.php
THEME/woocommerce/loop/pagination.php
THEME/woocommerce/myaccount/form-edit-account.php
THEME/woocommerce/myaccount/my-orders.php
THEME/woocommerce/single-product/add-to-cart/variable.php
THEME/woocommerce/single-product/meta.php
THEME/woocommerce/single-product/rating.php
THEME/woocommerce/single-product/tabs/tabs.php
THEME/woocommerce/single-product/title.php

### Product Bundles ###

Database Version: 6.17.3
Loopback Test: ❌ Loopback test failed.
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-11 03:49:58 -08:00
Options: ✔
Notes: 23
Onboarding: completed

### Action Scheduler ###

Complete: 1,190
Oldest: 2022-11-09 17:07:06 -0800
Newest: 2022-12-10 16:03:06 -0800

Failed: 12
Oldest: 2021-06-20 12:27:00 -0700
Newest: 2022-12-10 15:59:05 -0800

Pending: 2
Oldest: 2022-12-10 20:12:04 -0800
Newest: 2022-12-17 01:35:08 -0800

### Name Your Price ###

Version: 
Database version: 
Template overrides: –

### Smart Coupons related settings ###

Number of coupons to show: 5
Number of characters in auto-generated coupon code: 
Valid order status for auto-generating coupon: processing
completed

Include tax in the amount of the generated gift card: no
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: yes
Printing coupons: no
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: yes
Allow schedule sending of coupons?: yes
Combine emails: yes
Auto generated coupon email: yes
Combined auto generated coupons email: yes
Acknowledgement email: yes
Enable taxes: no
Prices entered with tax: no
Rounding: no
Display prices in the shop: excl
Display prices during cart and checkout: excl
Display tax totals: itemized
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: yes
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2022-12-10 16:48:19 -08:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by therealgilles** [comment]
Looking at the code, I really don't see how this occurs but I have the stack trace in the `debug.log`, so it is still somehow happening. I wonder if this happened as wp-cron was running exactly as I was saving the corresponding product.

**Comment by therealgilles** [comment]
I dug a little deeper. This fatal error happens when saving a variable product as wp-cron is running.
I think a possible fix would be like this:
```PHP
    // wp-content/plugins/woocommerce/src/Internal/DownloadPermissionsAdjuster.php
    $children_with_downloads = array();
    foreach ( $children_ids as $child_id ) {
      $child = wc_get_product( $child_id );
      // ADD THIS IF CONDITION
      if ( ! $child ) {
        continue;
      } 
      $children_with_downloads[ $child_id ] = $this->get_download_files_and_permissions( $child );
    }
```

**Comment by barryhughes** [comment]
Thanks for reporting: we'll take a look at the PR shortly :+1:

**Comment by barryhughes** [comment]
Thanks! Closing, as we will aim to address via https://github.com/woocommerce/woocommerce/issues/36325 (for anyone who might be interested, we'd also be happy to accept a PR for this).

**Comment by barryhughes** [comment]
Reopening, we've changed tactics and will address these individually as they arise.

**Comment by flakas** [comment]
Hi @therealgilles - thanks for reporting this, and for the detail you gave.

I know this has been open for a very long time, and I appreciate your patience. We're currently going through some older WooCommerce issues, identifying what still needs fixing, and tidying up what's already fixed or out of scope.

It looks like this has already been fixed, or it's no longer happening on trunk.

I'm going to close this one. If you're still facing this issue on a current version, please reply with steps to reproduce and we'll happily take another look.
