### ISSUE TITLE
`WC_Plugin_Updates` class unavailable on WooCommerce > Status page

### ISSUE THREAD

**Issue by bernattorras** [woothemes/woocommerce#37417]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In some scenarios, when you try to open the WooCommerce > Status page, the following critical PHP error appears:

```
PHP Fatal error:  Uncaught Error: Class 'WC_Plugin_Updates' not found in /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-status-report.php:31
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php(30): include_once()
#1 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-status.php(43): WC_Admin_Status::status_report()
#2 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php(23): include_once('/Users/bernatto...')
#3 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(305): WC_Admin_Status::output()
#4 /Users/bernattorras/Local Sites/renewbreakupbootcamp/app/public/wp-includes/class-wp-hook.php(308): WC_Admin in /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-status-report.php on line 31
```

This is happening because the WC_Plugin_Updates class [is instantiated when rendering the Status page](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/views/html-admin-page-status-report.php#L27) without being the class included or available at this moment.

This issue was reported [here](https://github.com/a8cteam51/renew-breakup-bootcamp/issues/316). I can't always replicate this error. The minimal scenario that I've found it happening is when using WooCommerce in combination with WooCommerce Subscriptions and [CoBlocks](https://wordpress.org/plugins/coblocks/). 

Even if the issue could be coming from a conflict between other plugins, I think that it would be safe to add a conditional like this before instantiating the `WC_Plugin_Updates` class:

```
if ( ! class_exists( 'WC_Plugin_Updates' ) ) {
	include_once dirname( WC_PLUGIN_FILE ) . '/includes/admin/plugin-updates/class-wc-plugin-updates.php';
}
```

Checking the code, I see that this is a usual thing to do when using the WC_Plugin_Updates class in WooCommerce ([here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-core-functions.php#L2280) for example).

### Expected behavior

The WooCommerce > Status page should be rendered without any errors.

If the `WC_Plugin_Updates` class isn't accessible for some reason (maybe a plugin conflict), it should be included to make it available again. 

### Actual behavior

For some reason, it seems that sometimes, the `WC_Plugin_Updates` class isn't available when rendering the WooCommerce > Status page, and when this happens, an error is thrown. 

### Steps to reproduce

0. I've only been able to replicate this issue when using WooCommerce + WooCommerce Subscriptions + [CoBlocks](https://wordpress.org/plugins/coblocks/). 
1. Go to WooCommerce > Status
2. Click on the Tools tab
3. Click back to the Status tab 

If you don't get the fatal error, try to repeat steps 2 and 3 a few more times. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://renewbreakupbootcamp.local
Site address (URL): https://renewbreakupbootcamp.local
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wp_
Total Database Size: 352.60MB
Database Data Size: 338.02MB
Database Index Size: 14.58MB
wp_woocommerce_sessions: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 3.52MB + Index: 0.05MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.52MB + Index: 1.69MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 1.91MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.48MB + Index: 0.77MB + Engine InnoDB
wp_convertkit_user_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_followup_customers: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.34MB + Index: 0.13MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 254.83MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 17.52MB + Index: 5.73MB + Engine InnoDB
wp_posts: Data: 49.19MB + Index: 1.05MB + Engine InnoDB
wp_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sensei_pro_groups_courses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sensei_pro_groups_students: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.38MB + Index: 0.11MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_activecampaign: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yikes_easy_mc_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.09MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 3
acf-field-group: 1
asp-products: 9
attachment: 745
aw_workflow: 9
boxzilla-box: 2
course: 1
custom_css: 2
event_ticket: 36
feedback: 1521
follow_up_email: 1
jetpack_migration: 2
jetpack-testimonial: 3
jp_img_sitemap: 6
jp_sitemap: 6
jp_sitemap_master: 6
jp_vid_sitemap: 6
lesson: 57
letter: 35
mts_notification_bar: 1
nav_menu_item: 42
page: 56
popup: 1
popup_theme: 8
post: 34
product: 24
product_variation: 75
pys_event: 1
quiz: 8
rbbc_letters: 5
rbbc_press: 27
rbbc_testimonials: 18
redirect_rule: 7
revision: 2336
shop_coupon: 20
shop_order_refund: 20
stripe_order: 94
wp_block: 5
wp_global_styles: 2
wpcode: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

CoBlocks: by GoDaddy – 2.25.5
WooCommerce Subscriptions: by WooCommerce – 5.0.0
WooCommerce: by Automattic – 7.5.1

### Inactive Plugins (22) ###

AceIDE: by AceIDE – 2.6.2
ActiveCampaign: by ActiveCampaign – 8.1.10
ActiveCampaign for WooCommerce: by ActiveCampaign – 2.1.0
Add Widget After Content: by Arelthia Phillips – 2.4.5
Advanced Custom Fields: by WP Engine – 6.0.7
Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.0
Afterpay Gateway for WooCommerce: by Afterpay – 3.5.3
AutomateWoo: by WooCommerce – 5.6.10
Boxzilla: by ibericode – 3.2.26
Canonical SEO WordPress Plugin: by Harsh Agrawal – 3.0
Carousel Slider Block for Gutenberg: by  – 1.0.8
ConvertKit: by ConvertKit – 2.1.1
Creative Mail by Newfold Digital: by Newfold Digital – 1.6.7
Duplicate Page: by mndpsingh287 – 4.5.1
Follow-Up Emails: by WooCommerce – 4.9.37
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.19
WooCommerce Box Office: by WooCommerce – 1.1.50
WooCommerce One Page Checkout: by Automattic – 2.2.0
WooCommerce Product Bundles: by WooCommerce – 6.18.2 (update to version 6.18.3 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce Stripe Gateway: by WooCommerce – 7.2.0
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.5

### Must Use Plugins (1) ###

mu-autoloader.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: #4850 - /cart/
Checkout: #4851 - /checkout/
My account: #4852 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Renew Breakup Bootcamp V2
Version: 2.0.0
Author URL: https://wpspecialprojects.wordpress.com
Child Theme: ✔
Parent Theme Name: Twenty Twenty-One
Parent Theme Version: 1.4 – 1.7 is available
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: renewbreakup-v2/woocommerce/archive-product.php
renewbreakup-v2/woocommerce/cart/cart.php version 3.8.0 is out of date. The core version is 7.4.0
renewbreakup-v2/woocommerce/checkout/form-coupon.php version 3.4.4 is out of date. The core version is 7.0.1
renewbreakup-v2/woocommerce/myaccount/dashboard.php
renewbreakup-v2/woocommerce/single-product/add-to-cart/simple.php version 3.4.0 is out of date. The core version is 7.0.1
renewbreakup-v2/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
Subscriptions Live URL: https://renewbreakupbootcamp.com
Subscriptions-core Library Version: 5.5.0
Subscriptions Template Theme Overrides: renewbreakup-v2/woocommerce/emails/subscription-info.php
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ Thanks for your payment order. It’s on-hold until we confirm that payment has been received. In the meantime
here’s a reminder of your order:

### Store Setup ###

Country / State: Canada — British Columbia

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-24 18:26:20 +00:00
Options: ✔
Notes: 38
Onboarding: completed

### Action Scheduler ###

Canceled: 5
Oldest: 2023-02-26 14:03:56 +0000
Newest: 2023-03-06 11:12:27 +0000

Complete: 6,274
Oldest: 2023-02-21 12:33:03 +0000
Newest: 2023-03-24 09:32:04 +0000

Failed: 13
Oldest: 2022-04-29 21:36:17 +0000
Newest: 2023-01-17 15:46:20 +0000

Pending: 3
Oldest: 2023-03-25 06:00:00 +0000
Newest: 2023-03-25 08:29:16 +0000

### Status report information ###

Generated at: 2023-03-24 10:00:33 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by shanevbg** [comment]
I had this problem and added
```
if ( ! class_exists( 'WC_Plugin_Updates' ) ) {
	include_once dirname( WC_PLUGIN_FILE ) . '/includes/admin/plugin-updates/class-wc-plugin-updates.php';
}
```
before line 25 in html-admin-page-status-report.php
and it worked perfectly.

WooCommerce version:   7.9.0
WordPress version: 6.2.2
