### ISSUE TITLE
CRITICAL Uncaught Error: Attempt to assign property "there_are_now_products" on array in StoredStateSetupForProducts.php:125

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#37637]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

A customer contacted Name Your Price support to report a fatal error when saving/updating a product in the admin. Based on the error message and their report that they can repro it with all plugins disabled, I believe this to be a core WC error that is not related to Name Your Price. I haven't been able to reproduce the error myself though. Here is there report:

>After the last update, I can no longer add new products or edit existing products.
>
>This is the product I am trying to edit but when I click Update I receive this error, "There has been a critical error on this website. >Please check your site admin email inbox for instructions."
>
>I have disabled all plug-ins except WooCommerce and Stripe and still receive the error.
>I have tried changing my theme to the default wordpress theme and still receive the error.
>I have cleared all the caches available.
>I have updated the database to the most recent version.
>I have verified all base tables are present. 

### Expected behavior

Save products without fatal error

### Actual behavior

Here's the logged error:

```
2023-04-09T16:48:07+00:00 CRITICAL Uncaught Error: Attempt to assign property "there_are_now_products" on array in /var/web/site/public_html/wp-content/plugins/woocommerce/src/Admin/RemoteInboxNotifications/StoredStateSetupForProducts.php:125
Stack trace:
#0 /var/web/site/public_html/wp-content/plugins/woocommerce/src/Admin/RemoteInboxNotifications/StoredStateSetupForProducts.php(111): AutomatticWooCommerceAdminRemoteInboxNotificationsStoredStateSetupForProducts::update_stored_state_and_possibly_run_remote_notifications()
#1 /var/web/site/public_html/wp-includes/class-wp-hook.php(308): AutomatticWooCommerceAdminRemoteInboxNotificationsStoredStateSetupForProducts::run_on_transition_post_status('publish', 'publish', Object(WP_Post))
#2 /var/web/site/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#3 /var/web/site/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /var/web/site/public_html/wp-includes/post.php(5345): do_action('transition_post...', 'publish', 'publish', Object(WP_Post))
#5 /var/web/site/public_html/wp-includes/post.php(4605): wp_transition_post_status('publish', 'publish', Object(WP_Post))
#6 /var/web/site/public_html/wp-includes/post.php(4817): wp_insert_post(Array, false, true)
#7 /var/web/site/public_html/wp-admin/includes/post.php(439): wp_update_post(Array)
#8 /var/web/site/public_html/wp-admin/post.php(227): edit_post()
#9 {main}
thrown in /var/web/site/public_html/wp-content/plugins/woocommerce/src/Admin/RemoteInboxNotifications/StoredStateSetupForProducts.php on line 125 
```

### Steps to reproduce

A bit of a guess on my part, but it sounds like it happens when updating a product. I haven't seen that locally though.

### WordPress Environment ###

WordPress address (URL): https://www.XXXXXX.com/
Site address (URL): https://www.XXXXXX.com/
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.22.1
PHP Version: 8.0.28
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 10.3.38-MariaDB-1:10.3.38+maria~ubu1804
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: gvf_
Total Database Size: 40.61MB
Database Data Size: 34.81MB
Database Index Size: 5.80MB
gvf_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
gvf_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
gvf_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gvf_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gvf_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
gvf_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
gvf_aws_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gvf_aws_index: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
gvf_b_testimo_slide: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gvf_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
gvf_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
gvf_defender_audit_log: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
gvf_defender_email_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_defender_lockout: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
gvf_defender_lockout_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gvf_defender_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gvf_defender_scan_item: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_et_social_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gvf_frm_fields: Data: 0.27MB + Index: 0.03MB + Engine InnoDB
gvf_frm_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_frm_items: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
gvf_frm_item_metas: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
gvf_hustle_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_hustle_entries_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gvf_hustle_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_hustle_modules_meta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
gvf_hustle_tracking: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
gvf_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_opanda_leads: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_opanda_leads_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_opanda_stats_v2: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_options: Data: 3.05MB + Index: 0.13MB + Engine InnoDB
gvf_postmeta: Data: 9.39MB + Index: 1.64MB + Engine InnoDB
gvf_posts: Data: 16.02MB + Index: 0.13MB + Engine InnoDB
gvf_randomize: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gvf_redirection_404: Data: 1.02MB + Index: 0.38MB + Engine InnoDB
gvf_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
gvf_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gvf_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_sbi_feed_caches: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
gvf_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_sbi_instagram_posts: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
gvf_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_search_filter_cache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gvf_search_filter_term_results: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gvf_smartcrawl_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gvf_smush_dir_images: Data: 0.33MB + Index: 0.19MB + Engine InnoDB
gvf_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
gvf_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gvf_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
gvf_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
gvf_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gvf_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gvf_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
gvf_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gvf_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
gvf_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gvf_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gvf_yoast_indexable: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
gvf_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gvf_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gvf_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gvf_yoast_seo_links: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_y1_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_y1_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_y1_defender_audit_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_y1_defender_email_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_y1_defender_lockout: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_y1_defender_lockout_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_y1_defender_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_y1_defender_scan_item: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_y1_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_y1_options: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_y1_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_y1_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_y1_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_y1_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_y1_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_y1_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_y1_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_y1_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_y1_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 277
custom-css-js: 5
custom_css: 2
dflip: 1
divi_bars: 1
divi_overlay: 22
epta: 1
et_body_layout: 3
et_footer_layout: 2
et_header_layout: 2
et_pb_layout: 27
et_template: 14
et_theme_builder: 1
frm_form_actions: 16
frm_styles: 2
nav_menu_item: 20
oembed_cache: 24
opanda-item: 2
page: 42
post: 31
product: 17
product_variation: 9
resource: 11
revision: 33
sa_slider: 3
search-filter-widget: 1
shop_coupon: 3
shop_order: 20
shop_order_refund: 1
tribe_events: 8
tribe_organizer: 2
tribe_rsvp_attendees: 2
tribe_rsvp_tickets: 3
tribe_venue: 4
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Advanced Custom Fields: by WP Engine – 6.1.3
Akismet Anti-Spam: by Automattic – 5.1
Simple Custom CSS and JS: by SilkyPress.com – 3.43
Custom Post Type UI: by WebDevStudios – 1.13.5
Divi Overlays: by Divi Life — Tim Strifler – 2.9.7.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Easy Testimonial Slider: by I Thirteen Web Solution – 1.0.16
Font Awesome: by Font Awesome – 4.3.2
Formidable Google Sheets: by Strategy11 – 1.0.1
Formidable Forms Pro: by Strategy11 – 6.2
Formidable Quiz Maker: by Strategy11 – 3.1
Formidable Zapier: by Strategy11 – 2.02
Formidable Forms: by Strategy11 Form Builder Team – 6.2.2
Hustle Pro: by WPMU DEV – 4.6.6
Smash Balloon Instagram Feed: by Smash Balloon – 6.1.3
Monarch Plugin: by Elegant Themes – 1.4.14
Redirection: by John Godley – 5.3.10
Search & Filter Pro: by Code Amp – 2.5.4
Slide Anything - Responsive Content / HTML Slider and Carousel: by – 2.4.9
SUMO Payment Plans: by Fantastic Plugins – 10.1
WooCommerce Checkout Fields & Fees: by Lagudi Domenico – 9.9
WooCommerce Stripe Gateway: by WooCommerce – 7.2.0
WooCommerce Name Your Price: by Kathy Darling – 3.5.1
WooCommerce: by Automattic – 7.5.1
Smush Pro: by WPMU DEV – 3.12.6
WPMU DEV Dashboard: by WPMU DEV – 4.11.18

### Inactive Plugins (17) ###

3D FlipBook : Dflip Lite: by DearHive – 1.7.35
Advanced Woo Search: by ILLID – 2.76
Analytify - Email Notifications: by WPBrigade – 2.0.3
Analytify - Google Analytics Dashboard: by Analytify – 4.3.1
Analytify - Google Analytics Dashboard Widget: by Analytify – 2.0.6
Analytify Pro: by WPBrigade – 4.1.6
AutomatePlug - Mautic for WordPress: by Brainstorm Force – 1.0.8
Event Tickets: by The Events Calendar – 5.5.10
Event Tickets Extension: Organizer Notifications: by The Events Calendar – 1.0.2
Event Tickets Extension: Ticket Email Settings: by The Events Calendar – 1.0.3
Hummingbird Pro: by WPMU DEV – 3.4.5
Randomize: by Javik – 1.4.3
SmartCrawl Pro: by WPMU DEV – 3.5.1
The Events Calendar: by The Events Calendar – 6.0.11
The Events Calendar Shortcode & Block: by Event Calendar Newsletter – 2.5.6
WP Mautic: by Mautic community – 2.4.2
Yoast SEO: by Team Yoast – 20.4

### Dropin Plugins (1) ###

object-cache.php: Hosting Object Cache

### Must Use Plugins (3) ###

ET Support Center :: Must-Use Plugins Autoloader: by Elegant Themes –
Hosting: by – 0.1
[Hustle] - Fix Mautic integration not showing the Segments list: by Anderson Salas @ WPMUDEV –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #1874 - /shop/
Cart: #1875 - /cart/
Checkout: #1876 - /checkout/
My account: #1877 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Gv Freeman
Version: 4.7.4.1607302192
Author URL: https://www.gvfreeman.com/
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.20.4
Parent Theme Author URL: http://www.elegantthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Name Your Price ###

Version:
Database version:
Template overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-09 18:23:36 +00:00
Options: ✔
Notes: 74
Onboarding: completed

### Action Scheduler ###

Complete: 80
Oldest: 2023-03-10 00:02:27 +0000
Newest: 2023-04-09 16:53:33 +0000

Failed: 7
Oldest: 2023-02-20 22:20:42 +0000
Newest: 2023-04-09 16:21:08 +0000

Pending: 1
Oldest: 2023-04-10 00:19:06 +0000
Newest: 2023-04-10 00:19:06 +0000

### Status report information ###

Generated at: 2023-04-09 16:54:15 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by felipevelzani** [comment]
Hi @helgatheviking, thank you for the report! 

While testing, did you also remove the mu-plugins and drop-in plugins?

For reference, I found some similar cases, and it looks like it is something specific on the WPMU DEV Hosting environment conflicting with WooCommerce when using PHP 8.x.

* https://wordpress.org/support/topic/error-505-when-update-any-product/
* https://wordpress.org/support/topic/fatal-error-when-updating-product-info/
* 6196426-zen

**Comment by wpmudev-nebu** [comment]
Hey @foosantos,

Hope you are keeping well :)

I tested this on the WPMU DEV Hosting environment with PHP versions 8.0, 8.1, and 8.2 and did not encounter the same issue.

We have received a few reports of this issue in our support forum and have investigated it closely. Based on our troubleshooting, it seems to be a bug on the WooCommerce side.

If we look at file line 125 of _/woocommerce-packages-woocommerce-admin-src-remoteinboxnotifications-storedstatesetupforproducts.html_, this is trying to add “True” as an object, in PHP the object index uses object->index. So we went ahead and added the print_r($stored_state) just before that line to understand what type of data the stored_state is and it is an array which brings the error “Attempt to assign property “there_are_now_products” on array” since array you would access array[‘index’].

If we go ahead with the troubleshooting and check the get_stored_state() Woocommerce itself defines the return type as an [object](https://woocommerce.github.io/code-reference/classes/Automattic-WooCommerce-Admin-RemoteInboxNotifications-RemoteInboxNotificationsEngine.html#methods).

So the error is _something in the middle of the process is converting this into an Array_ and causes the issue. 

Based on our investigation, the issue does not seem to be related to the hosting environment as it is not being replicated on other websites with WooCommerce installations. 

We appreciate your concerns and willingness to investigate this matter thoroughly. While we cannot say for certain that this is an issue at the hosting end, we believe that it's important to explore all possibilities. If you can provide us with more details on how this issue could be related to the hosting environment, we can take the necessary measures to replicate the issue and investigate it further.
 
Best Regards,
Nebu John
FLS - WPMU DEV

**Comment by felipevelzani** [comment]
Thank you for checking that, @wpmudev-nebu!

That makes sense. It's not clear to me yet if it is indeed on WPMU DEV Hosting, but the odd thing is that I checked it on more than five different topics and internal tickets and all of them are hosted on WPMU DEV. I don't expect it to be a coincidence, so I'm wondering if it is one of the Hosting settings triggering this issue.

We are using the following temporary solution while supporting WooCommerce: [delete-stored-state-option.zip](https://github.com/woocommerce/woocommerce/files/11289239/delete-stored-state-option.zip)

PS: Our development team still needs to review this issue as well, so only I'm providing some context based on what we identified on support.

**Comment by xue28** [comment]
6277860-zen

**Comment by neway** [comment]
Hit the same issue today.  Ubuntu 22 LTS - PHP 8.1

2023-05-25T13:10:45+00:00 CRITICAL Uncaught Error: Attempt to assign property "there_are_now_products" on array in /wp-content/plugins/woocommerce/src/Admin/RemoteInboxNotifications/StoredStateSetupForProducts.php:125
Stack trace:

Using the delete_option fix found in the zip file as a temp fix - look forward to the function getting fixed!

**Comment by wpmudev-nebu** [comment]
Hey @neway,

Sorry to know that you are experiencing this issue. 

I understand your situation. Could you please let us know if the website is hosted with WPMU DEV hosting? If it is, I kindly request you [open a ticket with us](https://wpmudev.com/docs/getting-started/getting-support/#support-tickets) so that our team can investigate the issue further and provide the necessary assistance. 

Kind Regards,
Nebu John

**Comment by neway** [comment]
Thanks for checking in.  Nope - we're running our own private cloud on
Linode.

Wayne Foster

Director
Neway Technology Ltd

Tel:       +44 (0)1782 479677
Skype:  wayne.neway
Email:   ***@***.*** (Google Hangouts)
Web:     http://www.newaytech.co.uk

Registered office: Ravenscliffe, First Avenue, Porthill,
Newcastle-under-Lyme, ST5 8QX
Registered in England. Reg. No. 07208528
( Find us <http://goo.gl/tW08AF> )

This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of Neway Technology.
If you are not the intended recipient of this email, you must neither take
any action based upon its contents, nor copy or show it to anyone.
The company scans for but accepts no responsibility for viruses and it is
the addressee's responsibility to scan attachments.
Please contact the sender if you believe you have received this email in
error.

**Comment by ethicaladitya** [comment]
Hi @neway, 

Thanks for confirming. 

We could narrow down the issue and confirm that this isn't a WPMUDEV Hosting issue, following screenshot shows how it’s stored in DB. It’s serialised.

<img width="910" alt="Screenshot 2023-05-26 at 6 29 57 PM" src="https://github.com/woocommerce/woocommerce/assets/11734697/5a5351fd-d12d-4c43-a744-6e02ffd8d49c">

In Woocommerce, it gets the value with :
`$stored_state = get_option( self::STORED_STATE_OPTION_NAME ); `
in file https://plugins.trac.wordpress.org/browser/woocommerce/trunk/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php

The above variable stores an array but in file https://plugins.trac.wordpress.org/browser/woocommerce/trunk/src/Admin/RemoteInboxNotifications/StoredStateSetupForProducts.php#L125, it tries to use it as an object.

With the above said, it's probably something specific to the sites reported and Woocommerce, could be some common plugin causing this, but surely is not a hosting issue. :) 

Best Regards,
Aditya Shah

**Comment by timfroling** [comment]
From fulcare 5 months ago in https://wordpress.org/support/topic/cant-update-products-4/

A workaround to prevent this is to replace the /woocommerce/src/Admin/RemoteInboxNotifications/StoredStateSetupForProducts.php line 125 from:

$stored_state = RemoteInboxNotificationsEngine::get_stored_state();
to
$stored_state = (object) RemoteInboxNotificationsEngine::get_stored_state();

This works for me too. I'm using Plesk with Litespeed server.

**Comment by stevenidi** [comment]
Same problem here. Thanks for the temporary workaround. Hope Woocommerce fixes it.

**Comment by adrianduffell** [comment]
Thanks for the reports, folks.

It looks like there could be more defensive practices in the `StoredStateSetupForProducts` class to validate the option date. However I'd advocate to take a step further and remove the [stored state rules](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/RemoteSpecs/RuleProcessors/README.md#stored-state) entirely. These rules seem like an additional layer that is providing limited value but can create a surface area for bugs like this. For simplicity I think we should just encourage folks to use [product_count](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/RemoteSpecs/RuleProcessors/README.md#product-count) rule.

**Comment by ollybowman** [comment]
I've suddenly started having the same issue. Has it been fixed yet?

**Comment by psealock** [comment]
>However I'd advocate to take a step further and remove the [stored state rules](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/RemoteSpecs/RuleProcessors/README.md#stored-state) entirely.

In https://github.com/woocommerce/woocommerce/pull/56467 I add appropriate defensive practices, which are sufficient to avoid fatal errors. 

I'm not sure we've ever deprecated a rule processor before, but I think the best way to do that is in the remote-specs-validation package because creating a deprecation warning on the WooCommerce installation is creating noise where its not relevant.

**Comment by psealock** [comment]
On second thought, in https://github.com/woocommerce/woocommerce/pull/56467 I decided not to deprecate or remove `stored_state` processors. It seems heavy handed to remove functionality, although I do admit its usefulness is somewhat limited. The purpose is for making calculations that may not be easily computable given the available operations. What do you think @adrianduffell ?

**Comment by adrianduffell** [comment]
> On second thought, in [#56467](https://github.com/woocommerce/woocommerce/pull/56467) I decided not to deprecate or remove `stored_state` processors. It seems heavy handed to remove functionality, although I do admit its usefulness is somewhat limited. The purpose is for making calculations that may not be easily computable given the available operations. What do you think [@adrianduffell](https://github.com/adrianduffell) ?

That sounds fair, thanks @psealock!
