### ISSUE TITLE
Bulk Update on Sale Prices causes Fatal Error when Regular Price is blank

### ISSUE THREAD

**Issue by lynnjat7** [woothemes/woocommerce#37681]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When doing a bulk edit of products to set a sale price (as a percentage of the regular price), if you have a product in the list that has a blank price, this throws a fatal error.

This stops the bulk update, leaving the product list in a half-updated state.

### Expected behavior

While a blank product price is not standard, it should not throw a fatal error; in this case the product should be skipped for the sale price update and the remainder of the product list should be processed as usual.

Additional and possibly related:
If I test this by choosing "decrease existing sale price" and enter a percentage, I do not see the fatal error, HOWEVER, if the existing sale price is/was blank, it sets the sale price to $0. Probably also not what we want --> if the sale price is blank in this case, it should remain blank I think.

### Actual behavior

Critical error.

Stack trace:
```
Error Details
=============
An error of type E_ERROR was caused in line 990 of the file /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-post-types.php. Error message: Uncaught TypeError: Unsupported operand types: string * float in /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-post-types.php:990
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-post-types.php(554): WC_Admin_Post_Types->set_new_price(Object(WC_Product_Simple), 'sale')
#1 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-post-types.php(350): WC_Admin_Post_Types->bulk_edit_save(747, Object(WC_Product_Simple))
#2 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): WC_Admin_Post_Types->bulk_and_quick_edit_save_post(747, Object(WP_Post))
#3 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /srv/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-post-types.php(314): do_action('woocommerce_pro...', 747, Object(WP_Post))
#6 /wordpress/core/6.2/wp-includes/class-wp-hook.php(310): WC_Admin_Post_Types->bulk_and_quick_edit_hook(747, Object(WP_Post))
#7 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#8 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /wordpress/core/6.2/wp-includes/post.php(4715): do_action('save_post', 747, Object(WP_Post), true)
#10 /wordpress/core/6.2/wp-includes/post.php(4817): wp_insert_post(Array, false, true)
#11 /wordpress/core/6.2/wp-admin/includes/post.php(667): wp_update_post(Array)
#12 /wordpress/core/6.2/wp-admin/edit.php(194): bulk_edit_posts(Array)
#13 {main}
 thrown
```

### Steps to reproduce

1. Create a few simple products on the back end.
2. Make one product in the middle of the list published but with a blank price.
3. When viewing the main Products list under Products, check off products to edit, including the one with the blank price.
4. Click on Bulk Actions > Edit:

![EYYiPY.png](https://user-images.githubusercontent.com/109691691/231513092-bc8efc9a-5d3b-4b91-a19b-2ef43593821f.png)

5. Select to edit the Sale price as "regular price decreased by" and enter 10% as the discount:

![LQ39EB.png](https://user-images.githubusercontent.com/109691691/231513257-2f22f777-71c2-4e60-9261-909167d52d85.png)

6. Click Update to run the update and see the critical error:

![lkEjtu.png](https://user-images.githubusercontent.com/109691691/231513337-16e6597d-d165-44db-b8a8-4e008970fdfc.png)

### WordPress Environment

<details>

```
### WordPress Environment ###

WordPress address (URL): https://numberone.mystagingwebsite.com
Site address (URL): https://numberone.mystagingwebsite.com
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.28
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wp_
Total Database Size: 28.86MB
Database Data Size: 17.32MB
Database Index Size: 11.54MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 1.56MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.25MB + Index: 2.86MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.23MB + Index: 0.16MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 3.00MB + Engine InnoDB
wp_posts: Data: 0.25MB + Index: 0.13MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_flat_rate_boxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 124
aw_workflow: 6
enr_email_template: 1
global_product_addon: 2
mailpoet_page: 1
nav_menu_item: 6
page: 12
post: 2
product: 100
product_variation: 100
revision: 16
shop_coupon: 4
shop_order: 212
shop_subscription: 37
wcpf_item: 8
wcpf_project: 2
wc_membership_plan: 4
wc_user_membership: 7
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

Akismet Anti-Spam: by Automattic – 5.1
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.19
AutomateWoo: by WooCommerce – 5.6.10
Code Snippets: by Code Snippets Pro – 3.3.0
Debug Bar: by wordpressdotorg – 1.1.4
Enhancer for WooCommerce Subscriptions: by FantasticPlugins – 3.7.0
Facebook for WooCommerce: by Facebook – 3.0.16
Jetpack: by Automattic – 12.1-a.5
WooCommerce All Products For Subscriptions: by WooCommerce – 4.0.5
WooCommerce Composite Products: by WooCommerce – 8.7.4 (update to version 8.7.5 is available)
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.4.1
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.11.0
WooCommerce Distance Rate Shipping: by WooCommerce – 1.3.0
WooCommerce Memberships: by SkyVerge – 1.24.0
WooCommerce Payments: by Automattic – 5.6.2 (update to version 5.7.0 is available)
WooCommerce Product Add-ons: by WooCommerce – 6.1.2 (update to version 6.2.0 is available)
WooCommerce Product Bundles: by WooCommerce – 6.18.3 (update to version 6.18.4 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.57
Product Filters for WooCommerce: by WooCommerce – 1.4.3 (update to version 1.4.4 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce Flat Rate Box Shipping: by WooCommerce – 2.2.0
WooCommerce UPS Shipping: by WooCommerce – 3.4.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.2 (update to version 4.3.3 is available)
WooCommerce Subscriptions: by WooCommerce – 5.0.0 (update to version 5.0.1 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.0 (update to version 3.1.1 is available)
WooCommerce: by Automattic – 7.5.1
Yoast SEO: by Team Yoast – 20.3
WP Mail Logging: by WP Mail Logging Team – 1.11.0

### Inactive Plugins (12) ###

Advanced Custom Fields: by WP Engine – 6.0.7
Advanced Product Fields for WooCommerce: by StudioWombat – 1.5.8
Custom Post Type UI: by WebDevStudios – 1.13.4
Extra Fees for WooCommerce: by FantasticPlugins – 4.2
Flexible Checkout Fields: by WP Desk – 3.5.4
Google Listings and Ads: by WooCommerce – 2.3.8
Loco Translate: by Tim Whitlock – 2.6.3
MailPoet: by MailPoet – 4.6.1
WooCommerce Force Sells: by WooCommerce – 1.1.31 (update to version 1.2.0 is available)
WooCommerce Name Your Price: by Kathy Darling – 3.3.10 (update to version 3.5.2 is available)
WooCommerce Quick View: by Themesquad – 1.7.0
WooCommerce Subscriptions Gifting: by WooCommerce – 2.5.1 (update to version 2.6.0 is available)

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 4
Free Membership:: Members: 2Access method: User account registrationAccess length: Unlimited Subscription: No
Basic membership:: Members: 0Access method: Product(s) purchaseAccess length: Specific length (60 days)Subscription: No
Fruit Basket Delivery:: Members: 2Access method: Product(s) purchaseAccess length: Unlimited Subscription: YesInstallment plan: No
VIP Membership:: Members: 3Access method: Product(s) purchaseAccess length: Specific length (6 months)Subscription: YesInstallment plan: No

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://numberone.mystagingwebsite.com
Subscriptions-core Library Version: 5.5.0
Subscription Statuses: wc-active: 22
wc-expired: 4
wc-pending-cancel: 1
wc-pending: 1
wc-on-hold: 4
wc-cancelled: 5

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — New York

### Subscriptions by Payment Gateway ###

Check payments: wc-on-hold: 1
WooCommerce Payments: wc-active: 19
wc-cancelled: 5
wc-expired: 4
wc-on-hold: 2
wc-pending-cancel: 1


### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Check payments: products
Cash on delivery: products

### Composite Products ###

Database Version: 8.7.4
Loopback Test: ✔
Template Overrides: –

### Product Bundles ###

Database Version: 6.18.3
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-12 19:51:29 -04:00
Options: ✔
Notes: 77
Onboarding: completed

### WooCommerce Payments ###

Version: 5.6.2
Connected to WPCOM: Yes
Blog ID: 210717503
Account ID: acct_1Ljq8PFtdYohmYFC

### All Products for WooCommerce Subscriptions ###

Template Overrides: –

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 1
Custom formats: 1
Next export: Not scheduled

### Action Scheduler ###

Canceled: 9
Oldest: 2023-03-20 09:53:41 -0400
Newest: 2023-04-11 15:04:28 -0400

Complete: 1,766
Oldest: 2023-03-12 12:12:14 -0400
Newest: 2023-04-12 11:42:40 -0400

Failed: 9
Oldest: 2022-10-18 12:07:43 -0400
Newest: 2023-03-24 13:56:31 -0400

Pending: 43
Oldest: 2023-04-12 12:12:17 -0400
Newest: 2024-05-21 23:00:00 -0400


### Status report information ###

Generated at: 2023-04-12 11:54:02 -04:00
```

</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lynnjat7** [comment]
6196648-zen

**Comment by akshaya-rane** [comment]
I would like to take this up.
