### ISSUE TITLE
Uncaught Error: Call to undefined function Automattic\WooCommerce\Admin\get_current_screen() in

### ISSUE THREAD

**Issue by kohyunkjun** [woothemes/woocommerce#37870]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Uncaught Error: Call to undefined function Automattic\WooCommerce\Admin\get_current_screen() in

 E_ERROR의 오류는 plugins/woocommerce/src/Admin/PageController.php 파일의 250 행에서 발생했습니다. 오류 메시지: Uncaught Error: Call to undefined function Automattic\WooCommerce\Admin\get_current_screen() in ~~ plugins/woocommerce/src/Admin/PageController.php:250
Stack trace:
#0 wp-content/plugins/woocommerce/src/Admin/PageController.php(121): Automattic\WooCommerce\Admin\PageController->get_current_screen_id()
#1 wp-content/plugins/woocommerce/src/Admin/PageController.php(227): Automattic\WooCommerce\Admin\PageController->determine_current_page()
#2 wp-content/plugins/woocommerce/src/Admin/PageController.php(369): Automattic\WooCommerce\Admin\PageController->get_current_page()
#3/wp-content/plugins/woocommerce/includes/react-admin/page-controller-functions.php(40): Automattic\WooCommerce\Admin\PageController->is_connected_page()
#4 wp-content/plugins/woocommerce/src/Admin/PageController.php(566): wc_admin_is_connected_page()
#5wp-content/plugins/woocommerce/src/Internal/Admin/Settings.php(228

### Expected behavior

under Footer area, these codes should not appear. 

### Actual behavior

Under Footer area, these codes appears . when I come into the  admin page, these codes appears , and when I succeed in login, admin page works well. 

### Steps to reproduce

![IMG_3004](https://user-images.githubusercontent.com/40458097/233236143-93297089-7a3b-4464-9edc-06e0bb5267e3.PNG)

### WordPress Environment

워드프레스 버전 6.2
활성 테마: twentyfourteen-child (버전 )
현재 플러그인: WooCommerce (버전 7.6.0)
PHP 버전 7.4.5p1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by khoipro** [comment]
I got same report from Recovery mode by email.

```
Uncaught Error: Call to undefined function Automattic\WooCommerce\Admin\get_current_screen() in /home/runcloud/webapps/xxx/wp-content/plugins/woocommerce/src/Admin/PageController.php:250 Stack trace: #0 /home/runcloud/webapps/xxx/wp-content/plugins/woocommerce/src/Admin/PageController.php(121): Automattic\WooCommerce\Admin\PageController->get_current_screen_id() #1 /home/runcloud/webapps/xxx/wp-content/plugins/woocommerce/src/Admin/PageController.php(227): Automattic\WooCommerce\Admin\PageController->determine_current_page() #2 /home/runcloud/webapps/xxx/wp-content/plugins/woocommerce/src/Admin/PageController.php(369): Automattic\WooCommerce\Admin\PageController->get_current_page() #3 /home/runcloud/webapps/xxx/wp-content/plugins/woocommerce/includes/react-admin/page-controller-functions.php(40): Automattic\WooCommerce\Admin\PageController->is_connected_page() #4 /home/runcloud/webapps/xxx/wp-content/plugins/woocommerce/src/Admin/PageController.php(566)
```

**Comment by ndr0824** [comment]
I am able to reproduce the error on the current released version of WooCommerce.

### Steps to reproduce

1. If you are logged into your website (such as https://www.example.com/), log out.
2. Open a new tab in a web browser.
3. Paste the URL https://www.example.com/wp-admin/post-new.php and press the Enter key.

### WordPress Environment

WordPress version 6.2.2
Active theme: Custom Theme (version 3.0)
Current plugin: WooCommerce (version 7.7.2)
PHP version 7.4.33

### Error Details

```
An error of type E_ERROR was caused in line 250 of the file /home/customer/www/example.com/public_html/wp-content/plugins/woocommerce/src/Admin/PageController.php. Error message: Uncaught Error: Call to undefined function Automattic\WooCommerce\Admin\get_current_screen() in /home/customer/www/example.com/public_html/wp-content/plugins/woocommerce/src/Admin/PageController.php:250
Stack trace:
#0 /home/customer/www/example.com/public_html/wp-content/plugins/woocommerce/src/Admin/PageController.php(121): Automattic\WooCommerce\Admin\PageController->get_current_screen_id()
#1 /home/customer/www/example.com/public_html/wp-content/plugins/woocommerce/src/Admin/PageController.php(227): Automattic\WooCommerce\Admin\PageController->determine_current_page()
#2 /home/customer/www/example.com/public_html/wp-content/plugins/woocommerce/src/Admin/PageController.php(369): Automattic\WooCommerce\Admin\PageController->get_current_page()
#3 /home/customer/www/example.com/public_html/wp-content/plugins/woocommerce/includes/react-admin/page-controller-functions.php(40): Automattic\WooCommerce\Admin\PageController->is_connected_page()
```

**Comment by pmcpinto** [comment]
Routing this to engineering for the next step: the report looks actionable enough for implementation or documentation work.

**Comment by samrat-biswas-git** [comment]
I've taken a look and this is still valid on trunk — marking it ready for the engineering team to pick up.

What I'm seeing: PageController::get_current_screen_id() (plugins/woocommerce/src/Admin/PageController.php:275) calls get_current_screen() unqualified inside the Automattic\WooCommerce\Admin namespace, with no function_exists() guard — only a null-result check afterward. connect-existing-pages.php reaches this via PageController::get_instance()->get_current_screen_id() (lines 60 and 110). When the screen API isn't loaded yet, PHP resolves the unqualified call to Automattic\WooCommerce\Admin\get_current_screen() and fatals — exactly the reported error. I found no open PR or landed fix that removes this risk.

Suggested fix: reproduce the failing lifecycle, then either function_exists()-guard / delay the call or fully-qualify it as \get_current_screen().
