### ISSUE TITLE
pnpm run build failing at current trunk

### ISSUE THREAD

**Issue by helgatheviking** [woothemes/woocommerce#38296]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

```
@woocommerce/components:turbo:build: cache miss, executing 6985fccda580978b
command (/home/helga/woocommerce/plugins/woocommerce/client/legacy) pnpm run turbo:build exited (1)

 Tasks:    2 successful, 20 total
Cached:    0 cached, 20 total
  Time:    6.775s 

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected behavior

build scripts finish compiling and the plugin has all assets

### Actual behavior

the WC plugin unusable with the following fatal error:

```
Fatal error: Uncaught Exception: Could not find asset registry for wp-admin-scripts in /user/woocommerce/plugins/woocommerce/src/Internal/Admin/WCAdminAssets.php:128 Stack trace: #0 /user/woocommerce/plugins/woocommerce/src/Internal/Admin/WCAdminAssets.php(412): Automattic\WooCommerce\Internal\Admin\WCAdminAssets::get_script_asset_filename('wp-admin-script...', 'variable-produc...') #1 /user/woocommerce/plugins/woocommerce/includes/admin/class-wc-admin-pointers.php(76): Automattic\WooCommerce\Internal\Admin\WCAdminAssets::register_script('wp-admin-script...', 'variable-produc...', true) #2 /user/woocommerce/plugins/woocommerce/includes/admin/class-wc-admin-pointers.php(41): WC_Admin_Pointers->create_variable_product_tutorial() #3 /app/wp-includes/class-wp-hook.php(308): WC_Admin_Pointers->setup_pointers_for_screen('post-new.php') #4 /app/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #5 /app/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #6 /app/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'post-new.php') #7 /app/wp-admin/edit-form-advanced.php(425): require_once('/app/wp-admin/a...') #8 /app/wp-admin/post-new.php(75): require('/app/wp-admin/e...') #9 {main} thrown in /user/woocommerce/plugins/woocommerce/src/Internal/Admin/WCAdminAssets.php on line 128 
```

### Steps to reproduce

pull latest trunk
delete `node_modules` and pnpm lock file
run `pnpm install` and then `pnpm run build`

### WordPress Environment

pnpm v8.5.1
PHP 8.1.7 (in command line)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment]
I can reproduce. The legacy assets are failing due to modern JS not compiling with Uglify.

Considering this code has been untouched for some time, I'd say an update has caused this and probably requires a configuration update.

**Comment by evokelektrique** [comment]
Having the same issue, (`PHP 8.1.3 (cli)` & `pnpm 8.5.1`)
```command (/home/evoke/git/woocommerce/plugins/woocommerce-admin) pnpm run turbo:build exited (1)

 Tasks:    24 successful, 25 total
Cached:    22 cached, 25 total
  Time:    18.621s 

 ERROR  run failed: command  exited (1)
/home/evoke/git/woocommerce/plugins/woocommerce:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  woocommerce@7.9.0 build: `pnpm -w exec turbo run turbo:build --filter=$npm_package_name`
Exit status 1
```

Is there any solution ?
