### ISSUE TITLE
Deprecation notice: `wc_get_min_max_price_meta_query()` function is deprecated since version 3.6.

### ISSUE THREAD

**Issue by jimjasson** [woothemes/woocommerce#39380]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The All Products for WooCommerce Subscriptions QIT tests failed with the following error: 

```
The wc_get_min_max_price_meta_query() function is deprecated since version 3.6.
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1061): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->init_order_record(NULL, 0, Object(stdClass))
#1 /var/www/html/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1030): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->read_multiple(Array)
```

which seems to be coming from an API call from HPOS.

ref: https://compatibilitydashboard.wpcomstaging.com/?qit_results=4512536.5yT83coZUpqqjMsLTVRZsgBRbGTnupTlMw2vP3WskHgNojzQnLitHRWxjPHghJ3d

### Expected behavior

There shouldn't be any errors in the API QIT test.

### Actual behavior

There are errors in the API QIT test.

### Steps to reproduce

See this report: https://compatibilitydashboard.wpcomstaging.com/?qit_results=4512536.5yT83coZUpqqjMsLTVRZsgBRbGTnupTlMw2vP3WskHgNojzQnLitHRWxjPHghJ3d

### WordPress Environment

Clean environment as it is set up by the WooCommerce QIT flow.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
⏪ We should consider un-deprecating, if there is no suitable existing alternative (as we still call this function from a few spots across the codebase).

🟡 Setting to low priority since it doesn't actually break anything, and I think there is a 'patch' for the problem, from a QIT context? Let me know if I'm wrong.

**Comment by barryhughes** [comment]
✍🏼 Some useful context may be found here: https://github.com/woocommerce/woocommerce/pull/22718
