### ISSUE TITLE
PHP Fatal when uninstalling the plugin and `WC_REMOVE_ALL_DATA` constant set to `true`

### ISSUE THREAD

**Issue by eri-trabiccolo** [woothemes/woocommerce#39881]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When deleting the plugin and the `WC_REMOVE_ALL_DATA` constant is set to `true` I get a PHP fatal error.

### Expected behavior

 I would expect the WooCommerce plugin to be deleted and all of its data removed, and mostly getting no errors.

### Actual behavior

The Delete button link turns into "Deleting..."
An admin notice appears saying: `Deletion failed: There has been a critical error on this website.Learn more about troubleshooting WordPress.`

 - nothing else happens. 

Refreshing the page you see the plugin isn't there anymore, so it was deleted, although not all of its data was, plus in the error log you'd see something like:
```
[24-Aug-2023 10:04:19 UTC] PHP Warning:  require(/shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/src/Internal/Admin/Analytics.php): failed to open stream: No such file or directory in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php on line 90
[24-Aug-2023 10:04:19 UTC] PHP Fatal error:  require(): Failed opening required '/shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/src/Internal/Admin/Analytics.php' (include_path='.:/usr/local/lib/php') in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php on line 90
[24-Aug-2023 10:04:19 UTC] PHP Fatal error:  Uncaught Error: Class 'ActionScheduler_Lock' not found in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php:29
Stack trace:
#0 /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(106): ActionScheduler::lock()
#1 /shared/httpd/wptest/wordpress/wp-includes/class-wp-hook.php(310): ActionScheduler_QueueRunner->maybe_dispatch_async_request('')
#2 /shared/httpd/wptest/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#3 /shared/httpd/wptest/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /shared/httpd/wptest/wordpress/wp-includes/load.php(1252): do_action('shutdown')
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php on line 29
 ```
 
If you wait a bit more you'll also see a warning about the action_scheduler. Please note that I hadn't activated WooCommerce yet:
```
[24-Aug-2023 10:05:05 UTC] Cron reschedule event error for hook: action_scheduler_run_queue, Error code: invalid_schedule, Error message: Event schedule does not exist., Data: {"schedule":"every_minute","args":["WP Cron"],"interval":60}
```

Also note that if you instead activate WooCommerce first and then disable it and delete it you get an additional fatal:
```
[24-Aug-2023 10:15:02 UTC] PHP Warning:  include_once(/shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/admin/plugin-updates/class-wc-plugin-updates.php): failed to open stream: No such file or directory in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 2300
[24-Aug-2023 10:15:02 UTC] PHP Warning:  include_once(): Failed opening '/shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/admin/plugin-updates/class-wc-plugin-updates.php' for inclusion (include_path='.:/usr/local/lib/php') in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 2300
[24-Aug-2023 10:15:02 UTC] PHP Fatal error:  Uncaught Error: Class 'WC_Plugin_Updates' not found in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/wc-core-functions.php:2304
Stack trace:
#0 /shared/httpd/wptest/wordpress/wp-includes/class-wp-hook.php(310): wc_enable_wc_plugin_headers(Array)
#1 /shared/httpd/wptest/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /shared/httpd/wptest/wordpress/wp-includes/functions.php(6710): apply_filters('extra_plugin_he...', Array)
#3 /shared/httpd/wptest/wordpress/wp-admin/includes/plugin.php(91): get_file_data('/shared/httpd/w...', Array, 'plugin')
#4 /shared/httpd/wptest/wordpress/wp-admin/includes/plugin.php(339): get_plugin_data('/shared/httpd/w...', false, false)
#5 /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper.php(1162): get_plugins()
#6 /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php(179): WC_Helper::get_local_woo_plugins()
#7 /shared/httpd/ in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 2304
[24-Aug-2023 10:15:02 UTC] PHP Fatal error:  Uncaught Error: Class 'ActionScheduler_Lock' not found in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php:29
Stack trace:
#0 /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(106): ActionScheduler::lock()
#1 /shared/httpd/wptest/wordpress/wp-includes/class-wp-hook.php(310): ActionScheduler_QueueRunner->maybe_dispatch_async_request('')
#2 /shared/httpd/wptest/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#3 /shared/httpd/wptest/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /shared/httpd/wptest/wordpress/wp-includes/load.php(1252): do_action('shutdown')
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php on line 29
[24-Aug-2023 10:15:58 UTC] Cron reschedule event error for hook: action_scheduler_run_queue, Error code: invalid_schedule, Error message: Event schedule does not exist., Data: {"schedule":"every_minute","args":["WP Cron"],"interval":60}
```

### Steps to reproduce

- Install WooCommerce
- (log your PHP error)
- add `define( 'WC_REMOVE_ALL_DATA', true );` to your wp-config.php
- Delete WooCommerce plugin: from wp-admin Plugins, Delete button link.

### WordPress Environment

```
### WordPress Environment ###

WordPress address (URL): http://wptest.dvl.to
Site address (URL): http://wptest.dvl.to
WC Version: 8.0.2
REST API Version: ✔ 8.0.2
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.22.1
PHP Version: 7.4.33
PHP Post Max Size: 72 MB
PHP Time Limit: 120
PHP Max Input Vars: 8000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.12-MariaDB-1:10.6.12+maria~ubu2004-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.2
WC Database Prefix: wp_
Total Database Size: 5.23MB
Database Data Size: 3.53MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 8
post: 2
product: 1
revision: 4
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.0.2

### Inactive Plugins (7) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Elementor: by Elementor.com – 3.15.3
Hello Dolly: by Matt Mullenweg – 1.7.2
LifterLMS: by LifterLMS – 7.3.0
LifterLMS Assignments: by LifterLMS – 2.1.0
User Switching: by John Blackbourn & contributors – 1.7.0
Yoast SEO: by Team Yoast – 21.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #19 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-25 10:17:57 +00:00
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Complete: 5
Oldest: 2023-08-24 10:14:54 +0000
Newest: 2023-08-24 10:19:11 +0000

Failed: 1
Oldest: 2023-08-24 10:19:05 +0000
Newest: 2023-08-24 10:19:05 +0000

Pending: 1
Oldest: 2023-08-25 10:14:54 +0000
Newest: 2023-08-25 10:14:54 +0000


### Status report information ###

Generated at: 2023-08-24 10:21:35 +00:00
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> If you wait a bit more you'll also see a warning about the action_scheduler.
> Cron reschedule event error for hook: action_scheduler_run_queue

This isn't related to the uninstall issue. If you activate WC then deactivate it, you'll see this message within a couple minutes. WordPress removes the cron schedule and logs this message to document the reason the schedule was removed. If WC is left inactive for 24 hours then there is one of these messages for each of the WC cron schedules.

**Comment by nicholasjeberlin** [comment]
7224328-zen
