### ISSUE TITLE
Serialized coupon meta data causes fatal error

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#40569]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

A fatal error occurs on the coupon list screen:

```
[02-Oct-2023 18:38:18 UTC] PHP Fatal error: Uncaught TypeError: explode(): Argument [#2](https://a8c.zendesk.com/agent/tickets/2) ($string) must be of type string, array given in /var/www/html/app/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php:134
Stack trace:
[#0](https://a8c.zendesk.com/agent/tickets/0) /var/www/html/app/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php(134): explode()
[#1](https://a8c.zendesk.com/agent/tickets/1) /var/www/html/app/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Coupon_Data_Store_CPT->read()
[#2](https://a8c.zendesk.com/agent/tickets/2) /var/www/html/app/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(135): WC_Data_Store->read()
[#3](https://a8c.zendesk.com/agent/tickets/3) /var/www/html/app/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(123): WC_Coupon->read_object_from_database()
[#4](https://a8c.zendesk.com/agent/tickets/4) /var/www/html/app/wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-coupons.php(102): WC_Coupon->__construct()
[#5](https://a8c.zendesk.com/agent/tickets/5) /var/www/html/app/wp-content/plugins/woocommerce/includes/admin/list-tables/abstract-class-wc-admin-list-table.php(254): WC_Admin_List_Table_Coupons->prepare_row_data()
[#6](https://a8c.zendesk.com/agent/tickets/6) /var/www/html/app/wp-includes/class-wp-hook.php(310): WC_Admin_List_Table->render_columns()
[#7](https://a8c.zendesk.com/agent/tickets/7) /var/www/html/app/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
[#8](https://a8c.zendesk.com/agent/tickets/8) /var/www/html/app/wp-includes/plugin.php(517): WP_Hook->do_action()
[#9](https://a8c.zendesk.com/agent/tickets/9) /var/www/html/app/wp-admin/includes/class-wp-posts-list-table.php(1387): do_action()
[#10](https://a8c.zendesk.com/agent/tickets/10) /var/www/html/app/wp-admin/includes/class-wp-list-table.php(1752): WP_Posts_List_Table->column_default()
[#11](https://a8c.zendesk.com/agent/tickets/11) /var/www/html/app/wp-admin/includes/class-wp-posts-list-table.php(1421): WP_List_Table->single_row_columns()
[#12](https://a8c.zendesk.com/agent/tickets/12) /var/www/html/app/wp-admin/includes/class-wp-posts-list-table.php(829): WP_Posts_List_Table->single_row()
[#13](https://a8c.zendesk.com/agent/tickets/13) /var/www/html/app/wp-admin/includes/class-wp-posts-list-table.php(805): WP_Posts_List_Table->_display_rows()
[#14](https://a8c.zendesk.com/agent/tickets/14) /var/www/html/app/wp-admin/includes/class-wp-list-table.php(1662): WP_Posts_List_Table->display_rows()
[#15](https://a8c.zendesk.com/agent/tickets/15) /var/www/html/app/wp-admin/includes/class-wp-list-table.php(1589): WP_List_Table->display_rows_or_placeholder()
[#16](https://a8c.zendesk.com/agent/tickets/16) /var/www/html/app/wp-admin/edit.php(495): WP_List_Table->display()
[#17](https://a8c.zendesk.com/agent/tickets/17) {main}
thrown in /var/www/html/app/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php on line 134
```

7113135-zen

### Expected behavior

List should show

### Actual behavior

Fatal error

### Steps to reproduce

1. Add two products to a coupon's usage restrictions
2. In `wp shell`
```
$ids = explode( ',', get_post_meta( COUPONID, 'product_ids', true ) );
update_post_meta( COUPONID, 'product_ids', $ids );
```
3. Reload the coupon list in the dashboard
4. The issue cn also be produced with the `excluded_product_ids`
5. While this issue is likely being created by an extension or custom code, deactivating the extension/removing the code does not eliminate the error.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nirkons** [comment]
Adding to this ticket as we are still having this issue, replacing 134-135 with these lines solves the issue but we are unable to update woocommerce (or have to reapply the fix for every update)

```

 'product_ids' => is_array(get_post_meta( $coupon_id, 'product_ids', true )) ? get_post_meta( $coupon_id, 'product_ids', true ) : array_filter( (array) explode( ',', get_post_meta( $coupon_id, 'product_ids',true))),

'excluded_product_ids' => is_array(get_post_meta( $coupon_id, 'exclude_product_ids', true )) ? get_post_meta( $coupon_id, 'exclude_product_ids', true ) : array_filter( (array) explode( ',', get_post_meta( $coupon_id, 'exclude_product_ids', true ))),
```

**Comment by nirkons** [comment]
any updates on this? I have to apply this fix every single time I updated woocommerce :(

**Comment by nirkons** [comment]
Unfortunately this issue still persists in latest version on every single woocommerce store that I run, entering the coupons screen results in fatal error.

It's a small fix, is there any chance to resolve this critical issue?

Thanks

**Comment by thisissandip** [comment]
7544756-zen

**Comment by nirkons** [comment]
Still occurs on 8.6.1 :(

will this ever be fixed? I can't be the only one experiencing this issue

**Comment by nirkons** [comment]
still happens with 8.6.1, will this ever get fixed? :(

I can't be the only one experiencing this issue

**Comment by Michael-Ashfield-Rixxo** [comment]
I can also confirm I have this issue, the above hotfix worked for me but has to be redone every time I run a Woocommerce update.

**Comment by nirkons** [comment]
Still happening on 8.8.3...

is this ever going to be resolved?

**Comment by nirkons** [comment]
still happening on 8.9.1 :(

**Comment by nirkons** [comment]
with latest 8.9.2 woocommerce, the entire site goes down and not only coupons page

```
[05-Jun-2024 07:41:16 UTC] PHP Fatal error:  Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /var/www/html/app/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php:134
Stack trace:
#0 /var/www/html/app/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php(134): explode()
#1 /var/www/html/app/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Coupon_Data_Store_CPT->read()
#2 /var/www/html/app/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(156): WC_Data_Store->read()
#3 /var/www/html/app/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(144): WC_Coupon->read_object_from_database()
#4 /var/www/html/app/wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-limited-recurring-coupon-manager.php(90): WC_Coupon->__construct()
#5 /var/www/html/app/wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-limited-recurring-coupon-manager.php(113): WCS_Limited_Recurring_Coupon_Manager::get_coupon_limit()
#6 /var/www/html/app/wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-limited-recurring-coupon-manager.php(127): WCS_Limited_Recurring_Coupon_Manager::coupon_is_limited()
#7 /var/www/html/app/wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-limited-recurring-coupon-manager.php(354): WCS_Limited_Recurring_Coupon_Manager::cart_contains_limited_recurring_coupon()
#8 /var/www/html/app/wp-includes/class-wp-hook.php(324): WCS_Limited_Recurring_Coupon_Manager::gateways_subscription_amount_changes()
#9 /var/www/html/app/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#10 /var/www/html/app/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(333): apply_filters()
#11 /var/www/html/app/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php(587): WC_Payment_Gateways->get_available_payment_gateways()
#12 /var/www/html/app/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php(315): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->render_button_wrapper_registrar()
#13 /var/www/html/app/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/ButtonModule.php(62): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->render_wrapper()
#14 /var/www/html/app/wp-includes/class-wp-hook.php(324): WooCommerce\PayPalCommerce\Button\ButtonModule::WooCommerce\PayPalCommerce\Button\{closure}()
#15 /var/www/html/app/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#16 /var/www/html/app/wp-includes/plugin.php(565): WP_Hook->do_action()
#17 /var/www/html/app/wp-includes/class-wp.php(830): do_action_ref_array()
#18 /var/www/html/app/wp-includes/functions.php(1336): WP->main()
#19 /var/www/html/app/wp-blog-header.php(16): wp()
#20 /var/www/html/app/index.php(17): require('...')
#21 {main}
  thrown in /var/www/html/app/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php on line 134

```

can this fix please be implemented???
