### ISSUE TITLE
Variable product with attribute name "variation" fatal errors on checkout complete

### ISSUE THREAD

**Issue by james-allan** [woothemes/woocommerce#41422]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This issue was originally reported to Subscriptions (https://github.com/woocommerce/woocommerce-subscriptions/issues/4589), however it impacts WC variable products too.

If you have a variable product with "variation" as an attribute name, you will get the following fatal error on the order received page.

```
PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in /public/wp-content/plugins/woocommerce/includes/class-wc-product-variation.php:174
Stack trace:
#0 /public/wp-content/plugins/woocommerce/includes/class-wc-product-variation.php(174): array_filter('B', 'wc_array_filter...')
#1 /public/wp-content/plugins/woocommerce/templates/order/order-details-item.php(31): WC_Product_Variation->get_permalink(Object(WC_Order_Item_Product))
#2 /public/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('...')
#3 /public/wp-content/plugins/woocommerce/templates/order/order-details.php(71): wc_get_template('order/order-det...', Array)
#4 /public/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('...')
#5 /public/wp-content/plugins/woocommerce/includes/wc-template-functions.php(2724): wc_get_template('order/order-det...', Array)
#6 /public/wp-includes/class-wp-hook.php(324): woocommerce_order_details_table(5218)
#7 /public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#8 /public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /public/wp-content/plugins/woocommerce/templates/checkout/thankyou.php(82): do_action('woocommerce_tha...', 5218)
#10 /public/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('...')
#11 /public/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(324): wc_get_template('checkout/thanky...', Array)
#12 /public/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(63): WC_Shortcode_Checkout::order_received(5218)
#13 /public/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_Checkout::output('')
#14 /public/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(95): WC_Shortcodes::shortcode_wrapper(Array, '')
#15 /public/wp-includes/shortcodes.php(433): WC_Shortcodes::checkout('', '', 'woocommerce_che...')
#16 [internal function]: do_shortcode_tag(Array)
#17 /public/wp-includes/shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(woocom...', 'do_shortcode_ta...', '[woocommerce_ch...')
#18 /public/wp-includes/class-wp-hook.php(324): do_shortcode('[woocommerce_ch...')
#19 /public/wp-includes/plugin.php(205): WP_Hook->apply_filters('[woocommerce_ch...', Array)
#20 /public/wp-includes/post-template.php(256): apply_filters('the_content', '<!-- wp:woocomm...')
#21 /public/wp-content/themes/storefront/inc/storefront-template-functions.php(352): the_content()
#22 /public/wp-includes/class-wp-hook.php(324): storefront_page_content('')
#23 /public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#24 /public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#25 /public/wp-content/themes/storefront/content-page.php(18): do_action('storefront_page')
#26 /public/wp-includes/template.php(792): require('...')
#27 /public/wp-includes/template.php(725): load_template('...', false, Array)
#28 /public/wp-includes/general-template.php(206): locate_template(Array, true, false, Array)
#29 /public/wp-content/themes/storefront/page.php(24): get_template_part('content', 'page')
#30 /public/wp-includes/template-loader.php(106): include('...')
#31 /public/wp-blog-header.php(19): require_once('...')
#32 /public/index.php(17): require('...')
#33 {main}
  thrown in /public/wp-content/plugins/woocommerce/includes/class-wc-product-variation.php on line 174
```

### Expected behavior

You should be able to create and purchase a variable product with this attribute name without  a fatal error. 

### Actual behavior

A fatal error occurs on the order received page. 

### Steps to reproduce

1. Create a variable product with an attribute called "variation". 

<img width="307" alt="Screenshot 2023-11-14 at 5 18 43 pm" src="https://github.com/woocommerce/woocommerce/assets/8490476/592172b1-d557-4801-827f-08230fca531b">

2. Add anyone of those variations to the cart.
3. Checkout.
4. Checkout will be successful but on the order-received page you should get the fatal error as mentioned above. 

Having a look into what causes this, the issue appears to be in the `WC_Product_Variation::get_permalink()` function. It attempts to get 'variation' from a `WC_Order_Item_Product` instance - [`if ( ! empty( $item_object['variation'] ) )`](https://github.com/woocommerce/woocommerce/blob/8.2.2/plugins/woocommerce/includes/class-wc-product-variation.php#L164). Because this order item product instance has a meta key with `variation`, the `ArrayAccess` functions of `WC_Order_Item` returns that meta value instead of an array of attributes. 

I'm not 100% sure of what the fix is here as I can't tell what the original purpose of that logic is. Does it need to ignore order item objects? 

eg 
```
if ( ! is_object( $item_object ) && ! empty( $item_object['variation'] ) ) {
```

But then the name of the variable `$item_object` as an object seems relevant. 

### WordPress Environment ###

WordPress address (URL): https://wcdev.local
Site address (URL): https://wcdev.local
WC Version: 8.2.2
REST API Version: ✔ 8.2.2
WC Blocks Version: ✔ 11.1.3
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix)
PHP Version: 8.0.22
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.88.1
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.2
WC Database Prefix: wp_
Total Database Size: 59.77MB
Database Data Size: 38.33MB
Database Index Size: 21.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.20MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 5.52MB + Index: 5.92MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 5.02MB + Index: 0.06MB + Engine InnoDB
wp_actionscheduler_actions: Data: 4.23MB + Index: 2.38MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.20MB + Index: 3.61MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 2.52MB + Index: 1.72MB + Engine InnoDB
wp_lhr_log: Data: 6.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.03MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 4.05MB + Index: 5.05MB + Engine InnoDB
wp_posts: Data: 0.20MB + Index: 0.09MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpl_user_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.36MB + Index: 0.66MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.25MB + Index: 0.30MB + Engine InnoDB
wp_wc_order_stats: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 4
page: 9
post: 2
product: 117
product_variation: 105
revision: 9
shop_coupon: 5
shop_order: 177
shop_order_placehold: 6
shop_subscription: 100
user_request: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 7.6.2
WooCommerce: by Automattic – 8.2.2

### Inactive Plugins (29) ###

Action Scheduler: by Automattic – 3.6.4
AutomateWoo: by WooCommerce – 5.7.5
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.0.3 (update to version 3.0.8 is available)
Log HTTP Requests: by FacetWP
LLC – 1.4.1

Query Monitor: by John Blackbourn – 3.15.0
Relative URL: by Tunghsiao Liu – 0.1.8
Test wcpay PR 6643: by Automattic –
User Switching: by John Blackbourn & contributors – 1.7.0
WCPay Server Redirect: by Automattic –
WCPay Subscription Generator: by James Allan –
WooCommerce All Products For Subscriptions: by WooCommerce – 4.1.2 (update to version 4.1.3 is available)
WooCommerce Deposits: by WooCommerce – 2.1.7 (update to version 2.2.2 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.8.4 (update to version 2.8.8 is available)
WooCommerce Eway Payment Gateway: by WooCommerce – 3.6.1 (update to version 3.7.1 is available)
WooCommerce Payfast Gateway: by WooCommerce – 1.5.4 (update to version 1.5.9 is available)
WooCommerce Payments: by Automattic – 6.7.1
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Pre-Orders: by WooCommerce – 2.0.2 (update to version 2.0.5 is available)
WooCommerce Product Add-ons: by WooCommerce – 6.4.7 (update to version 6.5.0 is available)
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.4.3 (update to version 1.4.4 is available)
WooCommerce SnapScan Gateway: by WooCommerce – 1.2.3
WooCommerce Square: by WooCommerce – 4.3.1
WooCommerce Subscription Downloads: by WooCommerce – 1.4.0 (update to version 1.4.1 is available)
WooCommerce Subscriptions: by WooCommerce – 5.2.0 (update to version 5.7.0 is available)
WooCommerce Subscriptions Core: by Automattic – 6.5.0
WP Console: by Edi Amin – 2.3.1
WP Job Manager: by Automattic – 1.42.0
WP Job Manager - WooCommerce Paid Listings: by Automattic – 2.9.8
WP phpMyAdmin: by Puvox.software – 5.2.1.02

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
job_package (job_package)
job_package_subscription (job_package_subscription)
new-variable (new-variable)
resume_package (resume_package)
resume_package_subscription (resume_package_subscription)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #187 - /block-checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.3.0 (update to version 4.5.3 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /Users/jamesallan/local-dev/wcdev/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/Users/jamesallan/local-dev/wcdev/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/Users/jamesallan/local-dev/wcdev/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-15 01:41:41 +10:00
Options: ✔
Notes: 119
Onboarding: completed

### Action Scheduler ###

Complete: 7,618
Oldest: 2023-10-15 23:02:59 +0000
Newest: 2023-11-14 07:06:06 +0000

Pending: 390
Oldest: 2023-11-14 07:34:00 +0000
Newest: 2026-08-15 01:27:26 +0000

Failed: 955
Oldest: 2023-05-23 05:49:35 +0000
Newest: 2023-11-14 06:55:29 +0000

Canceled: 93
Oldest: 2023-10-17 06:36:16 +0000
Newest: 2023-11-13 01:57:52 +0000

### Status report information ###

Generated at: 2023-11-14 17:34:00 +10:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment]
I don't believe this issue is for Rubik/Kirigami/Origami teams, the stacktrace doesn't touch our codebase and by the issue description the bug resides in Core.
I'm reassigning this to Proton

**Comment by mouligreenlaw** [comment]
7554376-zen

**Comment by flickerb** [comment]
Just adding in I have found this exact same issue as well. I have edited the file at line 164 to:
if ( ! empty( $item_object['variation'] ) && is_array( $item_object['variation'] )  ) {

That gets around it for now...
