### ISSUE TITLE
Problem with creation of Variant Products via REST API

### ISSUE THREAD

**Issue by tobiasgardner** [woothemes/woocommerce#41661]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am using the REST API to process data on Woocommerce. And I have a scenario where I create a "parent" product and one or more child product (variants).
Creation of parent product including attributes etc works find.

Problem comes when you create the variants... Took me some time to find since the API indicates that everything goes fine (response is ok, json contains new ids etc), but when you look at the product in the Woocommerce Admin, there are no variants connected. HOWEVER, they are saved somehow in the database, because trying to create them again will result in an error due to SKU collission.

According to the API documentation, there are many fields which are possible include when creating a variant product, one of these is "status". When the field "status" is included in the data, the problem above happens.
https://woocommerce.github.io/woocommerce-rest-api-docs/#product-variations

### Creating the parent product - works as expected
```
REQUEST to: products/batch
{ 'create': [ { 'attributes': [ { 'name': 'Variabel 1',
                                  'options': ['Bertil', 'Kalle'],
                                  'position': 0,
                                  'variation': 'true',
                                  'visible': 'true'},
                                { 'name': 'Variabel 2',
                                  'options': ['Anna', 'Stina'],
                                  'position': 1,
                                  'variation': 'true',
                                  'visible': 'true'}],
                'backorders': 'notify',
                'catalog_visibility': 'visible',
                'categories': [{'id': '238'}],
                'default_attributes': [],
                'description': '<p>Lite produktbeskrivning</p>',
                'downloadable': 'false',
                'featured': 'false',
                'manage_stock': 'yes',
                'name': 'Test av variabla produkter med flera variabler',
                'parent_id': '0',
                'purchase_note': '',
                'regular_price': '',
                'sale_price': '',
                'shipping_class': 'fraktklass-standard',
                'short_description': '',
                'sku': '102916',
                'sold_individually': 'false',
                'status': 'draft',
                'stock_quantity': 0,
                'type': 'variable',
                'virtual': 'false'}],
  'delete': [],
  'update': []}

RESPONSE
{ 'create': [ { '_links': { 'collection': [{'href': 'https://www.villaspa.se/wp-json/wc/v3/products'}],
                            'self': [{'href': 'https://www.villaspa.se/wp-json/wc/v3/products/41433'}]},
                'attributes': [ { 'id': 0,
                                  'name': 'Variabel 1',
                                  'options': ['Bertil', 'Kalle'],
                                  'position': 0,
                                  'variation': True,
                                  'visible': True},
                                { 'id': 0,
                                  'name': 'Variabel 2',
                                  'options': ['Anna', 'Stina'],
                                  'position': 1,
                                  'variation': True,
                                  'visible': True}],
                'average_rating': '0',
                'backordered': True,
                'backorders': 'notify',
                'backorders_allowed': True,
                'button_text': '',
                'catalog_visibility': 'visible',
                'categories': [{'id': 238, 'name': 'Diverse', 'slug': 'diverse-2'}],
                'cross_sell_ids': [],
                'date_created': '2023-11-23T14:30:15',
                'date_created_gmt': '2023-11-23T13:30:15',
                'date_modified': '2023-11-23T14:30:15',
                'date_modified_gmt': '2023-11-23T13:30:15',
                'date_on_sale_from': None,
                'date_on_sale_from_gmt': None,
                'date_on_sale_to': None,
                'date_on_sale_to_gmt': None,
                'default_attributes': [],
                'description': '<p>Lite produktbeskrivning</p>',
                'dimensions': {'height': '', 'length': '', 'width': ''},
                'download_expiry': -1,
                'download_limit': -1,
                'downloadable': False,
                'downloads': [],
                'external_url': '',
                'featured': False,
                'generated_slug': 'test-av-variabla-produkter-med-flera-variabler',
                'grouped_products': [],
                'has_options': True,
                'id': 41433,
                'images': [],
                'low_stock_amount': None,
                'manage_stock': True,
                'menu_order': 0,
                'meta_data': [],
                'name': 'Test av variabla produkter med flera variabler',
                'on_sale': False,
                'parent_id': 0,
                'permalink': 'https://www.villaspa.se/?post_type=product&p=41433',
                'permalink_template': 'https://www.villaspa.se/produkt/%pagename%/',
                'post_password': '',
                'price': '',
                'price_html': '<span class="woocommerce-Price-amount amount"></span>',
                'purchasable': False,
                'purchase_note': '',
                'rating_count': 0,
                'regular_price': '',
                'related_ids': [468, 500, 483, 529, 427],
                'reviews_allowed': True,
                'sale_price': '',
                'shipping_class': 'fraktklass-standard',
                'shipping_class_id': 282,
                'shipping_required': True,
                'shipping_taxable': True,
                'short_description': '',
                'sku': '102916',
                'slug': '',
                'sold_individually': False,
                'status': 'draft',
                'stock_quantity': 0,
                'stock_status': 'onbackorder',
                'tags': [],
                'tax_class': '',
                'tax_status': 'taxable',
                'total_sales': 0,
                'type': 'variable',
                'upsell_ids': [],
                'variations': [],
                'virtual': False,
                'weight': ''}]}
```

### Creating the child product - works as expected
```
REQUEST to: products/41433/variations/batch
{ 'create': [ { 'attributes': [{'name': 'Variabel 1', 'option': 'Kalle'}, {'name': 'Variabel 2', 'option': 'Anna'}],
                'backorders': 'notify',
                'description': '',
                'downloadable': 'false',
                'manage_stock': 'yes',
                'regular_price': '40',
                'sale_price': '',
                'shipping_class': 'fraktklass-standard',
                'sku': '102917',
                'stock_quantity': 0,
                'virtual': 'false'}],
  'delete': [],
  'update': []}

RESPONSE
{ 'create': [ { '_links': { 'collection': [{'href': 'https://www.villaspa.se/wp-json/wc/v3/products/41433/variations'}],
                            'self': [{'href': 'https://www.villaspa.se/wp-json/wc/v3/products/41433/variations/41434'}],
                            'up': [{'href': 'https://www.villaspa.se/wp-json/wc/v3/products/41433'}]},
                'attributes': [{'id': 0, 'name': 'Variabel 1', 'option': 'Kalle'}, {'id': 0, 'name': 'Variabel 2', 'option': 'Anna'}],
                'backordered': True,
                'backorders': 'notify',
                'backorders_allowed': True,
                'date_created': '2023-11-23T14:30:17',
                'date_created_gmt': '2023-11-23T13:30:17',
                'date_modified': '2023-11-23T14:30:17',
                'date_modified_gmt': '2023-11-23T13:30:17',
                'date_on_sale_from': None,
                'date_on_sale_from_gmt': None,
                'date_on_sale_to': None,
                'date_on_sale_to_gmt': None,
                'description': '',
                'dimensions': {'height': '', 'length': '', 'width': ''},
                'download_expiry': -1,
                'download_limit': -1,
                'downloadable': False,
                'downloads': [],
                'id': 41434,
                'image': None,
                'low_stock_amount': None,
                'manage_stock': True,
                'menu_order': 0,
                'meta_data': [],
                'name': 'Kalle, Anna',
                'on_sale': False,
                'parent_id': 41433,
                'permalink': 'https://www.villaspa.se/?post_type=product&p=41433&attribute_variabel-1=Kalle&attribute_variabel-2=Anna',
                'price': '40',
                'purchasable': True,
                'regular_price': '40',
                'sale_price': '',
                'shipping_class': 'fraktklass-standard',
                'shipping_class_id': 282,
                'sku': '102917',
                'status': 'publish',
                'stock_quantity': 0,
                'stock_status': 'onbackorder',
                'tax_class': 'parent',
                'tax_status': 'taxable',
                'virtual': False,
                'weight': ''}]}
```

Image from admin after operation (successful):
![image](https://github.com/woocommerce/woocommerce/assets/7185907/8607ca6d-0f92-4f4d-8625-418485d24fd9)

### Creating another child product WITH the field "status" in the input - does not work
```
REQUEST to: products/41433/variations/batch
{ 'create': [ { 'attributes': [{'name': 'Variabel 1', 'option': 'Kalle'}, {'name': 'Variabel 2', 'option': 'Stina'}],
                'backorders': 'notify',
                'description': '',
                'downloadable': 'false',
                'manage_stock': 'yes',
                'regular_price': '48',
                'sale_price': '',
                'shipping_class': 'fraktklass-standard',
                'sku': '102918',
                'status': 'draft',
                'stock_quantity': 0,
                'virtual': 'false'}],
  'delete': [],
  'update': []}

RESPONSE
{ 'create': [ { '_links': { 'collection': [{'href': 'https://www.villaspa.se/wp-json/wc/v3/products/41433/variations'}],
                            'self': [{'href': 'https://www.villaspa.se/wp-json/wc/v3/products/41433/variations/41435'}],
                            'up': [{'href': 'https://www.villaspa.se/wp-json/wc/v3/products/41433'}]},
                'attributes': [{'id': 0, 'name': 'Variabel 1', 'option': 'Kalle'}, {'id': 0, 'name': 'Variabel 2', 'option': 'Stina'}],
                'backordered': True,
                'backorders': 'notify',
                'backorders_allowed': True,
                'date_created': '2023-11-23T14:36:33',
                'date_created_gmt': '2023-11-23T13:36:33',
                'date_modified': '2023-11-23T14:36:33',
                'date_modified_gmt': '2023-11-23T13:36:33',
                'date_on_sale_from': None,
                'date_on_sale_from_gmt': None,
                'date_on_sale_to': None,
                'date_on_sale_to_gmt': None,
                'description': '',
                'dimensions': {'height': '', 'length': '', 'width': ''},
                'download_expiry': -1,
                'download_limit': -1,
                'downloadable': False,
                'downloads': [],
                'id': 41435,
                'image': None,
                'low_stock_amount': None,
                'manage_stock': True,
                'menu_order': 0,
                'meta_data': [],
                'name': 'Kalle, Stina',
                'on_sale': False,
                'parent_id': 41433,
                'permalink': 'https://www.villaspa.se/?post_type=product&p=41433&attribute_variabel-1=Kalle&attribute_variabel-2=Stina',
                'price': '48',
                'purchasable': False,
                'regular_price': '48',
                'sale_price': '',
                'shipping_class': 'fraktklass-standard',
                'shipping_class_id': 282,
                'sku': '102918',
                'status': 'draft',
                'stock_quantity': 0,
                'stock_status': 'onbackorder',
                'tax_class': 'parent',
                'tax_status': 'taxable',
                'virtual': False,
                'weight': ''}]}

```

Everything looks good in the API response, but looking in admin, the system has not connected the new product:
![image](https://github.com/woocommerce/woocommerce/assets/7185907/82331642-fdfc-44aa-a598-101d88e6a94d)

### Trying to create the same product again (that "fails" in the last attemp) is not possible because we will get a SKU collision
```
REQUEST to: products/41433/variations/batch
{ 'create': [ { 'attributes': [{'name': 'Variabel 1', 'option': 'Kalle'}, {'name': 'Variabel 2', 'option': 'Stina'}],
                'backorders': 'notify',
                'description': '',
                'downloadable': 'false',
                'manage_stock': 'yes',
                'regular_price': '48',
                'sale_price': '',
                'shipping_class': 'fraktklass-standard',
                'sku': '102918',
                'status': 'draft',
                'stock_quantity': 0,
                'virtual': 'false'}],
  'delete': [],
  'update': []}

 RESPONSE from: products/batch
{ 'create': [ { 'error': { 'code': 'product_invalid_sku',
                           'data': {'resource_id': 41435, 'status': 400, 'unique_sku': '102918-1'},
                           'message': 'Ogiltigt eller dubblett av artikelnummer.'},
                'id': 0}]}
Updating 0 products with the following fields: []
```

### Expected behavior

1. If there is a problem to create the variant product, I expected the API response to report that.
1. API documentation should not include fields that are not possible to update / create
2. If such fields are included, and the system cannot filter them out, I would expected an error stating that the product could not be created for this and that reason.

### Actual behavior

1. API indicates that the product is created. And it "seems" to be, but it is not connected to the parent product, i.e. completely useless.

### Steps to reproduce

Screenshots and API request/responses provided above in problem statement.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.villaspa.se
Site address (URL): https://www.villaspa.se
WC Version: 8.3.0
REST API Version: ✔ 8.3.0
WC Blocks Version: ✔ 11.4.8
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.11
PHP Post Max Size: 50 MB
PHP Time Limit: 90
PHP Max Input Vars: 3000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB-cll-lve
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.0
WC Database Prefix: wp_
Total databasstorlek: 557.54MB
Datastorlek för databas: 477.09MB
Indexstorlek för databas: 80.45MB
wp_woocommerce_sessions: Data: 241.64MB + Index: 4.43MB + Motor MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_woocommerce_order_items: Data: 1.76MB + Index: 1.20MB + Motor MyISAM
wp_woocommerce_order_itemmeta: Data: 19.30MB + Index: 9.65MB + Motor MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_actionscheduler_actions: Data: 1.07MB + Index: 0.54MB + Motor MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_actionscheduler_logs: Data: 1.30MB + Index: 0.78MB + Motor MyISAM
wp_aws_cache: Data: 3.36MB + Index: 0.00MB + Motor MyISAM
wp_aws_index: Data: 9.35MB + Index: 9.12MB + Motor MyISAM
wp_berocket_termmeta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Motor MyISAM
wp_comments: Data: 9.30MB + Index: 3.70MB + Motor MyISAM
wp_facetwp_index: Data: 1.61MB + Index: 0.68MB + Motor MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_litespeed_avatar: Data: 0.01MB + Index: 0.01MB + Motor MyISAM
wp_litespeed_img_optm: Data: 2.46MB + Index: 0.94MB + Motor MyISAM
wp_litespeed_img_optming: Data: 0.02MB + Index: 0.03MB + Motor MyISAM
wp_litespeed_url: Data: 0.38MB + Index: 0.48MB + Motor MyISAM
wp_litespeed_url_file: Data: 1.23MB + Index: 1.60MB + Motor MyISAM
wp_mclean_refs: Data: 0.09MB + Index: 0.04MB + Motor MyISAM
wp_mclean_scan: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_ms_snippets: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_options: Data: 19.19MB + Index: 0.61MB + Motor MyISAM
wp_pmxe_exports: Data: 0.66MB + Index: 0.00MB + Motor MyISAM
wp_pmxe_google_cats: Data: 0.26MB + Index: 0.05MB + Motor MyISAM
wp_pmxe_posts: Data: 0.62MB + Index: 0.28MB + Motor MyISAM
wp_pmxe_templates: Data: 0.19MB + Index: 0.00MB + Motor MyISAM
wp_pmxi_files: Data: 0.01MB + Index: 0.00MB + Motor MyISAM
wp_pmxi_hash: Data: 0.19MB + Index: 0.18MB + Motor MyISAM
wp_pmxi_history: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_pmxi_images: Data: 0.36MB + Index: 0.04MB + Motor MyISAM
wp_pmxi_imports: Data: 0.83MB + Index: 0.00MB + Motor MyISAM
wp_pmxi_posts: Data: 1.64MB + Index: 0.52MB + Motor MyISAM
wp_pmxi_templates: Data: 0.05MB + Index: 0.00MB + Motor MyISAM
wp_postmeta: Data: 67.87MB + Index: 34.58MB + Motor MyISAM
wp_posts: Data: 8.13MB + Index: 3.03MB + Motor MyISAM
wp_sco_sessions: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_seopress_significant_keywords: Data: 0.31MB + Index: 0.36MB + Motor MyISAM
wp_snippets: Data: 0.05MB + Index: 0.00MB + Motor MyISAM
wp_termmeta: Data: 0.22MB + Index: 0.22MB + Motor MyISAM
wp_terms: Data: 0.04MB + Index: 0.09MB + Motor MyISAM
wp_term_relationships: Data: 0.35MB + Index: 0.77MB + Motor MyISAM
wp_term_taxonomy: Data: 0.05MB + Index: 0.06MB + Motor MyISAM
wp_usermeta: Data: 0.33MB + Index: 0.12MB + Motor MyISAM
wp_users: Data: 0.01MB + Index: 0.01MB + Motor MyISAM
wp_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Motor MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wc_category_lookup: Data: 0.01MB + Index: 0.02MB + Motor MyISAM
wp_wc_customer_lookup: Data: 0.52MB + Index: 0.44MB + Motor MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.03MB + Motor InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.22MB + Motor InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.06MB + Motor InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.13MB + Motor InnoDB
wp_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.11MB + Motor MyISAM
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.06MB + Motor InnoDB
wp_wc_order_product_lookup: Data: 1.16MB + Index: 1.21MB + Motor MyISAM
wp_wc_order_stats: Data: 0.73MB + Index: 0.42MB + Motor MyISAM
wp_wc_order_tax_lookup: Data: 0.38MB + Index: 0.50MB + Motor MyISAM
wp_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_wc_product_meta_lookup: Data: 0.17MB + Index: 0.27MB + Motor MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_bundled_itemmeta: Data: 0.00MB + Index: 0.01MB + Motor MyISAM
wp_woocommerce_bundled_items: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_woocommerce_gpf_google_taxonomy: Data: 2.52MB + Index: 0.23MB + Motor InnoDB
wp_woof_query_cache: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wpforms_payments: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wpforms_payment_meta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Motor MyISAM
wp_wpmailsmtp_debug_events: Data: 0.06MB + Index: 0.00MB + Motor InnoDB
wp_wpmailsmtp_emails_log: Data: 75.02MB + Index: 1.09MB + Motor InnoDB
wp_wpmailsmtp_email_tracking_events: Data: 1.52MB + Index: 1.09MB + Motor InnoDB
wp_wpmailsmtp_email_tracking_links: Data: 0.52MB + Index: 0.31MB + Motor InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.04MB + Index: 0.01MB + Motor MyISAM

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 2972
b2bking_custom_field: 9
b2bking_custom_role: 2
b2bking_group: 3
b2bking_rule: 1
br_product_filter: 2
ct_template: 13
custom_css: 1
nav_menu_item: 44
oembed_cache: 3
oxy_user_library: 1
page: 39
post: 1
product: 2039
product_variation: 167
revision: 163
seopress_404: 9849
seopress_bot: 7
seopress_schemas: 1
shop_coupon: 382
shop_order: 8654
shop_order_refund: 46
wapf_product: 1
wp_block: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

Advanced Custom Fields PRO: av WP Engine – 6.2.3
Advanced Database Cleaner: av Younes JFR. – 3.1.3
Advanced Woo Search PRO: av ILLID – 2.92
All-in-One WP Migration: av ServMask – 7.79
Code Snippets: av Code Snippets Pro – 3.6.2
Cookies och Content Security Policy: av Jonk @ Follow me Darling – 2.17
GTM4WP: av Thomas Geiger – 1.18.1
Hydrogen Pack: av Clean Plugins – 1.4.4
Facebook for WooCommerce: av Facebook – 3.1.3
Fortnox: av Redlight Media – 4.3.7
Fraktjakts fraktmetod för WooCommerce: av Fraktjakt AB (Sverige) – 2.5.1
OMGF: av Daan from Daan.dev – 5.7.6
LiteSpeed Cache: av LiteSpeed Technologies – 5.7.0.1
Loco Translate: av Tim Whitlock – 2.6.6
Media Cleaner (Pro): av Jordy Meow – 6.6.4
OxyNinja: av OxyNinja – 3.5.3
Oxy Toolbox: av Gagan S Goraya
Sridhar Katakam – 1.5.9

Oxygen Gutenberg Integration: av Soflyy – 1.4.4
Oxygen Elements for WooCommerce: av Soflyy – 2.0
Oxygen: av Soflyy – 4.7.1
Remember Me Controls: av Scott Reilly – 2.0.1
Svea Checkout för WooCommerce: av The Generation AB – 2.5.2
UpdraftPlus - Backup/Restore: av UpdraftPlus.Com
DavidAnderson – 1.23.12

User Menus: av Code Atlantic – 1.3.2
WooCommerce Stripe Gateway: av WooCommerce – 7.7.0
WooCommerce Swish Ecommerce Gateway: av Redlight media – 5.2.0
Sequential Order Numbers for WooCommerce: av SkyVerge – 1.10.1
WooCommerce: av Automattic – 8.3.0 (en uppdatering till version 8.3.1 finns tillgänglig)
WP All Export Pro: av Soflyy – 1.8.6
WP All Import Pro: av Soflyy – 4.8.5
Asset CleanUp: Page Speed Booster: av Gabe Livan – 1.3.9.3
WP Mail SMTP Pro: av WP Mail SMTP – 3.10.1
SEOPress PRO: av The SEO Guys at SEOPress – 7.2
SEOPress: av The SEO Guys at SEOPress – 7.2
WP All Export - ACF Export Add-On Pro: av Soflyy – 1.0.5
WP All Export - User Export Add-On Pro: av Soflyy – 1.0.7
WP All Export - WooCommerce Export Add-On Pro: av Soflyy – 1.0.9
WP All Import - ACF Add-On: av Soflyy – 3.3.8
WP All Import - WooCommerce Import Add-On Pro: av Soflyy – 4.0.0
WPForms Lite: av WPForms – 1.8.4.1

### Inactive Plugins (22) ###

Advanced Product Fields for WooCommerce: av StudioWombat – 1.6.4
annasta Woocommerce Product Filters: av annasta.net – 1.6.7
B2BKing: av WebWizards – 3.1.0
Better Search Replace: av WP Engine – 1.4.3
CoBlocks: av GoDaddy – 3.1.5
FacetWP: av FacetWP
LLC – 3.5.10

FacetWP - Submit button: av FacetWP
LLC – 0.1

Flying Analytics by FlyingPress: av FlyingPress – 2.0.1
Flying Images: av WP Speed Matters – 2.4.14
Flying Scripts: av WP Speed Matters – 1.2.3
HUSKY - Products Filter Professional for WooCommerce: av realmag777 – 1.3.4.5
OxyPowerPack: av The OxyPowerPack team – 2.0.4
Regenerate Thumbnails: av Alex Mills (Viper007Bond) – 3.1.6
Site Kit by Google: av Google – 1.113.0
WooCommerce Blocks: av Automattic – 11.5.4
WooCommerce Google Product Feed: av Ademti Software Ltd. – 10.10.5 (en uppdatering till version 10.11.1 finns tillgänglig)
WordPress REST API Authentication: av miniOrange – 3.0.0
WP-Optimize - Clean, Compress, Cache: av David Anderson
Ruhani Rabin
Team Updraft – 3.2.21

WPlit Woo Conditions for Oxygen: av WPlit – 1.0.1
WP Mail SMTP: av WP Mail SMTP – 3.10.0
Yoast SEO: WooCommerce: av Team Yoast – 12.6.1
Yoast SEO Premium: av Team Yoast – 13.2

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Butikbas: #131 - /shop/
Varukorg: #133 - /kundvagn/
Kassan: ❌ Sidan innehåller inte kortkoden [woocommerce_checkout] eller blocket woocommerce/checkout.
Mitt konto: #132 - /konto/
Villkor: #174 - /allmanna-villkor/

### Theme ###

Name: twentytwenty
Version: (en uppdatering till version 2.4 finns tillgänglig)
Author URL: 
Child Theme: ❌ – Om du modifierar WooCommerce på ett modertema som du själv inte byggt
så rekommenderar vi att du använder ett barntema istället. Läs: Hur du skapar ett barntema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Swish Ecommerce ###

Swish Testmode: -
Merchant Swish number: 1236737167
Swish Technical Supplier: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-24 06:26:30 +01:00
Options: ✔
Notes: 14
Onboarding: completed

### Action Scheduler ###

Färdigbehandlad: 3 056
Oldest: 2023-10-23 15:52:36 +0200
Newest: 2023-11-23 14:21:22 +0100

Misslyckades: 12
Oldest: 2023-08-21 15:28:12 +0200
Newest: 2023-11-20 14:34:39 +0100

Väntar: 10
Oldest: 2023-11-23 18:19:22 +0100
Newest: 2023-11-28 14:42:17 +0100

### Status report information ###

Generated at: 2023-11-23 14:44:59 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment]
Hi @tobiasgardner! 👋

Thanks for reaching out. When dealing with variable products, _draft_ variations aren't displayed in the admin UI nor the frontend. We agree that the REST API should surface an error when attempting to do something that is not allowed.
We'd like to get some clarification on whether you have any need for draft variations or you just want to make sure validation here isn't as loose as it currently is.

**Comment by Sapera-SH** [comment]
Hi 
I have experience the same, or similar issue. 
Through the API i am creating products, attributes and the variants. 
the issue arises when i add attributes to my POST request in postman. 
in the following error i have replaced my domain with * and the ip with IP
The PHP error i get: 
`2023/12/05 14:48:00 [error] 4444#4444: *16078 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to a member function get_variation() on string in /www/*_720/public/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-product-variations-controller.php:314
Stack trace:
#0 /www/*_720/public/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php(163): WC_REST_Product_Variations_Controller->prepare_object_for_database(Object(WP_REST_Request), false)
#1 /www/*_720/public/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php(238): WC_REST_CRUD_Controller->save_object(Object(WP_REST_Request), false)
#2 /www/*_720/public/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-controller.php(269): WC_REST_CRUD_Controller->update_item(Object(WP_REST_Request))
#3 /www/*_720/public/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/cla" while reading response header from upstream, client: IP, server: stg-*-staging.kinsta.cloud, request: "POST /wp-json/wc/v3/products/4067/variations/batch HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.0-fpm-*.sock:", host: "stg-*-staging.kinsta.cloud:45651"`

**Comment by tobiasgardner** [comment]
Thanks for the answer @jorgeatorres!
I did not even reflect on DRAFT products, since it was an option that could be sent to the API.
Since it is not possible to use/set STATUS on variant level in the Woocommerce admin interface (have not looked for it earlier), I guess that I can do without that. It is enough for my usecase to set the parent product to DRAFT.
However, it would be good if the API spec should be updated and/or validation of data is extended to cover this type of cases. I have a feeling that there are more attributes in the Product Variation API that are not really used/triggered in the Woocommerce Admin today? Perhaps all of these should be removed and set to default values.

**Comment by tobiasgardner** [comment]
@Sapera-SH I think you need to complement your comment with the actual request that you are sending. I cannot see that this is really related to the same issue that I had, so perhaps you should open a separate ticket if it is something else.

**Comment by Sapera-SH** [comment]
Hi Tobias, 
it was the closes one i could find. 
but thanks for the comment and good luck with your issue.

**Comment by tobiasgardner** [comment]
I am not an expert on Woo, but I think that anyone that looks at your issue needs to know more :)

**Comment by barryhughes** [comment]
Thanks again, @tobiasgardner: just confirming that for now you are not blocked and are able to move ahead with your project/immediate goals?

**Comment by samrat-biswas-git** [comment]
Thanks @tobiasgardner — still valid on trunk. Creating a variation with status=draft via REST returns a 200 with the variation in the response, but draft variations aren't shown in the admin or frontend, so it silently creates a variation that effectively doesn't exist. The v3 variation controller accepts status and the schema advertises the full post-status enum, even though draft isn't actually supported for variations.

Marking ready for engineering, using the direction @jorgeatorres already agreed here (the API should surface an error rather than silently accept it):

- Validate variation status on create/update and reject unsupported values (e.g. draft) with a clear error, and narrow/document the schema to the statuses variations actually support.
- BC note: this changes a request that currently "succeeds" into an explicit error — but it's replacing a broken silent state, so worth a changelog note.
- Add a regression test: POST a variation with status=draft should return a validation error, not a hidden variation.

(For reference: #36713 is the GUI side of the same behavior. The attribute error @Sapera-SH mentioned above is unrelated and tracked separately under #43722.)
