### ISSUE TITLE
[Flaky] merchant/products/add-variable-product/update-variations.spec.js

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#41691]
can individually edit variations 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/6993173935

**Comment by lanej0** [comment]
can individually edit variations 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7010670676

**Comment by lanej0** [comment]
can bulk edit variations 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7011624761

```
4) [Chrome] › merchant/products/add-variable-product/update-variations.spec.js:335:2 › Update variations › can bulk edit variations › Click on the "Variations" tab. 

    Test timeout of 120000ms exceeded.

    Error: locator.click: Page closed
    =========================== logs ===========================
    waiting for getByRole('link', { name: 'Variations' })
    ============================================================

      341 |
      342 | 		await test.step( 'Click on the "Variations" tab.', async () => {
    > 343 | 			await page.getByRole( 'link', { name: 'Variations' } ).click();
          | 			                                                        ^
      344 | 		} );
      345 |
      346 | 		await test.step(

        at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/merchant/products/add-variable-product/update-variations.spec.js:343:60
        at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/merchant/products/add-variable-product/update-variations.spec.js:342:14
```

**Comment by lanej0** [comment]
can manage stock levels 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7017344351

```
5) [Chrome] › merchant/products/add-variable-product/update-variations.spec.js:407:2 › Update variations › can manage stock levels › Click on the "Variations" tab. 

    Test timeout of 120000ms exceeded.

    Error: locator.click: Page closed
    =========================== logs ===========================
    waiting for getByRole('link', { name: 'Variations' })
    ============================================================

      413 |
      414 | 		await test.step( 'Click on the "Variations" tab.', async () => {
    > 415 | 			await page.getByRole( 'link', { name: 'Variations' } ).click();
          | 			                                                        ^
      416 | 		} );
      417 |
      418 | 		await test.step( 'Expand all variations', async () => {

        at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/merchant/products/add-variable-product/update-variations.spec.js:415:60
        at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/merchant/products/add-variable-product/update-variations.spec.js:414:14
```

**Comment by lanej0** [comment]
can manage stock levels 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7017344351

**Comment by lanej0** [comment]
can remove a variation 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7032219082

**Comment by lanej0** [comment]
can remove a variation 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7035204228

```
4) [Chrome] › merchant/products/add-variable-product/update-variations.spec.js:587:2 › Update variations › can remove a variation › Click on the "Variations" tab. 

    Test timeout of 120000ms exceeded.

    Error: locator.click: Page closed
    =========================== logs ===========================
    waiting for getByRole('link', { name: 'Variations' })
    ============================================================

      593 |
      594 | 		await test.step( 'Click on the "Variations" tab.', async () => {
    > 595 | 			await page.getByRole( 'link', { name: 'Variations' } ).click();
          | 			                                                        ^
      596 | 		} );
      597 |
      598 | 		await test.step( 'Click "Remove" on a variation', async () => {

        at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/merchant/products/add-variable-product/update-variations.spec.js:595:60
        at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/merchant/products/add-variable-product/update-variations.spec.js:594:14
```

**Comment by lanej0** [comment]
can set variation defaults 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7045666309

```
3) [Chrome] › merchant/products/add-variable-product/update-variations.spec.js:523:2 › Update variations › can set variation defaults › Click on the "Variations" tab. 

    Test timeout of 120000ms exceeded.

    Error: locator.click: Page closed
    =========================== logs ===========================
    waiting for getByRole('link', { name: 'Variations' })
    ============================================================

      529 |
      530 | 		await test.step( 'Click on the "Variations" tab.', async () => {
    > 531 | 			await page.getByRole( 'link', { name: 'Variations' } ).click();
          | 			                                                        ^
      532 | 		} );
      533 |
      534 | 		await test.step( 'Wait for block overlay to disappear.', async () => {

        at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/merchant/products/add-variable-product/update-variations.spec.js:531:60
        at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/merchant/products/add-variable-product/update-variations.spec.js:530:14
```

**Comment by lanej0** [comment]
can bulk edit variations 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7049378402

Not a failure, interrupted

**Comment by lanej0** [comment]
can manage stock levels 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7053240110

**Comment by lanej0** [comment]
can individually edit variations 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7055730229

**Comment by lanej0** [comment]
can delete all variations 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7055897246

**Comment by lanej0** [comment]
can remove a variation 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7059212288

**Comment by lanej0** [comment]
can manage stock levels 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7063586761

**Comment by lanej0** [comment]
can manage stock levels 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7064494373

**Comment by lanej0** [comment]
can delete all variations 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7087507838

**Comment by lanej0** [comment]
can remove a variation 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7087507838

**Comment by lanej0** [comment]
can remove a variation 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7100033328

**Comment by lanej0** [comment]
can individually edit variations 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7101542441

**Comment by lanej0** [comment]
can remove a variation 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7108631123

**Comment by lanej0** [comment]
can set variation defaults 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7118001698

**Comment by lanej0** [comment]
can remove a variation 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7119414060

**Comment by lanej0** [comment]
can remove a variation 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7145373265

**Comment by lanej0** [comment]
can remove a variation 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7172282725

**Comment by lanej0** [comment]
can set variation defaults 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7174315016
