### ISSUE TITLE
[Flaky] admin-analytics/analytics-data.spec.js > Analytics-related tests › downloads revenue report as CSV

### ISSUE THREAD

**Issue by rodelgc** [woothemes/woocommerce#41734]
The following tests had become flaky since last Fri, Nov 24, 2023, and were momentarily skipped in https://github.com/woocommerce/woocommerce/pull/41700 to unblock other PR's:

`downloads revenue report as CSV`
`set custom date range on revenue report`

**Comment by lanej0** [comment]
The download report as CSV test appears to be having issues because occasionally, hitting the download will asynchronously process the download (it will notify you via email) instead of initiating an immediate download.  I think this happens once a certain threshold number of orders is received.

We could either:
- Make either outcome acceptable in the test: either an immediate download, or a message saying that you will be notified
- Increasing the number of orders during setup so that the report is ONLY processed async

**Comment by lanej0** [comment]
use advanced filters on orders report 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7049378402

**Comment by lanej0** [comment]
use date filter on revenue report 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7049378402

```
 Error: Timed out 20000ms waiting for expect(received).toBeVisible()
    Call log:
      - expect.toBeVisible with timeout 20000ms
      - waiting for getByRole('menuitem', { name: 'Returns $0.00 No change from Previous year:' })


      215 | 		await expect( page.getByText( 'Month to date' ).first() ).toBeVisible();
      216 | 		await expect( page.getByRole( 'menuitem', { name: 'Gross sales $1,229.30 No change from Previous year:' } ) ).toBeVisible();
    > 217 | 		await expect( page.getByRole( 'menuitem', { name: 'Returns $0.00 No change from Previous year:' } ) ).toBeVisible();
          | 		                                                                                                      ^
      218 | 		await expect( page.getByRole( 'menuitem', { name: 'Coupons $0.00 No change from Previous year:' } ) ).toBeVisible();
      219 | 		await expect( page.getByRole( 'menuitem', { name: 'Net sales $1,229.30 No change from Previous year:' } ) ).toBeVisible();
      220 | 		await expect( page.getByRole( 'menuitem', { name: 'Taxes $0.00 No change from Previous year:' } ) ).toBeVisible();

        at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/admin-analytics/analytics-data.spec.js:217:105
```

**Comment by lanej0** [comment]
use advanced filters on orders report 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7052102464

```
2) [Chrome] › admin-analytics/analytics-data.spec.js:269:2 › Analytics-related tests › use advanced filters on orders report 

    Error: Timed out 20000ms waiting for expect(locator).toBeVisible()

    Locator: getByRole('menuitem', { name: 'Net sales $1,229.30 No change from Previous year:' })
    Expected: visible
    Received: hidden
    Call log:
      - expect.toBeVisible with timeout 20000ms
      - waiting for getByRole('menuitem', { name: 'Net sales $1,229.30 No change from Previous year:' })


      272 | 		// no filters applied
      273 | 		await expect( page.getByRole( 'menuitem', { name: 'Orders 10 No change from Previous year:' } ) ).toBeVisible();
    > 274 | 		await expect( page.getByRole( 'menuitem', { name: 'Net sales $1,229.30 No change from Previous year:' } ) ).toBeVisible();
          | 		                                                                                                            ^
      275 | 		await expect( page.getByRole( 'menuitem', { name: 'Average order value $122.93 No change from Previous year:' } ) ).toBeVisible();
      276 | 		await expect( page.getByRole( 'menuitem', { name: 'Average items per order 11 No change from Previous year:' } ) ).toBeVisible();
      277 |

        at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/admin-analytics/analytics-data.spec.js:274:111
```

**Comment by lanej0** [comment]
use date filter on revenue report 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7052102464

```
 1) [Chrome] › admin-analytics/analytics-data.spec.js:211:2 › Analytics-related tests › use date filter on revenue report 

    Test timeout of 120000ms exceeded.

    Error: locator.click: Test timeout of 120000ms exceeded.
    Call log:
      - waiting for getByText('Last month')
      -   locator resolved to <span class="woocommerce-segmented-selection__label">Last month</span>
      - attempting click action
      -   waiting for element to be visible, enabled and stable
      -   element is visible, enabled and stable
      -   scrolling into view if needed
      -   done scrolling
      -   <div class="woocommerce-tour-kit-step-navigation">…</div> from <div class="tour-kit woocommerce-tour-kit">…</div> subtree intercepts pointer events

   224 | 		// click the date filter and change to Last month (should be no sales/orders)
      225 | 		await page.getByRole( 'button', { name: 'Month to date' } ).click();
    > 226 | 		await page.getByText( 'Last month' ).click();
          | 		                                     ^
      227 | 		await page.getByRole( 'button', { name: 'Update' } ).click();
      228 | 		await expect( page.getByRole( 'menuitem', { name: 'Gross sales $0.00 No change from Previous year:' } ) ).toBeVisible();
      229 | 		await expect( page.getByRole( 'menuitem', { name: 'Returns $0.00 No change from Previous year:' } ) ).toBeVisible();

        at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/admin-analytics/analytics-data.spec.js:226:40
```

**Comment by lanej0** [comment]
confirms correct summary numbers on overview page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7154377208

**Comment by lanej0** [comment]
confirms correct summary numbers on overview page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7155682453

**Comment by lanej0** [comment]
confirms correct summary numbers on overview page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7155738174

**Comment by lanej0** [comment]
confirms correct summary numbers on overview page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7155827896

**Comment by lanej0** [comment]
confirms correct summary numbers on overview page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7155925958

**Comment by lanej0** [comment]
use date filter on revenue report 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7173089583

**Comment by lanej0** [comment]
use date filter on revenue report 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7179558257
