### ISSUE TITLE
E2E: the environment isn't accessible after provisioning occasionally

### ISSUE THREAD

**Issue by dinhtungdu** [woothemes/woocommerce#42182]
## Describe the bug

Occasionally, when the Playwright global setup script is executed, the environment isn't ready, which breaks the workflow.

```
> @woocommerce/block-library@11.4.0-dev test:e2e
> sh ./bin/check-env.sh && npx playwright test --config=tests/e2e/playwright.config.ts "--config=tests/e2e/playwright.side-effects.config.ts"

Error: Error: Failed to discover REST API endpoint.
 Link header: undefined

   at ../global-setup.ts:[14](https://github.com/woocommerce/woocommerce-blocks/actions/runs/6511725871/job/17687960916#step:14:15)3

  141 | 	} );
  142 |
> 143 | 	await requestUtils.setupRest();
      | 	^
  144 | 	await requestContext.dispose();
  145 |
  146 | 	await prepareAttributes( config );

    at getAPIRootURL (/home/runner/work/woocommerce-blocks/woocommerce-blocks/node_modules/@wordpress/e2e-test-utils-playwright/src/request-utils/rest.ts:32:9)
    at RequestUtils.setupRest (/home/runner/work/woocommerce-blocks/woocommerce-blocks/node_modules/@wordpress/e2e-test-utils-playwright/src/request-utils/rest.ts:42:29)
    at globalSetup (/home/runner/work/woocommerce-blocks/woocommerce-blocks/tests/e2e/global-setup.ts:143:2)
```

See https://github.com/woocommerce/woocommerce-blocks/actions/runs/6511725871/job/17687960916

**Comment by WunderBart** [comment]
This issue should be resolved after the recent refactors to our E2E setup. @dinhtungdu, can you confirm?

**Comment by dinhtungdu** [comment]
@WunderBart yep, thanks for the head-up! I can confirm this is no longer reproducible. Closing.
