### ISSUE TITLE
Defensive coding around use of `$product->get_attributes()`

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#43722]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We were recently made aware of a large number of fatal errors as follows:

```
PHP Fatal error:  Uncaught Error: Call to a member function get_variation() on string in /woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:1100

Stack trace:

#0 /woocommerce/includes/class-wc-data-store.php(224): WC_Product_Data_Store_CPT->find_matching_product_variation(Object(WC_Product_Variation), Array)
#1 /woocommerce/includes/class-wc-ajax.php(530): WC_Data_Store->__call('find_matching_p...', Array)
#2 /wp-includes/class-wp-hook.php(324): WC_AJAX::get_variation('')
#3 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /woocommerce/includes/class-wc-ajax.php(96): do_action('wc_ajax_get_var...')
#6 /wp-includes/class-wp-hook.php(324): WC_AJAX::do_wc_ajax('')
#7 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(false, Array)
#8 /wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /wp-includes/template-loader.php(13): do_action('template_redire...')
#10 /wp-blog-header.php(19): require_once('/wordpress/core...')
#11 /index.php(17): require('/wordpress/core...')
#12 {main}
  thrown in /woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php on line 1100
```

We cannot replicate, but the problem is we expect an array of `WC_Product_Attributes` [over here](https://github.com/woocommerce/woocommerce/blob/8.5.1/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L1107) but are apparently receiving an array with one or more strings. One possible reason is that data properties are filterable, so a 'rogue plugin' could be the culprit. 

This seems like something we can guard against (and log) with some defensive coding. Something very similar may also be happening in the [REST API code](https://github.com/woocommerce/woocommerce/issues/41661#issuecomment-1844667931).

### Expected behavior

If filter callbacks (in this case, filtering the array of product attributes) change the return type to something unexpected, the app should handle things gracefully and without fatal errors.

### Actual behavior

Fatal error occurs.

### Steps to reproduce

We don't have steps to reproduce (though we could contrive things and approximate the same error, we don't know for sure what the actual real-world conditions behind the fatal errors are).

### WordPress Environment

Reports came in in relation to 8.4.0, but it seems possible it could happen with any recent release.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
I have a PR addressing parts of this here: #43739. As noted in the review it still needs manual reproduction / testing steps. 

As for the REST API issue: [this line here](https://github.com/woocommerce/woocommerce/blob/824dc6be5107d7a68d6300bd903cefbf52b88b5a/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-product-variations-controller.php#L314) might benefit from a check for `! is_a( $parent_attributes[ $attribute_name ], 'WC_Product_Attribute' )`. I have not come up with a way to provoke the issue in a unit test yet, but wanted to quickly capture the idea here.

**Comment by jamesckemp** [comment]
Reviewed and confirmed this is still valid. Marking as ready for engineering.

Current evidence: Current trunk still assumes product attribute arrays contain WC_Product_Attribute objects in several variation-matching paths without defensive instanceof checks. The reported fatal remains plausible on trunk if filters or malformed data inject strings.
