### ISSUE TITLE
Error on plugin screen when Beta Tester installed and WooCommerce is updated via plugin upload

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#44373]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

1. Create a site with `8.4.0` 
2. Install the WC Beta Tester plugin
3. Activate both plugins
4. Go to the plugins screen
5. Upload a newer version of WooCommerce (eg. 8.5.1)
6. Click `Replace with current uploaded`
7. The following appears on screen:

`Error on this website. Please check your site admin email inbox for instructions.`

8. See error in site email after completing upgrade steps (Note I only received an email for the first test of this),

### Expected behavior

No error should occur

### Actual behavior

The following appears on screen:

`Error on this website. Please check your site admin email inbox for instructions.`

See the following error in site email after completing upgrade steps:

```
Error Details
=============
An error of type E_ERROR was caused in line 20 of the file /srv/htdocs/wp-content/plugins/woocommerce/includes/wccom-site/rest-api/endpoints/class-wc-rest-wccom-site-installer-controller.php. Error message: Uncaught Error: Class "WC_REST_WCCOM_Site_Controller" not found in /srv/htdocs/wp-content/plugins/woocommerce/includes/wccom-site/rest-api/endpoints/class-wc-rest-wccom-site-installer-controller.php:20
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php(224): require_once()
#1 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): WC_WCCOM_Site::register_rest_namespace(Array)
#2 /srv/htdocs/__wp__/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#3 /srv/htdocs/wp-content/plugins/woocommerce/includes/rest-api/Server.php(60): apply_filters('woocommerce_res...', Array)
#4 /srv/htdocs/wp-content/plugins/woocommerce/includes/rest-api/Server.php(40): Automattic\WooCommerce\RestApi\Server->get_rest_namespaces()
#5 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\RestApi\Server->register_rest_routes(Object(WP_REST_Server))
#6 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /srv/htdocs/__wp__/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /srv/htdocs/__wp__/wp-includes/rest-api.php(593): do_action('rest_api_init', Object(WP_REST_Server))
#9 /srv/htdocs/__wp__/wp-includes/rest-api.php(551): rest_get_server()
#10 /srv/htdocs/__wp__/wp-includes/rest-api.php(2918): rest_do_request(Object(WP_REST_Request))
#11 [internal function]: rest_preload_api_request(Array, '/wc-analytics/r...')
#12 /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Admin/Settings.php(145): array_reduce(Array, 'rest_preload_ap...')
#13 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\Admin\Settings->add_component_settings(Array)
#14 /srv/htdocs/__wp__/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#15 /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Admin/WCAdminSharedSettings.php(61): apply_filters('woocommerce_adm...', Array)
#16 /srv/htdocs/wp-content/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php(268): Automattic\WooCommerce\Internal\Admin\WCAdminSharedSettings->Automattic\WooCommerce\Internal\Admin\{closure}()
#17 /srv/htdocs/wp-content/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php(393): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->execute_lazy_data()
#18 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->enqueue_asset_data('')
#19 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#20 /srv/htdocs/__wp__/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#21 /srv/htdocs/__wp__/wp-admin/admin-footer.php(95): do_action('admin_print_foo...')
#22 /srv/htdocs/__wp__/wp-admin/update.php(186): require_once('/srv/htdocs/__w...')
#23 {main}
  thrown
```

### Steps to reproduce

1. Create a site with `8.4.0` 
2. Install the WC Beta Tester plugin
3. Activate both plugins
4. Go to the plugins screen
5. Upload a newer version of WooCommerce (eg. 8.5.1)
6. Click `Replace with current uploaded`
7. The following appears on screen:

`Error on this website. Please check your site admin email inbox for instructions.`

8. See error in site email after completing upgrade steps (Note I only received an email for the first test of this),

### WordPress Environment ###

Fresh default WP 6.4.3 with only the plugins described in the steps to reproduce.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
I added `8.6 Beta` to the issue title and description since the issue happens there as well.

**Comment by tammullen** [comment]
Maybe related to changes in https://github.com/woocommerce/woocommerce/pull/37893 ?

**Comment by rrennick** [comment]
I have edited the issue title and description to better describe the issue. 

As an interim work around, deactivating the WC beta tester before uploading the WC zip eliminates the issue.

**Comment by rodelgc** [comment]
thank you for updating the details @rrennick. BTW the error happens when updating from WC 8.5.2 to WC 8.6 Beta or any of the 8.6.0.x versions.

I do see a different kind of error when updating from WC 8.4 to WC 8.5.2 though: 
> CRITICAL Uncaught Error: Failed opening required '/srv/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Shipping/PickupLocation.php' (include_path='/:.') in /srv/htdocs/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php:90

**Comment by rrennick** [comment]
@rodelgc Thanks for the followup. The issue is related to files / classes not existing. In the case of the 8.6.0 the source file for `WC_REST_WCCOM_Site_Controller` is required in the line previous to the line that triggers the error. I verified that the file exists in the zip.

The beta tester plugin is initializing the REST API during the plugin replacement. We need to prevent it from doing that.

**Comment by samrat-biswas-git** [comment]
Hi @nigeljamesstevenson - thanks for such a detailed report, it's really helpful.

I know this has been open for a long time, and I appreciate your patience. We're currently going through some older WooCommerce issues, identifying what still needs fixing, and tidying up what's already fixed or out of scope.

I'd like to get an engineer's eyes on this before we make a call, so I've flagged it for developer feedback. Someone will take a proper look at the repro steps and how it's behaving now.

The bit that needs a closer look: Because the reported failure is tied to the separate Beta Tester plugin, this does not belong in core issue execution against this repository.
