### ISSUE TITLE
PHP fatal when using calculate_total() on order that has an empty fee value

### ISSUE THREAD

**Issue by tbradsha** [woothemes/woocommerce#44859]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If an order has a fee with a blank value, and one calls `calculate_totals()` on said order, one gets a PHP fatal, as it's trying to add a float (or int) and an empty string.

Note that I've run across this issue in two other sites in the wild as well.

### Expected behavior

A blank string should be treated as 0 for calculation purposes, allowing the calculation to proceed.

### Actual behavior

```
[21-Feb-2024 17:04:28 UTC] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: float * string in /wp-content/plugins/woocommerce/includes/class-wc-order-item-fee.php:93
Stack trace:
#0 /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(1760): WC_Order_Item_Fee->calculate_taxes(Array)
#1 /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(1922): WC_Abstract_Order->calculate_taxes()
#2 /wp-content/mu-plugins/sandbox.php(10): WC_Abstract_Order->calculate_totals()
#3 /wp-includes/class-wp-hook.php(324): test('')
#4 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#5 /wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wp-settings.php(643): do_action('init')
#7 /wp-config.php(87): require_once('/Users/tmb/loca...')
#8 /wp-load.php(50): require_once('/Users/tmb/loca...')
#9 /wp-blog-header.php(13): require_once('/Users/tmb/loca...')
#10 /index.php(17): require('/Users/tmb/loca...')
#11 {main}
  thrown in /wp-content/plugins/woocommerce/includes/class-wc-order-item-fee.php on line 93
```

### Steps to reproduce

There are two issues here:
1. We allow fee values to be stored as an empty string. They should probably be stored as `0` when sanitizing input. This is probably why similar errors keep cropping up (#38009, #37681, #42271, #36761...)
2. We don't ensure values are numerical prior to performing operations on them. I prefer explicit checks for empty strings; casting would also work, but can make it harder to troubleshoot future bugs.

The easiest way to reproduce the errant state:
1. Enable taxes and add a standard rate.
2. Create an order with a fee and save.
3. Edit the fee and delete the fee value (don't put 0 as the value, but delete the value so that the 0 placeholder shows).
4. Save the order.

At this point, the fee value is stored in the database as a blank fee, and it's simple to trigger the PHP fatal with the following:

```
$order = wc_get_order( $order_id );
$order->calculate_totals();
```

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://norubbish.local
Site address (URL): http://norubbish.local
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.2.10
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 256.76MB
Database Data Size: 233.53MB
Database Index Size: 23.23MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 3.02MB + Index: 8.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.03MB + Index: 3.03MB + Engine InnoDB
wp_aioseo_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.16MB + Index: 0.28MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_comments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_donationmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_donormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_donors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_formmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_give_migrations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_revenue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sequential_ordering: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_give_subscriptionmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_subscriptions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.36MB + Index: 1.11MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mbe_shipping_standard_package_product: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mbe_shipping_standard_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mbeshippingrate: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 206.03MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.22MB + Index: 0.17MB + Engine InnoDB
wp_posts: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
wp_sm_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 2.52MB + Index: 3.02MB + Engine InnoDB
wp_users: Data: 0.38MB + Index: 0.38MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_automation_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_canned_replies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_companies: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_contacts: Data: 1.50MB + Index: 0.34MB + Engine InnoDB
wp_zbs_customfields: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_events: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_zbs_externalsources: Data: 0.20MB + Index: 0.20MB + Engine InnoDB
wp_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_invoices: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_zbs_lineitems: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_zbs_logs: Data: 3.52MB + Index: 0.59MB + Engine InnoDB
wp_zbs_mail: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_zbs_mail_campaign_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zbs_mail_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_mail_links: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_zbs_mail_sequences: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_mail_sequences_steps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_mail_stats: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
wp_zbs_mail_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_meta: Data: 0.34MB + Index: 0.17MB + Engine InnoDB
wp_zbs_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_object_links: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_zbs_product_index: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_quotes: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_zbs_quotes_templates: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_zbs_scheduled_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_settings: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_zbs_sys_cronmanagerlogs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email_hist: Data: 1.52MB + Index: 0.14MB + Engine InnoDB
wp_zbs_tags: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tags_links: Data: 0.25MB + Index: 0.33MB + Engine InnoDB
wp_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_transactions: Data: 0.27MB + Index: 0.31MB + Engine InnoDB
wp_zbs_twilio_numbers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_workflows: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbscrm_api_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 12
custom_css: 1
feedback: 55
give_forms: 1
give_payment: 1
mailpoet_page: 1
page: 26
post: 2
postman_sent_mail: 4
product: 6
product_variation: 9
revision: 28
shop_order: 38
shop_order_refund: 2
shop_subscription: 2
wp_global_styles: 6
wp_navigation: 1
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.6.1

### Must Use Plugins (1) ###

sandbox.php: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #11 - /shop/
Cart: #12 - /cart/
Checkout: #13 - /checkout/
My account: #14 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: test_theme
Version: 1.0.0
Author URL: http://underscores.me/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: http://norubbish.local
Subscriptions-core Library Version: 6.8.0
Subscription Statuses: auto-draft: 1
wc-pending: 1

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Payment Gateway Support ###

Cash on delivery: products

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-21 19:55:26 -12:00
Options: ✔
Notes: 164
Onboarding: completed

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: http://norubbish.local?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Canceled: 1
Oldest: 2024-02-21 10:00:56 +0000
Newest: 2024-02-21 10:00:56 +0000

Complete: 10,800
Oldest: 2024-01-21 21:34:27 +0000
Newest: 2024-02-21 17:30:53 +0000

Failed: 31
Oldest: 2022-10-26 14:49:45 +0000
Newest: 2023-10-24 19:30:34 +0000

Pending: 2
Oldest: 2024-02-21 17:32:53 +0000
Newest: 2024-02-21 17:58:36 +0000

### Status report information ###

Generated at: 2024-02-21 05:32:38 -12:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kaushikasomaiya** [comment]
Seen in 9400790-zen

**Comment by tyxla** [comment]
PR for this: https://github.com/woocommerce/woocommerce/pull/66231. 

I've worked from the prior community contribution in https://github.com/woocommerce/woocommerce/pull/48130.
