### ISSUE TITLE
Payment Fields Missing with Woocommerce Payments

### ISSUE THREAD

**Issue by AndyMeps** [woothemes/woocommerce#45165]
## Describe the bug
Hi, our site has been working fine with Storefront for over a year, but with a recent Woocommerce Payments update, the card details no longer load. Woocommerce Payments and the Twenty TwentyFour theme works fine, Storefront and Woocommerce Payments disabled works fine.

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. Go to http://staging.thedotingdogcompany.co.uk/product/the-tougher-box-monthly-subscription/
2. Click on any dog size from the dropdown
3. Click on any subscription length
4. The "Sign-up Now" button is currently not displaying properly (Not sure where the CSS for that is coming from, I've remove all custom CSS from the theme)
5. You will be taken to the Checkout page, scroll down to the "credit card / debit card" section
6. The card form is missing.
7. Open Dev Tools and refresh page, note error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'defaults')`

> Note: Everything works fine with simple products (not sure why it would behave differently with subscription products), so if you think this is something I should raise with Woocommerce Payments instead, I will.

## Screenshots
<img width="571" alt="Screenshot 2024-02-25 at 14 19 14" src="https://github.com/woocommerce/storefront/assets/1610289/7bb9ec9b-5173-4422-9aa9-107d964f9a05">

## Expected behavior
Card form should be available.

### Browser Environment
Please provide as much detail as possible about your testing environment.

- Platform: macOS
- Browser(s): Chrome

Reported on various browsers.

### WordPress Environment
The URL provided is from a staging environment, I've been able to hotfix in production by commenting out some code relating to jquery-blockui in [checkout.min.js (see commented out sections of JS)](https://thedotingdogcompany.co.uk/wp-content/plugins/woocommerce/assets/js/frontend/checkout.min.js)

<details>
```
### WordPress Environment ###

WordPress address (URL): http://staging.thedotingdogcompany.co.uk
Site address (URL): http://staging.thedotingdogcompany.co.uk
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 5 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Ubuntu)
PHP Version: 8.0.28
PHP Post Max Size: 5 GB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.32
Max Upload Size: 5 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Total Database Size: 148.46MB
Database Data Size: 98.61MB
Database Index Size: 49.85MB
wp_woocommerce_sessions: Data: 5.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 17.55MB + Index: 7.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 5.11MB + Index: 2.55MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.09MB + Index: 3.08MB + Engine InnoDB
wp_aioseo_cache: Data: 0.22MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.22MB + Index: 0.02MB + Engine InnoDB
wp_atum_export_templates: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_product_data: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 5.52MB + Index: 3.41MB + Engine InnoDB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.13MB + Index: 0.31MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.25MB + Index: 0.20MB + Engine InnoDB
wp_postmeta: Data: 26.56MB + Index: 22.02MB + Engine InnoDB
wp_posts: Data: 13.52MB + Index: 2.41MB + Engine InnoDB
wp_term_relationships: Data: 0.31MB + Index: 0.23MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 2.52MB + Index: 3.00MB + Engine InnoDB
wp_users: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 0.81MB + Engine InnoDB
wp_wc_order_stats: Data: 0.36MB + Index: 0.30MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.19MB + Index: 0.38MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wfpklist_template_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_sc_coupon_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 1.50MB + Index: 0.41MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.17MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.11MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 1965
custom_css: 1
customize_changeset: 1
feedback: 3213
mailpoet_page: 1
nav_menu_item: 9
oembed_cache: 1
page: 19
popup: 3
popup_theme: 8
post: 2
product: 1316
product_variation: 280
revision: 430
shop_coupon: 317
shop_order: 3377
shop_order_refund: 58
shop_subscription: 143
wp_global_styles: 1
wp_navigation: 1
wp_template: 2
wpforms: 1
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooPayments: by Automattic – 7.2.0
Woo Subscriptions: by WooCommerce – 6.0.0
WooCommerce: by Automattic – 8.6.1

### Inactive Plugins (29) ###

Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.5
Advanced Product Fields for WooCommerce: by StudioWombat – 1.6.6
All-in-One WP Migration: by ServMask – 7.80
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.9.36.2
Category Discount Woocommerce: by QuanticEdge – 4.7
Checkout Field Editor for WooCommerce: by ThemeHigh – 2.0.0
Duplicator: by Duplicator – 1.5.4
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.24.0
Google Listings and Ads: by WooCommerce – 2.4.5
Jetpack: by Automattic – 12.3
Login Logo: by Mark Jaquith – 0.10.2
Mailchimp for WooCommerce: by Mailchimp – 3.5
Minimum Periods for WooCommerce Subscriptions: by WPExtend – 2.5
NextMove Lite - Thank You Page for WooCommerce: by XLPlugins – 2.17.0
OptinMonster: by OptinMonster Popup Builder Team – 2.13.2
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.4
Pinterest for WooCommerce: by WooCommerce – 1.2.21 (update to version 1.3.22 is available)
Popup Maker: by Popup Maker – 1.18.1
Smart Coupons For WooCommerce Coupons: by WebToffee – 1.4.6
Sold Out Badge for WooCommerce: by Charlie Etienne – 4.3.6
Trustpilot-reviews: by Trustpilot – 2.5.914
WooCommerce PDF Invoices, Packing Slips, Delivery Notes and Shipping Labels: by WebToffee – 4.0.9
WooCommerce Shipping & Tax: by WooCommerce – 2.4.2 (update to version 2.5.1 is available)
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.7.0
WP fail2ban: by Charles Lecklider – 5.1.1
WPForms Lite: by WPForms – 1.8.1.3
WP Mail SMTP: by WP Mail SMTP – 3.8.0
Yoast SEO: by Team Yoast – 20.8
Yoast Test Helper: by Team Yoast – 1.17

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: woocommerce/storefront#6 - /products/
Basket: woocommerce/storefront#7 - /cart/
Checkout: woocommerce/storefront#8 - /checkout/
My account: woocommerce/storefront#9 - /my-account/
Terms and conditions: woocommerce/storefront#1176 - /terms-and-conditions/

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.2.0
Connected to WPCOM: Yes
WPCOM Blog ID: 205564084
Account ID: acct_1L5alc2E9oi6KVtb
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Enabled
Logging: Disabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
Subscriptions Live URL: http://thedotingdogcompany.co.uk
Subscriptions-core Library Version: 6.8.0
Subscription Statuses: wc-active: 46
wc-pending-cancel: 2
wc-on-hold: 1
wc-cancelled: 94

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United Kingdom (UK)

### Subscriptions by Payment Gateway ###

WooPayments: wc-active: 46
wc-cancelled: 94
wc-on-hold: 1
wc-pending-cancel: 2


### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Cash on delivery: products

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-25 18:10:26 +00:00
Options: ✔
Notes: 186
Onboarding: completed

### Action Scheduler ###

Canceled: 154
Oldest: 2024-01-26 16:08:43 +0000
Newest: 2024-02-24 23:02:03 +0000

Complete: 5,998
Oldest: 2024-01-25 14:34:35 +0000
Newest: 2024-02-25 14:00:09 +0000

Failed: 968
Oldest: 2022-06-03 19:08:20 +0100
Newest: 2024-02-25 14:26:49 +0000

Pending: 60
Oldest: 2024-02-25 14:28:24 +0000
Newest: 2024-03-22 21:24:13 +0000


### Status report information ###

Generated at: 2024-02-25 14:27:07 +00:00
```
</details>

**Comment by wavvves** [comment]
Hello @AndyMeps, thank you for reaching out.

Looking at the error stack trace, it seems that MailChimp scripts may be related, but your environment details state that this extension is disabled. 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'defaults')
    at HTMLDocument.<anonymous> (checkout.min.js?ver=8.6.1:1:81)
    at f (mc-validate.js:1:18278)
    at Object.fireWith [as resolveWith] (mc-validate.js:1:19064)
    at Function.ready (mc-validate.js:1:13874)
    at HTMLDocument.xt (mc-validate.js:1:11367)
```

Can you please confirm this without loading any MailChimp assets? What does the error stack trace look like without it?

Also, I see that both on staging and production, there is another MailChimp-related error output:
`Uncaught SyntaxError: Unexpected token ',' (at checkout/:1067:242)`

**Comment by AndyMeps** [comment]
Thanks @wavvves - you're absolutely right. The Mailchimp embed code was causing the issue, fixing the error thrown by the embed code has fixed the payment form. Happy for this issue to be closed.
