### ISSUE TITLE
PHP Fatal with the Germanized extension installed

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#45174]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

PHP Fatal error when WooCommerce is installed along with [the Germanized extension](https://vendidero.de/woocommerce-germanized)

```
PHP Fatal error:  Uncaught Exception: The LegacyProxy class is not intended for getting instances of classes in the src directory, please use init method injection or the instance of Automattic\WooCommerce\Vendor\Psr\Container\ContainerInterface for that. in /wordpress/plugins/woocommerce-accelerated-frequency/8.7.0.20/src/Proxies/LegacyProxy.php:38
Stack trace:
#0 /wordpress/plugins/woocommerce-accelerated-frequency/8.7.0.20/includes/rest-api/Server.php(48): Automattic\WooCommerce\Proxies\LegacyProxy->get_instance_of('Vendidero\\Germa...')
#1 /wordpress/core/6.4.3/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\RestApi\Server->register_rest_routes(Object(WP_REST_Server))
#2 /wordpress/core/6.4.3/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/core/6.4.3/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/core/6.4.3/wp-includes/rest-api.php(593): do_action('rest_api_init', Object(WP_REST_Server))
#5 /wordpress/plugins/woocommerce-accelerated-frequency/8.7.0.20/src/Blocks/BlockTypes/AbstractBlock.php(466): rest_get_server()
#6 /wordpress/plugins/woocommerce-accelerated-frequency/8.7.0.20/src/Blocks/BlockTypes/AbstractBlock.php(444): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->get_routes_from_namespace('wc/store/v1')
#7 /wordpress/plugins/woocommerce-accelerated-frequency/8.7.0.20/src/Blocks/BlockTypes/AbstractProductGrid.php(697): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_data(Array)
#8 /wordpress/plugins/woocommerce-accelerated-frequency/8.7.0.20/src/Blocks/BlockTypes/AbstractBlock.php(415): Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->enqueue_data(Array)
#9 /wordpress/plugins/woocommerce-accelerated-frequency/8.7.0.20/src/Blocks/BlockTypes/AbstractBlock.php(95): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_assets(Array, '', Object(WP_Block))
#10 /wordpress/core/6.4.3/wp-includes/class-wp-block.php(258): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback(Array, '', Object(WP_Block))
#11 /wordpress/core/6.4.3/wp-includes/blocks.php(1484): WP_Block->render()
#12 /wordpress/core/6.4.3/wp-includes/blocks.php(1522): render_block(Array)
#13 /wordpress/core/6.4.3/wp-includes/class-wp-hook.php(324): do_blocks('<!-- wp:paragra...')
#14 /wordpress/core/6.4.3/wp-includes/plugin.php(205): WP_Hook->apply_filters('<!-- wp:paragra...', Array)
#15 /wordpress/core/6.4.3/wp-includes/post-template.php(256): apply_filters('the_content', '<!-- wp:paragra...')
#16 /srv/htdocs/wp-content/themes/barberry/template-parts/content-page.php(6): the_content('Continue readin...')
#17 /wordpress/core/6.4.3/wp-includes/template.php(792): require('/srv/htdocs/wp-...')
#18 /wordpress/core/6.4.3/wp-includes/template.php(725): load_template('/srv/htdocs/wp-...', false, Array)
#19 /wordpress/core/6.4.3/wp-includes/general-template.php(206): locate_template(Array, true, false, Array)
#20 /srv/htdocs/wp-content/themes/barberry/page.php(22): get_template_part('template-parts/...', 'page')
#21 /wordpress/core/6.4.3/wp-includes/template-loader.php(106): include('/srv/htdocs/wp-...')
#22 /wordpress/core/6.4.3/wp-blog-header.php(19): require_once('/wordpress/core...')
#23 /wordpress/core/6.4.3/index.php(17): require('/wordpress/core...')
#24 {main}
  thrown in /wordpress/plugins/woocommerce-accelerated-frequency/8.7.0.20/src/Proxies/LegacyProxy.php on line 38
```

### Expected behavior

No PHP Fatal

### Actual behavior

Fatal is encountered

### Steps to reproduce

Install WooCommerce 8.7 Beta 1 along with [the Germanized extension](https://vendidero.de/woocommerce-germanized)

### WordPress Environment

WooCommerce 8.7 Beta

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Fix is being tracked here: https://github.com/woocommerce/woocommerce/pull/45178

**Comment by lanej0** [comment]
Looks like the linked PR was merged, so going to close this as complete.
