### ISSUE TITLE
Fatal Error in Bulk Sale Price Adjustments for Variable Products When Sale Price is Missing

### ISSUE THREAD

**Issue by thisissandip** [woothemes/woocommerce#47943]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Performing bulk actions to increase or decrease sale prices in the "Variations" tab of a Variable Product leads to a fatal error if the sale price does not exist.

### Expected behavior

Performing bulk actions to increase or decrease sale prices in the "Variations" tab of a Variable Product should not lead to a fatal error and if the sale price does not exist, the option should not be there, instead, only the "set sale price" option should be present.

### Actual behavior

increasing or decreasing using bulk actions of in the "Variations" tab leads to a fatal error if the sale price does not exist and the prices are not updated.

### Steps to reproduce

1. Create a variable product with a few variations
2. Go to the Variations Tab
3. Select "Decrease sales price by (fixed amount or percentage)"
4. Enter a percentage value like "10%"
5. See the prices are not updated
6. Go to WooCommerce > Status > Logs and check the recent fatal error

Error:

```
2024-05-29T10:16:19+00:00 Critical Uncaught TypeError: Unsupported operand types: string / int in /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php:2808  
Additional context
{
    "error": {
        "type": 1,
        "file": "\/srv\/htdocs\/wp-content\/plugins\/woocommerce\/includes\/class-wc-ajax.php",
        "line": 2808
    },
    "backtrace": [
        "",
        "#0 \/srv\/htdocs\/wp-content\/plugins\/woocommerce\/includes\/class-wc-ajax.php(2788): WC_AJAX::variation_bulk_adjust_price(Array, 'sale_price', '-', '20%')",
        "#1 \/srv\/htdocs\/wp-content\/plugins\/woocommerce\/includes\/class-wc-ajax.php(2902): WC_AJAX::variation_bulk_action_variable_sale_price_decrease(Array, Array)",
        "#2 \/srv\/htdocs\/__wp__\/wp-includes\/class-wp-hook.php(324): WC_AJAX::bulk_edit_variations('')",
        "#3 \/srv\/htdocs\/__wp__\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)",
        "#4 \/srv\/htdocs\/__wp__\/wp-includes\/plugin.php(517): WP_Hook->do_action(Array)",
        "#5 \/srv\/htdocs\/__wp__\/wp-admin\/admin-ajax.php(192): do_action('wp_ajax_woocomm...')",
        "#6 {main}",
        "thrown"
    ]
}
```

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://bagpipes-of-larks.jurassic.ninja
Site address (URL): https://bagpipes-of-larks.jurassic.ninja
WC Version: 8.9.1
REST API Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.28
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.17-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.1
WC Database Prefix: wp_
Total Database Size: 3.18MB
Database Data Size: 1.43MB
Database Index Size: 1.75MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 30
page: 7
post: 1
product: 20
product_variation: 15
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Jetpack: by Automattic – 13.5-a.1
WooCommerce: by Automattic – 8.9.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 KB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-29 14:29:47 +00:00
Options: ✔
Notes: 61
Onboarding: skipped

### Action Scheduler ###

Complete: 89
Oldest: 2024-05-27 14:30:07 +0000
Newest: 2024-05-29 10:28:47 +0000

Failed: 2
Oldest: 2024-05-27 14:33:01 +0000
Newest: 2024-05-27 14:33:01 +0000

Pending: 2
Oldest: 2024-05-29 22:09:13 +0000
Newest: 2024-05-30 10:09:13 +0000

### Status report information ###

Generated at: 2024-05-29 10:46:16 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by hideandgeek404** [comment]
This has been raised again at 8985024-zen

I have looked into the code a little and it seems that this is due to the `get_sale_price()` function, which in turn is using `get_prop()` is returning a string value (`""`) if the `_sale_price` postmeta does not exist for a variation. This then creates a logic problem as the `variation_bulk_adjust_price()` function then tries to add the discount value, which is an integer with either a percentage sign or not, to a blank string. 

Previously, in PHP 7.4, I believe this might have been a warning, not a fatal. But with TypeError becoming so prominent in PHP 8+, it now presents as a fatal.

I think we need to decide upon what logic this function should follow to best create a solution for it. 

1. Should the `variation_bulk_adjust_price()` function have logic to ignore any variation that returns either a blank string, `NULL` or `0` and therefore only affect any variation that _already has_ a sale price?
2. Should the `variation_bulk_adjust_price()` function have logic to convert a blank string or `NULL` to a 0 and apply the discount regardless of whether the variation has a sale price already?

Personally, I would say that 1 makes more sense because in the scenario that I wish to have all the green variations of a product on sale, but not the black variations, I wouldn't want the bulk `Decrease sale prices` action to add a sale price to a variation that wasn't on sale (didn't have an existing sale price)

**Comment by gigitux** [comment]
Fixed with https://github.com/woocommerce/woocommerce/pull/54202
