### ISSUE TITLE
wc_get_notices session error

### ISSUE THREAD

**Issue by brittneymurphy** [woothemes/woocommerce#48023]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have a client who's getting a fatal error from this line in the wc_get_notices function:

`$all_notices = WC()->session->get( 'wc_notices', array() );`

Here's the error:

```
[20-May-2024 14:24:03 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /home/laneinnovative/domains/laneinnovative.com/public_html/wp-content/plugins/woocommerce/includes/wc-notice-functions.php:240
Stack trace:
#0 /home/laneinnovative/domains/laneinnovative.com/public_html/wp-content/plugins/woocommerce-gateway-authorize-net-cim/vendor/skyverge/wc-plugin-framework/woocommerce/payment-gateway/class-sv-wc-payment-gateway-direct.php(480): wc_get_notices()
#1 /home/laneinnovative/domains/laneinnovative.com/public_html/wp-content/plugins/woocommerce-gateway-authorize-net-cim/vendor/skyverge/wc-plugin-framework/woocommerce/payment-gateway/class-sv-wc-payment-gateway-direct.php(444): SkyVerge\WooCommerce\PluginFramework\v5_12_1\SV_WC_Payment_Gateway_Direct->get_notices_as_user_messages()
#2 /home/laneinnovative/domains/laneinnovative.com/public_html/wp-content/plugins/woocommerce-gateway-authorize-net-cim/vendor/skyverge/wc-plugin-framework/woocommerce/payment-gateway/integrations/class-sv-wc-payment-gateway-integration-subscriptions.php(371): SkyVerge\WooCommerce\PluginFramework\v5_12_1\SV_WC_Payment_Gateway_Direct->process_payment()
```

I didn't include the entire stack trace because it get quite long. 

I've temporarily fixed the error by adding the following right above the line that causes the error:

```
if ( WC()->session == null) {
	WC()->session = new WC_Session_Handler();
	WC()->session->init();
}
```

I didn't see any other mentions of this causing fatal errors, but this issue does seem to be similar: https://github.com/woocommerce/woocommerce/pull/46488

Maybe this should be fixed by the Authorize plugin instead, but I haven't figured out how to reach out to them yet so I thought I'd start here.

### Expected behavior

I expected the page to get the notices and carry on with whatever else it needs to do.

### Actual behavior

The page doesn't fully load because there's a fatal error.

### Steps to reproduce

My client didn't show me a step-by-step, but it happened on the admin side when a payment failed. I was able to find the error in the debug log and listed it above. 

To test, I replicated this by adding this line to an admin page outside of the WooCommerce framework.

`$all_notices = WC()->session->get( 'wc_notices', array() );`

 Once again the admin page didn't load all the way and gave me a fatal error, which was the same as the error I'd found earlier.
 
 When I added the fix of initiating a WC session, the page loaded fine.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment]
Hi @brittneymurphy, the session object referenced by `WC()->session` being null is an expected behavior as long as the code doesn't run in a frontend request, and by that I mean a request made from the customer-facing area of the site (so not including the admin area). That said, the `wc_get_notices` function should of course be robust enough to not throw an exception even when being invoked outside of such a request.

Could you please ask your client for more details on how/why they are invoking the function, as it seems that it's not intended for the admin area? Regardless, we'll keep this issue open, so that we can keep track of it and improve the robustness of `wc_get_notices` at some point. Thank you!

**Comment by brittneymurphy** [comment]
Just to clarify, my client didn't add the function on a page anywhwere, I just did that to try to replicate the problem. It was caused when a payment failed using the Authorize gateway. And when I went down the stack trace, it looks like Authorize is calling the wc_get_notices function.

I'm not sure if that helps or not. I can definitely try to find out more specific information from my client about the steps leading up to the error.

**Comment by jorgeatorres** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/57086.
