### ISSUE TITLE
quantities-and-units-for-woocommerce still incompatible with PHP 8.2

### ISSUE THREAD

**Issue by narcisgarcia** [woothemes/woocommerce#48886]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Migrating a Wordpress+Woocommerce site from Debian 11 webserver (PHP 7.4) to Debian 12 webserver (PHP 8.2).
Tried as a customer to order (add button) a product. A critical error page is returned.

### Expected behavior

Expected to see order basked with more units.

### Actual behavior

` Fatal error: Uncaught TypeError: Unsupported operand types: float - string in /srv/www/EXAMPLE.NET/www/site.tree/public/wp-content/plugins/quantities-and-units-for-woocommerce/includes/class-wcqu-validations.php:126 Stack trace: #0 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-content/plugins/quantities-and-units-for-woocommerce/includes/class-wcqu-validations.php(31): WC_Quantities_and_Units_Quantity_Validations->validate_single_product() #1 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-includes/class-wp-hook.php(324): WC_Quantities_and_Units_Quantity_Validations->add_to_cart_validation() #2 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-includes/plugin.php(205): WP_Hook->apply_filters() #3 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(840): apply_filters() #4 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(814): WC_Form_Handler::add_to_cart_handler_simple() #5 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-includes/class-wp-hook.php(324): WC_Form_Handler::add_to_cart_action() #6 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #7 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-includes/plugin.php(517): WP_Hook->do_action() #8 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-settings.php(717): do_action() #9 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-config.php(84): require_once('...') #10 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-load.php(50): require_once('...') #11 /srv/www/EXAMPLE.NET/www/site.tree/public/wp-blog-header.php(13): require_once('...') #12 /srv/www/EXAMPLE.NET/www/site.tree/public/index.php(17): require('...') #13 {main} thrown in /srv/www/EXAMPLE.NET/www/site.tree/public/wp-content/plugins/quantities-and-units-for-woocommerce/includes/class-wcqu-validations.php on line 126`

### Steps to reproduce

Open any product,
press Add to basket.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.0.2
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.18
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.11.6-MariaDB-0+deb12u1
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Tu servidor no tiene la clase SoapClient activada - puede que algunos plugins de pasarela de pago que utilizan SOAP no funcionen como se espera.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 6605
elementor_library: 9
entrevistas: 1
f12_captcha_log: 86
itsec-dash-card: 5
itsec-dashboard: 1
jc-import-files: 11
jc-imports: 1
libro: 1
mb-post-type: 1
mb-taxonomy: 1
mc4wp-form: 2
nav_menu_item: 127
oembed_cache: 6
page: 22
portafolio: 1
post: 143
product: 2866
quantity-rule: 10
revision: 21
shop_coupon: 5
shop_order: 1646
user_registration: 1
videojuegos: 1
viwec_template: 14
watermark: 1
wc_campos_registro: 1
wporg_custom_field: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Advanced Woo Search: por ILLID – 3.09
Breadcrumb NavXT: por John Havlik | Traducción: Karin Sequén – 7.3.0
Decorator - Personalizador de correo electrónico de WooCommerce: por WebToffee – 1.2.9
Disable Comments: por WPDeveloper – 2.4.6
Disable Gutenberg: por Jeff Starr – 3.1.2
Elementor Pro: por Elementor.com – 3.21.0
Elementor: por Elementor.com – 3.22.3
FactoriaTIC (personalizaciones varias): por Sergi Toboso – 2.0
GDPR Cookie Compliance: por Moove Agency – 4.15.1
Loco Translate: por Tim Whitlock – 2.6.10
Max Mega Menu: por megamenu.com – 3.3.1
No Category Base (WPML): por Marios Alexandrou – 1.3
PDF Image Generator: por Mizuho Ogino – 1.5.6
Product Image Watermark for Woo: por WP Plugin Experts – 1.0.4
Qty Increment Buttons for WooCommerce: por taisho – 2.7.5
Quantities and Units for WooCommerce: por Nicholas Verwymeren – 1.0.13
Recently Registered: por Mika Epstein – 3.5
Simple Page Ordering: por 10up – 2.7.1
SMTP Mailer: por naa986 – 1.1.15
Visibility Logic for Elementor: por StaxWP – 2.3.5.1
WooCommerce Campos en el Registro: por Enrique J. Ros – 4.2.4
WooCommerce AJAX Cart: por Moises Heberle – 1.3.25
Google Analytics for WooCommerce: por WooCommerce – 2.1.3
WooCommerce Legacy REST API: por WooCommerce – 1.0.4
WooCommerce Custom Payment Gateway: por WPRuby – 1.3.9
WooCommerce: por Automattic – 9.0.2
Yoast SEO: por Equipo Yoast – 22.9
WP Captcha: por Devnath verma – 2.0.0
WP-Optimize - Clean, Compress, Cache: por David Anderson
Ruhani Rabin
Team Updraft – 3.4.0


### Inactive Plugins (0) ###


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 días
Level threshold: –
Log directory size: 14 KB

### WC Pages ###

Base de la tienda: ❌ El ID de página está establecido
pero la página no existe

Carrito: #6 - /carrito-de-compra/
Finalizar compra: #7 - /finalizar-pedido/
Mi cuenta: #8 - /mi-cuenta/
Términos y condiciones: #1153 - /politica-de-ventas-y-envios/

### Theme ###

Name: Hello Elementor
Version: 3.1.0
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-06-27 13:04:05 +02:00
Options: ✔
Notes: 191
Onboarding: completed

### Action Scheduler ###

Completo: 674
Oldest: 2024-05-27 12:42:29 +0200
Newest: 2024-06-27 05:28:33 +0200

Fallida: 1
Oldest: 2023-02-15 16:47:35 +0100
Newest: 2023-02-15 16:47:35 +0100

Pendiente: 1
Oldest: 2024-06-27 22:19:23 +0200
Newest: 2024-06-27 22:19:23 +0200


### Status report information ###

Generated at: 2024-06-27 12:04:01 +02:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Thanks for reporting, this looks like this is an issue with the [Quantities and Units for WooCommerce plugin](https://wordpress.org/plugins/quantities-and-units-for-woocommerce/) and not WooCommerce core plugin so closing this. You should reach out the the plugin author for Quantities and Units for WooCommerce plugin
