### ISSUE TITLE
Undefined function `as_has_scheduled_action`

### ISSUE THREAD

**Issue by thilinah** [woothemes/woocommerce#49229]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This is a bug in WC 9.1-RC.1.

Which cause the exception:

```
PHP Fatal error:  Uncaught Error: Call to undefined function Automattic\WooCommerce\Internal\BatchProcessing\as_has_scheduled_action() in /var/www/wp-content/plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php:531
Stack trace:
#0 /var/www/wp-content/plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php(86): Automattic\WooCommerce\Internal\BatchProcessing\BatchProcessingController->remove_or_retry_failed_processors()
#1 /var/www/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\BatchProcessing\BatchProcessingController->Automattic\WooCommerce\Internal\BatchProcessing\{closure}('')
#2 /var/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /var/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /var/www/wp-includes/load.php(1270): do_action('shutdown')
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in /var/www/wp-content/plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php on line 531
```

Reason seems to be the newly added shutdown hook here: https://github.com/woocommerce/woocommerce/blob/9.1.0-rc.1/plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php#L83

- When the shutdown hook is called, it look for the function `as_has_scheduled_action`.
- But `as_has_scheduled_action` is defined after the shoulddown hook is added.
- If the process got killed at a point between BatchProcessingController constructor being called and `as_has_scheduled_action` is defined, this error will be thrown.

### Expected behavior

Check if `as_has_scheduled_action` is defined before calling it.

### Actual behavior

Shutdown hook throws an exception [here](https://github.com/woocommerce/woocommerce/blob/9.1.0-rc.1/plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php#L531).

### Steps to reproduce

1. The `BatchProcessingController` is created [here](https://github.com/woocommerce/woocommerce/blob/9.1.0-rc.1/plugins/woocommerce/src/Internal/DependencyManagement/ServiceProviders/BatchProcessingServiceProvider.php#L37)
2.  Call `wp_die()` right after this line.
```
public function register() {
		$this->share( BatchProcessingController::class, new BatchProcessingController() );
		wp_die();
		$this->share_with_implements_tags( OrderCouponDataMigrator::class );
	}
```
3. The exception mentioned in the error should occure.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.0-rc.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.59 (Debian)
PHP Version: 8.1.28
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.3.35-MariaDB-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 7
page: 7
post: 2
product: 1
shop_order: 1
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce Deposits: by WooCommerce – 2.2.9
WooCommerce Table Rate Shipping: by WooCommerce – 3.2.1 (update to version 3.2.2 is available)
WooCommerce: by Automattic – 9.1.0-rc.1

### Inactive Plugins (0) ###


### Must Use Plugins (1) ###

wccom-helper-local-testing-hacks.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 KB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 2.8
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-08 13:28:08 +00:00
Options: ✔
Notes: 78
Onboarding: skipped

### Action Scheduler ###

Complete: 20
Oldest: 2024-06-10 04:06:53 +0000
Newest: 2024-07-08 11:11:49 +0000

Failed: 10
Oldest: 2024-06-04 11:01:59 +0000
Newest: 2024-07-08 11:10:13 +0000

Pending: 2
Oldest: 2024-07-08 23:10:13 +0000
Newest: 2024-07-09 11:10:13 +0000


### Status report information ###

Generated at: 2024-07-08 11:32:08 +00:00
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by thilinah** [comment]
I've done some further debugging on this issue and noticed the error is happening if the wp shutdown hook is called before action scheduler functions are included.

1. The `BatchProcessingController` is created [here](https://github.com/woocommerce/woocommerce/blob/9.1.0-rc.1/plugins/woocommerce/src/Internal/DependencyManagement/ServiceProviders/BatchProcessingServiceProvider.php#L37)
2. But if `do_action('shutdown')` is called due to any reason after `BatchProcessingController` is constructed but before action scheduler functions from `plugins/woocommerce/packages/action-scheduler/functions.php` are loaded, the above exception will be thrown.
