### ISSUE TITLE
[Fatal] Call to a member function meta_exists() on null | class-wc-checkout.php

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#50245]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.0.2:

```
Uncaught Error: Call to a member function meta_exists() on null in /.../woocommerce/includes/class-wc-checkout.php:1360
```

<summary>
Part of a captured backtrace:

<details>

```
#0 /.../woocommerce/includes/class-wc-checkout.php(234): WC_Checkout->get_value('billing_country') 
#1 /.../plugins/shopengine/utils/helper.php(525): WC_Checkout->get_checkout_fields('billing') 
#2 /.../plugins/shopengine/widgets/checkout-form-billing/checkout-form-billing.php(36): ShopEngine\Utils\Helper::get_checkout_input_fields() 
#3 /.../plugins/elementor/includes/base/controls-stack.php(2361): Elementor\ShopEngine_Checkout_Form_Billing->register_controls() 
#4 /.../plugins/elementor/includes/base/controls-stack.php(569): Elementor\Controls_Stack->init_controls() 
#5 /.../plugins/elementor/includes/base/widget-base.php(197): Elementor\Controls_Stack->get_stack() 
#6 /.../plugins/elementor/includes/base/controls-stack.php(2141): Elementor\Widget_Base->init_settings() 
#7 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_data() 
#8 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#9 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#10 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Base\Document->get_data() 
#11 /.../plugins/elementor/core/files/css/base.php(102): Elementor\Plugin->elementor()->documents->get() 
#12 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->is_static() 
#13 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->save() 
#14 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#15 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#16 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#17 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#18 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#19 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#20 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#21 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#22 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#23 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#24 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#25 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#26 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#27 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#28 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#29 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#30 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save()
#31 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#32 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#33 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#34 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#35 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#36 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#37 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#38 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#39 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#40 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#41 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#42 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#43 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#44 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#45 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#46 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#47 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#48 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#49 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#51 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#52 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#53 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#54 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#55 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#56 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#57 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#58 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#59 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#60 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#61 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#62 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#63 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#64 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#65 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static() 
#66 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#67 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack() 
#68 /.../plugins/elementor/includes/base/controls-stack.php(308): Elementor\Controls_Stack->get_stack() 
#69 /.../plugins/elementor/core/base/document.php(1245): Elementor\Controls_Stack->get_data() 
#70 /.../plugins/elementor/core/files/css/base.php(36): Elementor\Core\Files\CSS\Base->save() 
#71 /.../plugins/elementor/core/files/css/document.php(451): Elementor\Core\Files\CSS\Base->is_static()
#72 /.../plugins/elementor/includes/managers/widgets.php(90): Elementor\Core\Files\CSS\Document->save() 
#73 /.../plugins/elementor/includes/base/controls-stack.php(486): Elementor\Controls_Stack->get_stack()
```

</details>

</summary>

If you look at the captured backtrace, it seems it may relate to a third party plugin, however it also seems like we could be more defensive within [WC_Checkout::get_value()](https://github.com/woocommerce/woocommerce/blob/9.1.4/plugins/woocommerce/includes/class-wc-checkout.php#L1320-L1369) and head this off. 

- We [try to get the `$customer_object`](https://github.com/woocommerce/woocommerce/blob/9.1.4/plugins/woocommerce/includes/class-wc-checkout.php#L1354-L1356) but don't have any guarantees that it will have been created.
- We then [check if a getter method is available](https://github.com/woocommerce/woocommerce/blob/9.1.4/plugins/woocommerce/includes/class-wc-checkout.php#L1358).
- If the above fails, which it will if `$customer_object` is null, we continue and [try to call the `get_meta()`](https://github.com/woocommerce/woocommerce/blob/9.1.4/plugins/woocommerce/includes/class-wc-checkout.php#L1361) method anyway.

We should probably check we have a valid `$customer_object` to start with. If we don't, we can simply return the default value.

### Expected behavior

No fatal errors `WC_Checkout::get_value()` is called.

### Actual behavior

Fatal errors can occur when `WC_Checkout::get_value()` is called.

### Steps to reproduce

We don't have steps to reproduce, but observed/received reports of multiple instances of this problem when 9.0.2 was released.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
I tried to replicate this from wp-cli shell, doing this:

```
$checkout = WC_Checkout::instance()
$checkout->get_value( 'billing_country' )
```

However, this still returned the expected default value of `US`, even though I did not explicitly initialize the cart or the customer object first. Thus, I think this error can only happen if WooCommerce has not been properly initialized yet, which is certainly possible in this case since it's being invoked from within another plugin (Elementor).

Should we still protect against this error? Maybe, but it might end up being a whack-a-mole, where once this error is avoided, another fatal error will just take it's place because the other plugin is `_doing_it_wrong`.

**Comment by coreymckrill** [comment]
Maybe the thing to do here is what we do in a few other places like [this](https://github.com/woocommerce/woocommerce/blob/d0e056729190feaab1ea3f3b1eddf2fd8bbdb65a/plugins/woocommerce/includes/wc-core-functions.php#L2531-L2535):

```php
	if ( ! did_action( 'before_woocommerce_init' ) || doing_action( 'before_woocommerce_init' ) ) {
		/* translators: 1: wc_load_cart 2: woocommerce_init */
		wc_doing_it_wrong( __FUNCTION__, sprintf( __( '%1$s should not be called before the %2$s action.', 'woocommerce' ), 'wc_load_cart', 'woocommerce_init' ), '3.7' );
		return;
	}
```

If we put this in `WC_Checkout`'s static `instance` method (maybe without the `return` since that would break backcompat) it would at least alert developers when their code might potentially be breaking things.

**Comment by barryhughes** [comment]
```
wp> did_action( 'init' ) && did_action( 'woocommerce_init' )
=> bool(true)
```

I think you're right. In the shell, almost everything is initialized by the time we are able to run commands.

> Maybe the thing to do here is [... use `wc_doing_it_wrong` ...] it would at least alert developers when their code might potentially be breaking things.

Somewhat playing devil's advocate: errors are already being emitted and logged when things go wrong, but I guess are being ignored (which might be because some sort of very specific conditions are needed, that are only found in a subset of production sites). Would adding additional deprecation warnings help with that?

Definitely not against it, though, as I guess it could still raise awareness and warn of other potential problems 🤔

**Comment by coreymckrill** [comment]
Ok, I've managed to replicate this without having to install Elementor:

1. Add this to an mu-plugins file:
    ```php
	add_action(
		'before_woocommerce_init',
		function() {
			require_once ABSPATH . 'wp-content/plugins/woocommerce/includes/class-wc-checkout.php';
			WC_Checkout::instance()->get_value( 'billing_country' );
		}
	);
    ```
2. Make a front end request from a logged out tab / Incognito mode.

<details>
<summary>Stack trace</summary>

```
[13-Aug-2024 22:46:42 UTC] PHP Fatal error:  Uncaught Error: Call to a member function meta_exists() on null in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php:1360
Stack trace:
#0 /var/www/html/wp-content/mu-plugins/index.php(17): WC_Checkout->get_value('billing_country')
#1 /var/www/html/wp-includes/class-wp-hook.php(324): {closure}('')
#2 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /var/www/html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(825): do_action('before_woocomme...')
#5 /var/www/html/wp-includes/class-wp-hook.php(324): WooCommerce->init('')
#6 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /var/www/html/wp-settings.php(700): do_action('init')
#9 /var/www/html/wp-config.php(147): require_once('/var/www/html/w...')
#10 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')
#11 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...')
#12 /var/www/html/index.php(17): require('/var/www/html/w...')
#13 {main}
  thrown in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php on line 1360
```
</details>
