### ISSUE TITLE
Uncaught Error: Cannot unset string offsets in StoreApi/Schemas/V1/AbstractSchema.php:98

### ISSUE THREAD

**Issue by grizooo** [woothemes/woocommerce#51059]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

All wp cli commands result in this error. Don't know why this happens, but to solve it for now, i just added an if case (is_array) like below.

```php
	protected function remove_arg_options( $properties ) {
		return array_map(
			function( $property ) {
				if ( isset( $property['properties'] ) ) {
					$property['properties'] = $this->remove_arg_options( $property['properties'] );
				} elseif ( isset( $property['items']['properties'] ) ) {
					$property['items']['properties'] = $this->remove_arg_options( $property['items']['properties'] );
				}
				if (is_array($property)) {
					unset( $property['arg_options'] );
				}
				return $property;
			},
			(array) $properties
		);
	}
```

### Expected behavior

No error in cli should appear, even if the woocommerce data is not correct

### Actual behavior

Cli commands will be executet but fail with this error.

### Steps to reproduce

1. open bash
2. execute any wp command

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.2.3
Legacy REST API Package Version: Auf dieser Website ist das alte REST-API-Plugin nicht installiert.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.27.1
PHP Version: 8.3.10
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.6.19-MariaDB-ubu2004
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 16
acf-field-group: 2
acf-taxonomy: 1
attachment: 7377
br_product_filter: 2
custom_css: 4
customize_changeset: 23
cwginstocknotifier: 1
divi_mega_pro: 1
document_template: 5
elementor_library: 2
et_body_layout: 2
et_pb_layout: 20
et_template: 12
et_theme_builder: 1
fgf_master_log: 76
fgf_rules: 4
filter-field: 3
filter-set: 1
lws_badge: 5
lws-wre-achievement: 5
lws-wre-event: 11
lws-wre-pool: 1
lws-wre-unlockable: 6
mailpoet_page: 1
ml-slide: 15
ml-slider: 1
mycred_rank: 1
nav_menu_item: 24
oembed_cache: 1
page: 30
polylang_mo: 1
popup: 2
popup_theme: 8
post: 1
product: 2331
product_variation: 5251
rank_math_schema: 1
revision: 28
rm_content_editor: 1
schema: 3
shop_coupon: 4
shop_order_placehold: 3549
shop_order_refund: 73
thc-events: 14
wcp_ruleset: 1
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (56) ###

Advanced Custom Fields: von WP Engine – 6.3.6
FiboSearch - AJAX Search for WooCommerce (Pro): von FiboSearch Team – 1.28.1
Erweiterte Sendungsverfolgung Pro: von zorem – 4.6.1
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: von codewoogeek – 5.4.2
consentmanager: von consentmanager – 3.0.7
Custom Related Products for WooCommerce [show-related]: von  – 99.0
Disable Gutenberg: von Jeff Starr – 3.1.2
Divi Mega Pro: von Divi Life — Tim Strifler – 1.9.8.2
Divi-Modules – Accessibility Attributes: von Divi-Modules – 1.0.1
Filter Everything PRO: von Andrii Stepasiuk – 1.8.6
Filter Everything — WooCoomerce Produkt & WordPress Filter: von Andrii Stepasiuk – 1.8.6
GTM for WooCommerce FREE - Google Tag Manager Integration: von Tag Concierge – 1.10.34
GTranslate: von Translate AI Multilingual Solutions – 3.0.6
Index WP MySQL For Speed: von Oliver Jones
Rick James – 1.4.18

iThemeland Free Gifts For Woo Lite: von iThemelandco – 2.3.4
Klarna Order Management for WooCommerce: von klarna
krokedil – 1.9.2

Klarna Payments for WooCommerce: von klarna – 3.6.1
MetaSlider: von MetaSlider – 3.90.1
NinjaFirewall (WP+): von The Ninja Technologies Network – 4.6.1
Nginx Cache: von Till Krüss – 1.0.6
One Stop Shop für WooCommerce: von vendidero – 1.6.2
Pfand (Deposit) for WooCommerce Products: von Nerdissimo – 2.0.0
RCD-Right Click Disabler for WordPress: von Param Sheoran – 1.0
releva.nz: von releva.nz – 2.1.7
Rank Math SEO PRO: von Rank Math – 3.0.69
Rank Math SEO: von Rank Math – 1.0.226
The Holiday Calendar: von Mva7 – 1.18.2
TikTok: von TikTok – 1.2.8
vendidero Helper: von vendidero – 2.2.4
CTX Feed: von WebAppick – 6.5.15
Discount Rules PRO 2.0: von Flycart – 2.6.5
Discount Rules Core: von Flycart – 2.6.5
WooCommerce.com Update Manager: von Automattic – 1.0.3
WooCommerce Amazon Pay: von WooCommerce – 2.5.2
Germanized für WooCommerce Pro: von vendidero – 4.1.0
Germanized für WooCommerce: von vendidero – 3.17.3
WooCommerce PayPal Payments: von WooCommerce – 2.8.3
WooCommerce Product Bundles: von Woo – 8.0.2
WooCommerce Shipping & Tax: von WooCommerce – 2.7.0
WooCommerce: von Automattic – 9.2.3
MyRewards: von Long Watch Studio – 5.3.5.1
WP All Export Pro: von Soflyy – 1.9.1
WP All Import Pro: von Soflyy – 4.8.10
WP Crontrol: von John Blackbourn – 1.17.0
WP-Lister Pro for eBay: von WP Lab – 3.6.5
WP Mail SMTP: von WP Mail SMTP – 4.1.1
WP-Optimize Premium - Clean, Compress, Cache: von David Anderson
Ruhani Rabin
Team Updraft – 3.5.0

WP All Export - ACF Export Add-On Pro: von Soflyy – 1.0.5
WP All Export - User Export Add-On Pro: von Soflyy – 1.0.7
WP All Export - WooCommerce Export Add-On Pro: von Soflyy – 1.0.9
WP All Import - ACF Add-On: von Soflyy – 3.3.8
WP All Import - Link Cloaking Add-on: von Soflyy – 1.1.5
WP All Import - WooCommerce Import Add-On Pro: von Soflyy – 4.0.0
YITH Infinite Scrolling: von YITH – 1.26.0

### Inactive Plugins (1) ###

NinjaFirewall (WP Edition): von The Ninja Technologies Network – 4.6.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

Index WP MySQL For Speed Upgrade Filter for mu-plugins.: von  – 1.4.14
NinjaFirewall WP+ (mu-plugin): von The Ninja Technologies Network – 1.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 Tage
Level threshold: –
Log directory size: 167 MB

### WC Pages ###

Shop-Basis: #3851 - /shop/
Warenkorb: #3852 - /warenkorb/ -  Enthält den [woocommerce_cart]-Shortcode
Kasse: #3853 - /checkout/ -  Enthält den [woocommerce_checkout]-Shortcode
Mein Konto: #3854 - /mein-konto/
Allgemeine Geschäftsbedingungen: #20287 - /agb/

### Theme ###

Name: Divi Child-Theme
Version: 1.0.0
Author URL: https://divi.world
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.27.1
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: divi-child/woocommerce/checkout/thankyou.php

### Product Bundles ###

Database Version: 8.0.2
Loopback Test: ✔
Template Overrides: –

### Klarna Payments Request Log ###

2023-02-21 10:07:12: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"406b1dc6-4db7-45c3-9314-beaecb9b0cfa\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:07:11: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"6ed2cdb1-aa87-4fbf-9e3d-4c92be686d57\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:07:11: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"c174d75e-8b65-4364-b664-06c25752d24d\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:06:33: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"9eb69154-7d1f-4c91-83ec-5e25060227dd\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:06:32: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"b1f01801-2d53-4441-b173-e63ef8967ff2\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:06:32: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"9b716595-5b16-467d-b7a6-063062fc00f8\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:06:22: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"6d513b22-0535-43b9-b138-217c7cbb7f5d\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:06:22: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"1e2a2b75-d269-40ef-aeab-251a3b1e9dad\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:06:22: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"3e0d2b69-4339-42a5-926d-278969ca1344\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:05:42: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"0fdbb7c9-90ba-4bfe-9896-9c4871d6663d\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:05:20: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"fe97e967-268b-4e94-afca-d77e246f7918\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:05:19: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"2b0b0318-7e39-49b1-863c-5fa277f2d5b5\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:05:14: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"0a803c66-dbff-487e-98e2-34c22c9d3d69\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:05:14: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"6000eab3-b1ff-426b-bfd2-18462e9975e6\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2023-02-21 10:05:11: KP Create Session
Response code: 400
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"BAD_VALUE\",\n  \"error_messages\" : [ \"Bad value: order_lines[3].total_tax_amount\" ],\n  \"correlation_id\" : \"1b90cd21-2d3b-49ef-9eae-04ac64a43b1b\"\n}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:


### Klarna Countries ###

Production Countries: DE
Test Countries: No countries selected

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-30 18:38:42 +00:00
Options: ✔
Notes: 81
Onboarding: completed

### Action Scheduler ###

Complete: 60
Oldest: 2024-08-29 21:50:39 +0000
Newest: 2024-08-30 03:28:04 +0000

Pending: 8
Oldest: 2024-08-30 21:50:40 +0000
Newest: 2024-08-31 03:09:24 +0000


### Status report information ###

Generated at: 2024-08-30 03:28:48 +00:00
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by florianbepunkt** [comment]
I can confirm the issue. The workaround described above works, but the issue is critical – at least for headless sites like ours, since all calls to the cart API fail.

**Comment by senadir** [comment]
Thanks! What's the error you're seeing, and why is this showing up just now and not 3 years ago.

**Comment by senadir** [comment]
More importantly, I can't reproduce the error you're describing.

**Comment by opr** [comment]
I am also unable to reproduce this, both on my local machine or my externally hosted site on Hostinger or WordPress.com

**Comment by florianbepunkt** [comment]
We are still investigating, but our current findings indicate that this has to do with the WooCommerce Germanized plugin, which was fixed two hours ago. @grizooo Do you have by any chance the WooCommerce Germanized plugin activated? If so could you please confirm that error is resolved when using their patch update from today?

**Comment by grizooo** [comment]
i updated the germanized plugin to 3.17.4 and the error seems to be gone now. thank you.

**Comment by seldimi** [comment]
Hello
I think the issue re-appeared, at least 10.4.x
Can't you escape it with is_array ?

**Comment by ucsendre** [comment]
> the issue re-appeared

I can confirm this error is present in StoreApi.
I have the below record in my error log:
`PHP Fatal error: Uncaught Error: Cannot unset string offsets in /wp-content/plugins/woocommerce/src/StoreApi/Schemas/V1/AbstractSchema.php:98`

WC Version: 10.5.2
WP Version: 6.9.1

```
Stack trace:

#0 [internal function]: Automattic\WooCommerce\StoreApi\Schemas\V1\AbstractSchema->{closure:Automattic\WooCommerce\StoreApi\Schemas\V1\AbstractSchema::remove_arg_options():92}()

#1 /wp-content/plugins/woocommerce/src/StoreApi/Schemas/V1/AbstractSchema.php(91): array_map()

#2 /wp-content/plugins/woocommerce/src/StoreApi/Schemas/V1/AbstractSchema.php(94): Automattic\WooCommerce\StoreApi\Schemas\V1\AbstractSchema->remove_arg_options()

#3 [internal function]: Automattic\WooCommerce\StoreApi\Schemas\V1\AbstractSchema->{closure:Automattic\WooCommerce\StoreApi\Schemas\V1\AbstractSchema::remove_arg_options():92}()

```

Could you please have a look and reply I would be more than happy indeed.

Thanks and regards,
Endre

**Comment by ucsendre** [comment]
Hello @seldimi 

I have found that this the error is caused by the latest update (version 2.5.1) of Pricepep - WooCommerce Dynamic Pricing & Discounts plugin by RightPress.

The error is gone as soon as Pricepep plugin is deactivated. I have tried this with different sets of plugins and themes and deactivating Pricepep was the solution every time.

I do not have active support for this paid plugin, so I could only post a comment to the plugin's page:
https://codecanyon.net/item/woocommerce-dynamic-pricing-discounts/7119279/comments?comment_31937529

I hope this helps you.

Best regards,
Endre

**Comment by seldimi** [comment]
I can confirm that. We used the same plugin. 

If we change the line on AbstractSchema.php
```
if (is_array( $property)) {
    unset( $property['arg_options'] );
}
```

Maybe on future release, it can make that bullet-proof as PHP 8.x becomes more strict.
