### ISSUE TITLE
[Fatal] PHP Fatal error: Uncaught WC_Data_Exception | class-wc-product-variation-data-store-cpt.php:61

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#51208]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.2.3

[Link to code](https://github.com/woocommerce/woocommerce/blob/b71e6e22a8c7fdbe10314fb7696c3cb646a336c3/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L53)

Stack trace:

```
PHP Fatal error:  Uncaught WC_Data_Exception: Ungültiger Produkttyp: Übergebene ID entspricht keiner Produktvariation. in /.../plugins/woocommerce/9.2.3/includes/data-stores/class-wc-product-variation-data-store-cpt.php:58
#0 /../plugins/woocommerce/9.2.3/includes/class-wc-data-store.php(159): WC_Product_Variation_Data_Store_CPT->read(Object(WC_Product_Variation))
#1 /../plugins/woocommerce/9.2.3/includes/abstracts/abstract-wc-product.php(139): WC_Data_Store->read(Object(WC_Product_Variation))
#2 /../plugins/woocommerce/9.2.3/includes/class-wc-product-simple.php(24): WC_Product->__construct('83630')
#3 /../plugins/woocommerce/9.2.3/includes/class-wc-product-variation.php(54): WC_Product_Simple->__construct('83630')
#4 /../../wp-content/plugins/bdroppy/src/Services/WooCommerce/Importer.php(888): WC_Product_Variation->__construct('83630')
#5 /../../wp-content/plugins/bdroppy/src/CronJob/Jobs/QueueJob.php(380): BDroppy\Services\WooCommerce\Importer->updateProductToWooCommerce(Object(stdClass), Object(BDroppy\Models\Mask\ProductMask), 1)
#6 /../../wp-content/plugins/bdroppy/src/CronJob/Jobs/QueueJob.php(39): BDroppy\CronJob\Jobs\QueueJob->updateMethod()
#7 /../../wp-content/plugins/bdroppy/src/CronJob/Jobs/BaseJob.php(41): BDroppy\CronJob\Jobs\QueueJob->handle()
#8 /../core/6.6.1/wp-includes/class-wp-hook.php(324): BDroppy\CronJob\Jobs\BaseJob->run()
#9 /../core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#10 /../core/6.6.1/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#11 /../core/6.6.1/wp-cron.php(191): do_action_ref_array('bdroppy_queues_...', Array)
#12 {main}
  thrown in /../plugins/woocommerce/9.2.3/includes/data-stores/class-wc-product-variation-data-store-cpt.php on line 58
```

(Translation for message: "PHP Fatal error: Uncaught WC_Data_Exception: Invalid product type: Passed ID does not correspond to a product variation. in /.../plugins/woocommerce/9.2.3/includes/data-stores/class-wc-product-variation-data-store-cpt.php:58")

### Expected behavior

No fatal errors when Uncaught WC_Data_Eception is thrown

### Actual behavior

Fatal errors when Uncaught WC_Data_Eception is thrown

### Steps to reproduce

We don't have steps to reproduce, but observed 974 instances of this problem on Fri Aug 30, 1200 UTC to 2359 UTC on one site. Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nigeljamesstevenson** [comment]
Still occurring in `9.6.1` I am updating the title for the new offending line number 61
see p1738681936354949/1738674245.585679-slack-C01DT6U03HC

**Comment by nigeljamesstevenson** [comment]
See p1738682099845839-slack-C08BH158LS2 for other information

**Comment by albarin** [comment]
This is coming from a plugin (`bdroppy`) that has some kind of [importer](https://github.com/idt-spa/bdroppy-wordpress-plugin/blob/7067295ec95291d8ec9f6af672ddae033e051d4a/src/Services/WooCommerce/Importer.php#L888):

`#4 /../../wp-content/plugins/bdroppy/src/Services/WooCommerce/Importer.php(888): WC_Product_Variation->__construct('83630')`

I'm thinking the exception is legit, shouldn't they handle the exception in their import function? 🤔 @coreymckrill @jorgeatorres

**Comment by jorgeatorres** [comment]
> [...]
> I'm thinking the exception is legit, shouldn't they handle the exception in their import function? 🤔 [@coreymckrill](https://github.com/coreymckrill) [@jorgeatorres](https://github.com/jorgeatorres)

I agree @albarin. It seems to be triggered by the datastore, so probably the wrong object type is being instantiated by their code (or the object doesn't even exist).
