### ISSUE TITLE
[Fatal] Fatal error: Uncaught Error: Call to a member function get() | includes/wc-cart-functions.php:394

### ISSUE THREAD

**Issue by veljkho** [woothemes/woocommerce#51237]
### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.2.3:

`Uncaught Error: Call to a member function get() on null in /wordpress/plugins/woocommerce/9.2.3/includes/wc-cart-functions.php:394`

[Link to code](https://github.com/woocommerce/woocommerce/blob/b40c4a95e5f8e92413abb335d1687d8b8efc230b/plugins/woocommerce/includes/wc-cart-functions.php#L394)

<details><summary>Stack trace</summary>

```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /wordpress/plugins/woocommerce/9.2.3/includes/wc-cart-functions.php:394
Stack trace:
#0 /srv/htdocs/wp-content/plugins/newebpay/class-newebpay.php(1673): wc_get_chosen_shipping_method_ids()
#1 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): newebpay_alter_payment_gateways(Array)
#2 /wordpress/core/6.6.1/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#3 /wordpress/plugins/woocommerce/9.2.3/includes/class-wc-payment-gateways.php(94): apply_filters('woocommerce_pay...', Array)
#4 /wordpress/plugins/woocommerce/9.2.3/includes/class-wc-payment-gateways.php(76): WC_Payment_Gateways->init()
#5 /wordpress/plugins/woocommerce/9.2.3/includes/class-wc-payment-gateways.php(49): WC_Payment_Gateways->__construct()
#6 /wordpress/plugins/woocommerce/9.2.3/includes/class-woocommerce.php(1137): WC_Payment_Gateways::instance()
#7 /wordpress/plugins/woocommerce/9.2.3/includes/class-woocommerce.php(201): WooCommerce->payment_gateways()
#8 /wordpress/plugins/woocommerce/9.2.3/src/StoreApi/Schemas/V1/CheckoutSchema.php(141): WooCommerce->__get('payment_gateway...')
#9 /wordpress/plugins/woocommerce/9.2.3/src/StoreApi/Schemas/V1/AbstractSchema.php(64): Automattic\WooCommerce\StoreApi\Schemas\V1\CheckoutSchema->get_properties()
#10 /wordpress/plugins/woocommerce/9.2.3/src/StoreApi/Routes/V1/AbstractRoute.php(85): Automattic\WooCommerce\StoreApi\Schemas\V1\AbstractSchema->get_item_schema()
#11 /wordpress/plugins/woocommerce/9.2.3/src/StoreApi/Routes/V1/AbstractRoute.php(269): Automattic\WooCommerce\StoreApi\Routes\V1\AbstractRoute->get_item_schema()
#12 /wordpress/plugins/woocommerce/9.2.3/src/StoreApi/Routes/V1/Checkout.php(80): Automattic\WooCommerce\StoreApi\Routes\V1\AbstractRoute->get_context_param(Array)
#13 /wordpress/plugins/woocommerce/9.2.3/src/StoreApi/RoutesController.php(162): Automattic\WooCommerce\StoreApi\Routes\V1\Checkout->get_args()
#14 /wordpress/plugins/woocommerce/9.2.3/src/StoreApi/RoutesController.php(87): Automattic\WooCommerce\StoreApi\RoutesController->register_routes('v1', 'wc/store')
#15 /wordpress/plugins/woocommerce/9.2.3/src/StoreApi/StoreApi.php(30): Automattic\WooCommerce\StoreApi\RoutesController->register_all_routes()
#16 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\StoreApi\StoreApi->Automattic\WooCommerce\StoreApi\{closure}(Object(WP_REST_Server))
#17 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#18 /wordpress/core/6.6.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#19 /wordpress/core/6.6.1/wp-includes/rest-api.php(589): do_action('rest_api_init', Object(WP_REST_Server))
#20 /wordpress/core/6.6.1/wp-includes/rest-api.php(413): rest_get_server()
#21 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#22 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#23 /wordpress/core/6.6.1/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#24 /wordpress/core/6.6.1/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#25 /wordpress/core/6.6.1/wp-includes/class-wp.php(813): WP->parse_request('')
#26 /wordpress/core/6.6.1/wp-includes/functions.php(1336): WP->main('')
#27 /wordpress/core/6.6.1/wp-blog-header.php(16): wp()
#28 /wordpress/core/6.6.1/index.php(17): require('/wordpress/core...')
#29 {main}
  thrown in /wordpress/plugins/woocommerce/9.2.3/includes/wc-cart-functions.php on line 394
```
</details> 

### Expected behavior

No fatal error

### Actual behavior

Fatal error

### Steps to reproduce

We don't have steps to reproduce this problem, but we observed 440 instances of it on Friday, September 6, from 1200 UTC to 2351 UTC on 5+ sites. Hopefully, someone can dig in and apply a defensive check if appropriate. This will be updated after the investigation.

**Comment by DavidAnderson684** [comment]
@veljkho This was previously reported here ("This is a bug in WooCommerce core, in the wc_get_chosen_shipping_method_ids() function, which attempts to check a value from the WooCommerce session without first checking if any WooCommerce session exists. ") - including the fatal error on the same line: https://github.com/woocommerce/woocommerce/issues/43375 , and tagged by multiple people.

A lot of people never bother reporting things to WordPress Core Trac because it looks there like only insiders can get any attention to things they post. It's been a shame (in my personal experience) to have seen the WooCommerce bug tracker go in the same direction in recent years. If you can tell us what should have been done on https://github.com/woocommerce/woocommerce/issues/43375 to get some attention (I personally had to advise many users of my extension of how to deploy work-arounds) I'd be grateful to know because nobody on either side benefits from having reproducible, widely-experienced bugs getting no attention.

I'm glad it is now fixed, anyway.
