### ISSUE TITLE
[Fatal] Path cannot be empty in `wc_template_redirect()` include statement | `wc-template-functions.php`

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#51304]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

During the 9.3.0 release, we observed the following error:

```
PHP Fatal error: Uncaught ValueError: Path cannot be empty 
in /.../woocommerce/includes/wc-template-functions.php:53
```

💡 We can see error logs suggesting this is not new as of 9.3.0.

<details>
<summary> Backtrace </summary>

```
#0 /.../wp-includes/class-wp-hook.php(324): wc_template_redirect('')
#1 /.../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#2 /.../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /.../wp-includes/template-loader.php(13): do_action('template_redire...')
#4 /.../wp-blog-header.php(19): require_once('/wordpress/core...')
#5 /.../index.php(17): require('/wordpress/core...')
#6 {main}
  thrown in /wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 53
```

</details>

[Relevant code](https://github.com/woocommerce/woocommerce/blob/9.2.3/plugins/woocommerce/includes/wc-template-functions.php#L49-L55)

We're trying to `include` whatever `get_query_template( '404' )` returns, which probably is a valid filepath in lots of cases but, actually, can be anything at all—including an empty string.

### Expected behavior

If we don't have a valid template path, let's find another way to gracefully exit (which is what happens anyway, once execution enters this path) without causing a fatal error.

### Actual behavior

In some circumstances, when we can't determine a valid 404 template path, we're triggering a fatal error.

### Steps to reproduce

No steps to share, this was observed by monitoring error logs.

### WordPress Environment

—

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by cardehngeh** [comment]
Zen - 8974289

**Comment by JanWebofka** [comment]
9.3.3 Still a problem, any updates ?

**Comment by barryhughes** [comment]
Not as yet, but if you stay subscribed to this issue you will see when a fix is ready.

**Comment by JanWebofka** [comment]
Well, do we have workaround ? Nothing seems to help it.

**Comment by barryhughes** [comment]
A workaround could be to modify your theme (or a child theme) and supply a 404 template, or else you could specify some other valid filepath using the `404_template` filter hook.

**Comment by JanWebofka** [comment]
Hmm interesting, I use elementor pro and i didnt have 404 template setup, so i created it. But error still the same.

**Comment by sefod** [comment]
Anyone else still having this issue, now on line 54?

**Comment by misiek08** [comment]
> Anyone else still having this issue, now on line 54?

Yup. Client is using Elementor, has 404 defined and exactly same problem :(
