### ISSUE TITLE
[Fatal] Unsupported operand types: string - int in `WCPayPromotion/Init.php`

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#51335]
During the 9.3.1 release, we observed the following problem:

```
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string - int 
in /.../woocommerce/src/Internal/Admin/WCPayPromotion/Init.php:82
```

~This appears to be new as of 9.3.x.~ This does not appear to be new, we can see instances of this from 9.2.x, for instance.

<details>
<summary>Backtrace</summary>

```
#0 /.../wp-includes/class-wp-hook.php(326): 
   Automattic\WooCommerce\Internal\Admin\WCPayPromotion\Init::set_gateway_top_of_list(Array)
   
#1 /.../wp-includes/plugin.php(205): 
   WP_Hook->apply_filters('s:101:"s:93:"s:...', Array)
   
#2 /.../wp-includes/option.php(247): 
   apply_filters('option_woocomme...', 's:101:"s:93:"s:...', 'woocommerce_gat...')
   
#3 /.../wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(97): 
    get_option('woocommerce_gat...')

#4 /.../wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(76): 
    WC_Payment_Gateways->init()

#5 /.../wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(49): 
    WC_Payment_Gateways->__construct()

#6 /.../wp-content/plugins/woocommerce/includes/class-woocommerce.php(1152): 
    WC_Payment_Gateways::instance()

#7 /.../wp-content/plugins/woocommerce/includes/class-woocommerce.php(204): 
    WooCommerce->payment_gateways()

#8 /.../wp-content/plugins/woocommerce/src/StoreApi/Schemas/V1/CheckoutSchema.php(141): 
    WooCommerce->__get('payment_gateway...')

#9 /.../wp-content/plugins/woocommerce/src/StoreApi/Schemas/V1/AbstractSchema.php(64): 
    Automattic\WooCommerce\StoreApi\Schemas\V1\CheckoutSchema->get_properties()

#10 /.../wp-content/plugins/woocommerce/src/StoreApi/Routes/V1/AbstractRoute.php(85): 
    Automattic\WooCommerce\StoreApi\Schemas\V1\AbstractSchema->get_item_schema()

#11 /.../wp-content/plugins/woocommerce/src/StoreApi/Routes/V1/AbstractRoute.php(269): 
    Automattic\WooCommerce\StoreApi\Routes\V1\AbstractRoute->get_item_schema()

#12 /.../wp-content/plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php(82): 
    Automattic\WooCommerce\StoreApi\Routes\V1\AbstractRoute->get_context_param(Array)

#13 /.../wp-content/plugins/woocommerce/src/StoreApi/RoutesController.php(156): 
    Automattic\WooCommerce\StoreApi\Routes\V1\Checkout->get_args()

#14 /.../wp-content/plugins/woocommerce/src/StoreApi/RoutesController.php(81): 
    Automattic\WooCommerce\StoreApi\RoutesController->register_routes('v1', 'wc/store')

#15 /.../wp-content/plugins/woocommerce/src/StoreApi/StoreApi.php(30): 
    Automattic\WooCommerce\StoreApi\RoutesController->register_all_routes()

#16 /.../wp-includes/class-wp-hook.php(324): 
    Automattic\WooCommerce\StoreApi\StoreApi->Automattic\WooCommerce\StoreApi\{closure}(Object(WP_REST_Server))

#17 /.../wp-includes/class-wp-hook.php(348): 
    WP_Hook->apply_filters(NULL, Array)

#18 /.../wp-includes/plugin.php(517): 
    WP_Hook->do_action(Array)

#19 /.../wp-includes/rest-api.php(589): 
    do_action('rest_api_init', Object(WP_REST_Server))

#20 /.../wp-includes/rest-api.php(413): 
    rest_get_server()

#21 /.../wp-includes/class-wp-hook.php(324): 
    rest_api_loaded(Object(WP))

#22 /.../wp-includes/class-wp-hook.php(348): 
    WP_Hook->apply_filters(NULL, Array)

#23 /.../wp-includes/plugin.php(565): 
    WP_Hook->do_action(Array)

#24 /.../wp-includes/class-wp.php(418): 
    do_action_ref_array('parse_request', Array)

#25 /.../wp-includes/class-wp.php(813): 
    WP->parse_request('')

#26 /.../wp-includes/functions.php(1336): 
    WP->main('')

#27 /.../wp-blog-header.php(16): 
    wp()

#28 /.../index.php(17): 
    require('/wordpress/core...')

#29 {main}
    thrown in /.../wp-content/plugins/woocommerce/src/Internal/Admin/WCPayPromotion/Init.php on line 82
```

</details>

### Expected behavior

No unnecessary fatal errors.

### Actual behavior

Fatal errors under some conditions.

### Steps to reproduce

No steps to share, this was observed by monitoring error logs.

**Comment by nigeljamesstevenson** [comment]
Discussed here - this may not be a new issue for `9.3.x` - see p1726157049413219-slack-C01DT6U03HC

**Comment by ioweb-gr** [comment]
The problem is coming in my case because `$ordering` variable is a serialized array and min is invoked outside of it. 

```
array (
  0 => 'a:15:{s:3:"cod";i:0;s:4:"bacs";i:1;s:6:"cheque";i:2;s:6:"paypal";i:3;s:8:"coingate";i:4;s:6:"stripe";i:5;s:11:"stripe_sepa";i:6;s:17:"stripe_bancontact";i:7;s:13:"stripe_sofort";i:8;s:14:"stripe_giropay";i:9;s:10:"stripe_eps";i:10;s:12:"stripe_ideal";i:11;s:10:"stripe_p24";i:12;s:13:"stripe_alipay";i:13;s:17:"stripe_multibanco";i:14;}',
)
```

Before using  `min` function most likely the array needs to be deserialized

`$ordering[ $id ] = $is_empty ? 0 : ( min( $ordering ) - 1 );`

Then serialized again after ordering if I understand it correctly as now min will return a string with the serialized value. 

The problem is that using unserialize here would open up some security issues unless properly sanitized data is set here. Most likely the ordering should happen earlier before the array is serialized?

**Comment by ErikBernskiold** [comment]
Found this thread today while debugging while users could no longer update any pages on the site after moving to PHP 8.x. This was the culprit.

Our hacky solution has been to just comment this function out.

**Comment by vladolaru** [comment]
Hello, everybody! Looking at the code reported, it is not doing anything abnormal.

The WordPress `get_option` function will fire the `option_woocommerce_gateway_order` filter like so:

```
return apply_filters( "option_{$option}", maybe_unserialize( $value ), $option );
```

The value is already unserialized if it is serialized (while at rest in the DB, it is serialized). What I think it is happening is some other code (WC core or external) is doubly serializing the value and we end up with what was shared above:

```
array (
  0 => 'a:15:{s:3:"cod";i:0;s:4:"bacs";i:1;s:6:"cheque";i:2;s:6:"paypal";i:3;s:8:"coingate";i:4;s:6:"stripe";i:5;s:11:"stripe_sepa";i:6;s:17:"stripe_bancontact";i:7;s:13:"stripe_sofort";i:8;s:14:"stripe_giropay";i:9;s:10:"stripe_eps";i:10;s:12:"stripe_ideal";i:11;s:10:"stripe_p24";i:12;s:13:"stripe_alipay";i:13;s:17:"stripe_multibanco";i:14;}',
)
```

The problem lies there, not with the `Automattic\WooCommerce\Internal\Admin\WCPayPromotion\Init::set_gateway_top_of_list()` method.

Regardless of this, we will completely remove the `Automattic\WooCommerce\Internal\Admin\WCPayPromotion\Init` class in the upcoming 9.9 release since [we replace the classic Payments Settings page with the new one](https://developer.woocommerce.com/2024/12/16/modernizing-the-woocommerce-payments-experience-technical-changes-ahead/) (React-based).
