### ISSUE TITLE
[Fatal] Argument must be string, array given in `WC_Admin_Status::scan_template_files()` | `class-wc-admin-status.php`

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#51336]
During the 9.3.1 release, we observed the following problem:

```
PHP Fatal error:  Uncaught TypeError: scandir(): Argument #1 ($directory) must be of type string, array given 
in /.../plugins/woocommerce/includes/admin/class-wc-admin-status.php:209
```

It does not however appear to be new as of this release cycle.

<details>
<summary>Backtrace</summary>

```
#0 /.../wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php(209): 
   scandir(Array)
   
#1 /.../wp-content/plugins/woocommerce/includes/class-wc-tracker.php(997): 
    WC_Admin_Status::scan_template_files(Array)
    
#2 /.../wp-content/plugins/woocommerce/includes/class-wc-tracker.php(199): 
    WC_Tracker::get_all_template_overrides()
    
#3 /.../wp-content/plugins/woocommerce/includes/class-wc-tracker.php(77): 
    WC_Tracker::get_tracking_data()
    
#4 /.../wp-includes/class-wp-hook.php(324): 
    WC_Tracker::send_tracking_data()
    
#5 /.../wp-includes/class-wp-hook.php(348): 
    WP_Hook->apply_filters('', Array)
    
#6 /.../wp-includes/plugin.php(565): 
    WP_Hook->do_action(Array)
    
#7 /.../wp-cron.php(191): 
    do_action_ref_array('woocommerce_tra...', Array)
    
#8 {main}
   thrown in /.../wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php on line 209
```

</details>

### Expected behavior

No unnecessary fatal errors.

### Actual behavior

Fatal errors under some conditions.

### Steps to reproduce

No steps to share, this was observed by monitoring error logs.

**Comment by jorgeatorres** [comment]
Fixed in #54353.
