### ISSUE TITLE
[Fatal] Call to a member function on string in `woocommerce_related_products()` | `wc-template-functions.php`

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#51337]
During the 9.3.1 release, we observed the following fatal error:

```
PHP Fatal error: Uncaught Error: Call to a member function get_id() on string 
in /.../plugins/woocommerce/includes/wc-template-functions.php:2093
```

[Relevant code](https://github.com/woocommerce/woocommerce/blob/release/9.3/plugins/woocommerce/includes/wc-template-functions.php#L2076-L2103): within `woocommerce_related_products()` it looks like we assume the global `$product` object will be set ... it may not be.

<details>
<summary> Backtrace </summary>

```
#0 /.../plugins/woocommerce/includes/class-wc-shortcodes.php(735): 
   woocommerce_related_products(Array)

#1 /.../core/6.6.2/wp-includes/shortcodes.php(434): 
   WC_Shortcodes::related_products(Array, '', 'related_product...')

#2 [internal function]: do_shortcode_tag(Array)

#3 /.../core/6.6.2/wp-includes/shortcodes.php(273): 
   preg_replace_callback('/\\[(\\[?)(relate...', 'do_shortcode_ta...', '[related_produc...')

#4 /.../wp-content/plugins/elementor/includes/widgets/shortcode.php(137): 
   do_shortcode('[related_produc...')

#5 /.../wp-content/plugins/elementor/includes/base/controls-stack.php(2325): 
   Elementor\Widget_Shortcode->render()

#6 /.../wp-content/plugins/elementor/includes/base/widget-base.php(635): 
   Elementor\Controls_Stack->render_by_mode()

#7 /.../wp-content/plugins/elementor/includes/base/widget-base.php(776): 
   Elementor\Widget_Base->render_content()

#8 /.../wp-content/plugins/elementor/includes/base/element-base.php(483): 
   Elementor\Widget_Base->print_content()

#9 /.../wp-content/plugins/elementor/includes/base/element-base.php(1442): 
   Elementor\Element_Base->print_element()

#10 /.../wp-content/plugins/elementor/includes/base/element-base.php(483): 
   Elementor\Element_Base->print_content()

#11 /.../wp-content/plugins/elementor/includes/base/element-base.php(1442): 
   Elementor\Element_Base->print_element()

#12 /.../wp-content/plugins/elementor/includes/base/element-base.php(483): 
   Elementor\Element_Base->print_content()

#13 /.../wp-content/plugins/elementor/core/base/document.php(1875): 
   Elementor\Element_Base->print_element()

#14 /.../wp-content/plugins/elementor/core/base/document.php(1800): 
   Elementor\Core\Base\Document->do_print_elements(Array)

#15 /.../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(412): 
   Elementor\Core\Base\Document->print_elements(Array)

#16 /.../wp-content/plugins/elementor/includes/frontend.php(1200): 
   ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper(Array)

#17 /.../wp-content/plugins/elementor/core/base/document.php(1249): 
   Elementor\Frontend->get_builder_content(25653, false)

#18 /.../wp-content/plugins/elementor/modules/library/documents/library-document.php(76): 
   Elementor\Core\Base\Document->get_content(false)

#19 /.../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(158): 
   Elementor\Modules\Library\Documents\Library_Document->get_content(false)

#20 /.../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(173): 
   ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_content()

#21 /.../wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(370): 
   ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_content()

#22 /.../wp-content/plugins/elementor-pro/modules/theme-builder/api.php(13): 
   ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->do_location('footer')

#23 /.../wp-content/themes/martfury/footer.php(14): 
   elementor_theme_do_location('footer')

#24 /.../core/6.6.2/wp-includes/template.php(810): 
   require_once('/.../wp-...')

#25 /.../core/6.6.2/wp-includes/template.php(745): 
   load_template('/.../wp-...', true, Array)

#26 /.../core/6.6.2/wp-includes/general-template.php(92): 
   locate_template(Array, true, true, Array)

#27 /.../wp-content/themes/martfury/404.php(15): 
   get_footer()

#28 /.../core/6.6.2/wp-includes/template-loader.php(106): 
   include('/.../wp-...')

#29 /.../core/6.6.2/wp-blog-header.php(19): 
   require_once('/.../core...')

#30 /.../core/6.6.2/index.php(17): 
   require('/.../core...')

#31 {main}
    thrown in /.../plugins/woocommerce/includes/wc-template-functions.php on line 2093
```

</details>

**Comment by albarin** [comment]
This is fixed by https://github.com/woocommerce/woocommerce/pull/53167
