### ISSUE TITLE
[Fatal] Uncaught type error in `QuantityLimits::get_add_to_cart_limits()` | `QuantityLimits.php`

### ISSUE THREAD

**Issue by barryhughes** [woothemes/woocommerce#51340]
While observing the 9.3.1 release (though it does not appear to be new as of 9.3.x) we noticed the following fatal error being logged:

```
PHP Fatal error: Uncaught TypeError: Automattic\WooCommerce\StoreApi\Utilities\QuantityLimits::limit_to_multiple(): Argument #1 ($number) must be of type int, string given
in /.../wp-content/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php on line 58
```

[Relevant code](https://github.com/woocommerce/woocommerce/blob/release/9.3/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php#L58)

<details>
<summary> Backtrace </summary>

```
#0 /.../wp-content/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php(58): 
   Automattic\WooCommerce\StoreApi\Utilities\QuantityLimits->limit_to_multiple('', '', 'ceil')

#1 /.../wp-content/plugins/woocommerce/src/StoreApi/Schemas/V1/ProductSchema.php(487): 
   Automattic\WooCommerce\StoreApi\Utilities\QuantityLimits->get_add_to_cart_limits(Object(WC_Product_Variable))

#2 [internal function]: 
   Automattic\WooCommerce\StoreApi\Schemas\V1\ProductSchema->get_item_response(Object(WC_Product_Variable))

#3 /.../wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractProductGrid.php(114): 
   array_map(Array, Array)

#4 /.../wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(98): 
   Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->render(Array, '', Object(WP_Block))

#5 /.../wp-includes/class-wp-block.php(519): 
   Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback(Array, '', Object(WP_Block))

#6 /.../wp-includes/blocks.php(2061): 
   WP_Block->render()

#7 /.../wp-includes/blocks.php(2113): 
   render_block(Array)

#8 /.../wp-includes/class-wp-hook.php(324): 
   do_blocks('<!-- wp:paragra...')

#9 /.../wp-includes/plugin.php(205): 
   WP_Hook->apply_filters('<!-- wp:paragra...', Array)

#10 /.../wp-includes/post-template.php(256): 
    apply_filters('the_content', '<!-- wp:paragra...')

#11 /.../wp-content/themes/bam-pro/partials/content-page.php(23): 
    the_content()

#12 /.../wp-includes/template.php(812): 
    require('/srv/htdocs/wp-...')

#13 /.../wp-includes/template.php(745): 
    load_template('/srv/htdocs/wp-...', false, Array)

#14 /.../wp-includes/general-template.php(206): 
    locate_template(Array, true, false, Array)

#15 /.../wp-content/themes/bam-pro/front-page.php(90): 
    get_template_part('partials/conten...', 'page')

#16 /.../wp-includes/template-loader.php(106): 
    include('/srv/htdocs/wp-...')

#17 /.../wp-blog-header.php(19): 
    
    require_once('/.../wp-content/core...')

#18 /.../index.php(17): 
    require('/.../wp-content/core...')

#19 {main} thrown in
    /.../wp-content/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php on line 72
```

</details>

No steps to replicate, as this was captured while monitoring logs.

**Comment by agabor** [comment]
Great, this bothered me for a while. Will this be in the next release?

**Comment by barryhughes** [comment]
Not quite, I'm afraid. It should make it into 9.5.0, though (that's because we have a period of time known as code freeze, or feature freeze, and we've already entered that for 9.4.0).

**Comment by agabor** [comment]
Thanks, I will wait patiently :)
