### ISSUE TITLE
[Fatal] Uncaught Error: Call to a member function meta_exists() on null | class-wc-checkout.php:1360

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#51381]
Fatal error in WooCommerce 9.2.3:

`PHP Fatal error:  Uncaught Error: Call to a member function meta_exists() on null in /wordpress/plugins/woocommerce/9.2.3/includes/class-wc-checkout.php:1360`

<details><summary>Stack trace</summary>

```
#0 /wordpress/plugins/woocommerce/9.2.3/includes/class-wc-checkout.php(234): WC_Checkout->get_value('billing_country')
#1 /srv/htdocs/wp-content/plugins/shopengine/utils/helper.php(525): WC_Checkout->get_checkout_fields('billing')
#2 /srv/htdocs/wp-content/plugins/shopengine/widgets/checkout-form-billing/checkout-form-billing.php(36): ShopEngine\Utils\Helper::get_checkout_input_fields()
#3 /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(2386): Elementor\ShopEngine_Checkout_Form_Billing->register_controls()
#4 /srv/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(1065): Elementor\Controls_Stack->init_controls()
#5 /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(569): Elementor\Widget_Base->init_controls()
#6 /srv/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(192): Elementor\Controls_Stack->get_stack()
#7 /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(314): Elementor\Widget_Base->get_stack()
#8 /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(2475): Elementor\Controls_Stack->get_controls()
#9 /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1158): Elementor\Controls_Stack->sanitize_settings(Array)
#10 /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(2218): Elementor\Controls_Stack->get_data('settings')
#11 /srv/htdocs/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#12 /srv/htdocs/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#13 /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1172): Elementor\Core\Base\Base_Object->get_settings()
#14 /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1263): Elementor\Controls_Stack->get_parsed_dynamic_settings()
#15 /srv/htdocs/wp-content/plugins/elementor-pro/modules/display-conditions/module.php(179): Elementor\Controls_Stack->get_settings_for_display()
#16 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\DisplayConditions\Module->before_element_render(Object(Elementor\ShopEngine_Checkout_Form_Billing))
#17 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#18 /wordpress/core/6.6.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#19 /srv/htdocs/wp-content/plugins/elementor/includes/base/element-base.php(474): do_action('elementor/front...', Object(Elementor\ShopEngine_Checkout_Form_Billing))
#20 /srv/htdocs/wp-content/plugins/elementor/includes/base/element-base.php(1440): Elementor\Element_Base->print_element()
#21 /srv/htdocs/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#22 /srv/htdocs/wp-content/plugins/elementor/includes/base/element-base.php(1440): Elementor\Element_Base->print_element()
#23 /srv/htdocs/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#24 /srv/htdocs/wp-content/plugins/elementor/core/base/document.php(1875): Elementor\Element_Base->print_element()
#25 /srv/htdocs/wp-content/plugins/elementor/core/base/document.php(1800): Elementor\Core\Base\Document->do_print_elements(Array)
#26 /srv/htdocs/wp-content/plugins/elementor/core/base/document.php(1201): Elementor\Core\Base\Document->print_elements(Array)
#27 /srv/htdocs/wp-content/plugins/elementor/includes/frontend.php(1158): Elementor\Core\Base\Document->print_elements_with_wrapper(Array)
#28 /srv/htdocs/wp-content/plugins/elementor/includes/frontend.php(1053): Elementor\Frontend->get_builder_content(25892)
#29 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): Elementor\Frontend->apply_builder_in_content('<h2>Checkout</h...')
#30 /wordpress/core/6.6.1/wp-includes/plugin.php(205): WP_Hook->apply_filters('<h2>Checkout</h...', Array)
#31 /wordpress/plugins/wordpress-seo/23.4/src/builders/indexable-link-builder.php(132): apply_filters('the_content', '<h2>Checkout</h...')
#32 /wordpress/plugins/wordpress-seo/23.4/src/actions/indexing/abstract-link-indexing-action.php(76): Yoast\WP\SEO\Builders\Indexable_Link_Builder->build(Object(Yoast\WP\SEO\Models\Indexable), '<h2>Checkout</h...')
#33 /wordpress/plugins/wordpress-seo/23.4/src/integrations/admin/background-indexing-integration.php(163): Yoast\WP\SEO\Actions\Indexing\Abstract_Link_Indexing_Action->index()
#34 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): Yoast\WP\SEO\Integrations\Admin\Background_Indexing_Integration->index()
#35 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#36 /wordpress/core/6.6.1/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#37 /wordpress/core/6.6.1/wp-cron.php(191): do_action_ref_array('wpseo_indexable...', Array)
#38 {main}
  thrown in /wordpress/plugins/woocommerce/9.2.3/includes/class-wc-checkout.php on line 1360
```

</details> 

### Steps to reproduce

No clear steps to reproduce, but observed 384 instances of this problem on Fri Sep 6, 1200 UTC to 2359 UTC on 5+ sites.

**Comment by mikejolley** [comment]
This was looks to have been tackled already via https://github.com/woocommerce/woocommerce/pull/50692
