### ISSUE TITLE
Payment Plugins for Stripe WooCommerce issue fatal error

### ISSUE THREAD

**Issue by tomoveout** [woothemes/woocommerce#51594]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

WordPress version 6.6.2
Thème actif : adforest child (version 1.0.0)
Extension actuelle : Payment Plugins for Stripe WooCommerce (version 3.3.75)
PHP version 8.1.27

Une erreur de type E_ERROR a été causée dans la ligne 62 du fichier /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woo-stripe-payment/includes/class-wc-stripe-api-operation.php. Message d'erreur : Uncaught InvalidArgumentException: Property paymentMethodConfigurations is not a valid entry in /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woo-stripe-payment/includes/class-wc-stripe-api-operation.php:62
Stack trace:
#0 /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woo-stripe-payment/includes/class-wc-stripe-gateway.php(107): WC_Stripe_API_Operation->__construct()
#1 /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woo-stripe-payment/includes/gateways/class-wc-payment-gateway-stripe-upm.php(503): WC_Stripe_Gateway->__get()
#2 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/class-wp-hook.php(326): WC_Payment_Gateway_Stripe_UPM->handle_connection_success()
#3 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woo-stripe-payment/includes/admin/settings/class-wc-stripe-account-settings.php(65): do_action()
#6 /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woo-stripe-payment/includes/admin/settings/class-wc-stripe-account-settings.php(83): WC_Stripe_Account_Settings->save_account_settings()
#7 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/class-wp-hook.php(324): WC_Stripe_Account_Settings->post_api_update()
#8 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#9 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#10 /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-page.php(265): do_action()
#11 /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-payment-gateways.php(320): WC_Settings_Page->do_update_options_action()
#12 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/class-wp-hook.php(324): WC_Settings_Payment_Gateways->save()
#13 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#14 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#15 /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php(84): do_action()
#16 /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(179): WC_Admin_Settings::save()
#17 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/class-wp-hook.php(324): WC_Admin_Menus->save_settings()
#18 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#19 /home/u196177799/domains/tomoveout.fr/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#20 /home/u196177799/domains/tomoveout.fr/public_html/wp-settings.php(722): do_action()
#21 /home/u196177799/domains/tomoveout.fr/public_html/wp-config.php(111): require_once('/home/u19617779...')
#22 /home/u196177799/domains/tomoveout.fr/public_html/wp-load.php(50): require_once('/home/u19617779...')
#23 /home/u196177799/domains/tomoveout.fr/public_html/wp-admin/admin.php(34): require_once('/home/u19617779...')
#24 {main}
thrown

### Expected behavior

I expect to happen when customers paid by credit card with stripe plugin on checkout page the detail and thank you page properly.

### Actual behavior

Now when I'm trying in test mode fatal error appears and no transaction is possible on my website.  

![image](https://github.com/user-attachments/assets/d5c910b8-cc06-4d8c-be63-5df7946387ea)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/eda107fb-cb98-44d1-854f-0e637e127956)

![image](https://github.com/user-attachments/assets/e33152ba-4a62-4953-a38e-6d6882a54e4e)

![image](https://github.com/user-attachments/assets/49a90a04-1f44-4c8c-a6ae-57d4c6f6289b)

![image](https://github.com/user-attachments/assets/fae36bb7-8f17-45c5-87bc-2de98f12ae40)

### WordPress Environment

[SystemStatusReport_tomoveout.fr_2024-09-20T21-02-47.txt](https://github.com/user-attachments/files/17080790/SystemStatusReport_tomoveout.fr_2024-09-20T21-02-47.txt)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment]
Hi @tomoveout,

The Stripe plugin you're using looks like it was developed by FunnelKit: https://funnelkit.com/docs/stripe-gateway-for-woocommerce/ -- probably best to get in touch with them if you've having trouble with it erroring.

**Comment by tomoveout** [comment]
Hi @lanej0,

Thank you for your answer.
I'm trying to disable FunnelKit and stripe gateway for woocommerce plugin however I obtain the same result so I copy/paste critical log for woocommerce here for your information and if some people have same issue :

Uncaught TypeError: Automattic\WooCommerce\Utilities\OrderUtil::remove_status_prefix(): Argument #1 ($status) must be of type string, null given, called in /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 629 and defined in /home/u196177799/domains/tomoveout.fr/public_html/wp-content/plugins/woocommerce/src/Utilities/OrderUtil.php:239  

Regards.

**Comment by vbelolapotkov** [comment]
@diegocurbelo flagging this one with you to monitor and provide additional input if possible.

**Comment by c-shultz** [comment]
Hi @tomoveout ,

Our team does not have familiarity with `Stripe Gateway for WooCommerce` which is FunnelKit's Stripe plugin, so FunnelKit will be the best place to get support on this. The link shared above looks like a good start point: https://funnelkit.com/docs/stripe-gateway-for-woocommerce/.

If you later need support from Woo directly, feel free to reach out.

**Comment by c-shultz** [comment]
In case you are using a different Stripe plugin (and not FunnelKit's `Stripe Gateway for WooCommerce` plugin), you can reach out for support from the responsible owner. For example, `WooCommerce Stripe Payment Gateway` is a separate plugin that you can get support for here: https://wordpress.org/support/plugin/woocommerce-gateway-stripe/
