### ISSUE TITLE
[Fatal] PHP Fatal error:  Uncaught Error: Call to undefined function wc_print_notice()  | no-products-found.php:22

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#52342]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.3.3

[Link to code](https://github.com/woocommerce/woocommerce/blob/4ca6696f12a955f753fd20927077813c48de78db/plugins/woocommerce/templates/loop/no-products-found.php#L22)

```
PHP Fatal error:  Uncaught Error: Call to undefined function wc_print_notice() in /../plugins/woocommerce/9.3.3/templates/loop/no-products-found.php:22
Stack trace:
#0 /../plugins/woocommerce/9.3.3/includes/wc-core-functions.php(345): include()
#1 /../plugins/woocommerce/9.3.3/includes/wc-template-functions.php(3410): wc_get_template('loop/no-product...')
#2 /../core/6.6.2/wp-includes/class-wp-hook.php(324): wc_no_products_found(Array)
#3 /../core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /../core/6.6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /../plugins/woocommerce/9.3.3/includes/shortcodes/class-wc-shortcode-products.php(680): do_action('woocommerce_sho...', Array)
#6 /../plugins/woocommerce/9.3.3/includes/shortcodes/class-wc-shortcode-products.php(100): WC_Shortcode_Products->product_loop()
#7 /../wp-content/plugins/lastudio-element-kit/includes/modules/woocommerce/classes/base-products-renderer.php(53): WC_Shortcode_Products->get_content()
#8 /../wp-content/plugins/lastudio-element-kit/includes/addons/vendor/woo-products.php(5970): LaStudioKitThemeBuilder\Modules\Woocommerce\Classes\Base_Products_Renderer->get_content()
#9 /../wp-content/plugins/elementor/includes/base/controls-stack.php(2325): Elementor\LaStudioKit_Woo_Products->render()
#10 /../wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack->render_by_mode()
#11 /../wp-content/plugins/elementor/includes/base/widget-base.php(776): Elementor\Widget_Base->render_content()
#12 /../wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Widget_Base->print_content()
#13 /../wp-content/plugins/elementor/includes/base/element-base.php(1442): Elementor\Element_Base->print_element()
#14 /../wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#15 /../wp-content/plugins/elementor/core/base/document.php(1875): Elementor\Element_Base->print_element()
#16 /../wp-content/plugins/elementor/core/base/document.php(1800): Elementor\Core\Base\Document->do_print_elements(Array)
#17 /../wp-content/plugins/elementor/core/base/document.php(1201): Elementor\Core\Base\Document->print_elements(Array)
#18 /../wp-content/plugins/elementor/includes/frontend.php(1207): Elementor\Core\Base\Document->print_elements_with_wrapper(Array)
#19 /../wp-content/plugins/elementor/includes/frontend.php(1102): Elementor\Frontend->get_builder_content(15)
#20 /../core/6.6.2/wp-includes/class-wp-hook.php(324): Elementor\Frontend->apply_builder_in_content('<style>.lakit-b...')
#21 /../core/6.6.2/wp-includes/plugin.php(205): WP_Hook->apply_filters('<style>.lakit-b...', Array)
#22 /../plugins/wordpress-seo/23.6/src/builders/indexable-link-builder.php(140): apply_filters('the_content', '<style>.lakit-b...')
#23 /../plugins/wordpress-seo/23.6/src/actions/indexing/abstract-link-indexing-action.php(76): Yoast\WP\SEO\Builders\Indexable_Link_Builder->build(Object(Yoast\WP\SEO\Models\Indexable), '<style>.lakit-b...')
#24 /../plugins/wordpress-seo/23.6/src/integrations/admin/background-indexing-integration.php(163): Yoast\WP\SEO\Actions\Indexing\Abstract_Link_Indexing_Action->index()
#25 /../core/6.6.2/wp-includes/class-wp-hook.php(324): Yoast\WP\SEO\Integrations\Admin\Background_Indexing_Integration->index()
#26 /../core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#27 /../core/6.6.2/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#28 /../core/6.6.2/wp-cron.php(191): do_action_ref_array('wpseo_indexable...', Array)
#29 {main}
  thrown in /../plugins/woocommerce/9.3.3/templates/loop/no-products-found.php on line 22
``` 

### Expected behavior

No fatal errors when attempting to call wc_print_notice()

### Actual behavior

No fatal errors when attempting to call wc_print_notice()

### Steps to reproduce

We don't have steps to reproduce, but observed 47 instances of this problem on Fri Oct 18, 1200 UTC to 2359 UTC across 1 site.

Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nigeljamesstevenson** [comment]
This one looks like it is related to the elementor plugin so can be considered a lower priority

**Comment by barryhughes** [comment]
For when we pick this up, the backtrace contains:

```
Yoast\WP\SEO\Integrations\Admin\Background_Indexing_Integration
```

So, possibly this is happening outside of a regular frontend request, whereas the function in question is one of a set of "frontend includes" that are only loaded for requests that are obviously related to the frontend.
