### ISSUE TITLE
[Fatal] PHP Fatal error: Uncaught Error: Call to a member function get_type() on null | wc-template-functions.php:1724

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#52596]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.3.3

[Link to code](https://github.com/woocommerce/woocommerce/blob/e66ab452634da522af668779bf98cd1a8adbe354/plugins/woocommerce/includes/wc-template-functions.php#L1724)

```
PHP Fatal error:  Uncaught Error: Call to a member function get_type() on null in /../plugins/woocommerce/9.3.3/includes/wc-template-functions.php:1724
Stack trace:
#0 /../wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php(301): woocommerce_template_single_add_to_cart()
#1 /../wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php(208): ElementorPro\Modules\Woocommerce\Widgets\Add_To_Cart->render_form_button(Object(WC_Product_Simple))
#2 /../wp-content/plugins/elementor/includes/base/controls-stack.php(2325): ElementorPro\Modules\Woocommerce\Widgets\Add_To_Cart->render()
#3 /../wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack->render_by_mode()
#4 /../wp-content/plugins/elementor/includes/base/widget-base.php(776): Elementor\Widget_Base->render_content()
#5 /../wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Widget_Base->print_content()
#6 /../wp-content/plugins/elementor/includes/base/element-base.php(1442): Elementor\Element_Base->print_element()
#7 /../wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#8 /../wp-content/plugins/elementor/includes/base/element-base.php(1442): Elementor\Element_Base->print_element()
#9 /../wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#10 /../wp-content/plugins/elementor/core/base/document.php(1874): Elementor\Element_Base->print_element()
#11 /../wp-content/plugins/elementor/core/base/document.php(1799): Elementor\Core\Base\Document->do_print_elements(Array)
#12 /../wp-content/plugins/elementor/core/base/document.php(1200): Elementor\Core\Base\Document->print_elements(Array)
#13 /../wp-content/plugins/elementor/includes/frontend.php(1190): Elementor\Core\Base\Document->print_elements_with_wrapper(Array)
#14 /../wp-content/plugins/elementor/includes/frontend.php(1085): Elementor\Frontend->get_builder_content(5)
#15 /../core/6.6.2/wp-includes/class-wp-hook.php(324): Elementor\Frontend->apply_builder_in_content('<p>Domaine fami...')
#16 /../core/6.6.2/wp-includes/plugin.php(205): WP_Hook->apply_filters('<p>Domaine fami...', Array)
#17 /../core/6.6.2/wp-includes/post-template.php(256): apply_filters('the_content', '<p>Domaine fami...')
#18 /../wp-content/themes/oceanwp/partials/page/article.php(20): the_content()
#19 /../core/6.6.2/wp-includes/template.php(812): require('/../wp-...')
#20 /../core/6.6.2/wp-includes/template.php(745): load_template('/../wp-...', false, Array)
#21 /../core/6.6.2/wp-includes/general-template.php(206): locate_template(Array, true, false, Array)
#22 /../wp-content/themes/oceanwp/partials/page/layout.php(20): get_template_part('partials/page/a...')
#23 /../core/6.6.2/wp-includes/template.php(812): require('/../wp-...')
#24 /../core/6.6.2/wp-includes/template.php(745): load_template('/../wp-...', false, Array)
#25 /../core/6.6.2/wp-includes/general-template.php(206): locate_template(Array, true, false, Array)
#26 /../wp-content/themes/oceanwp/page.php(36): get_template_part('partials/page/l...')
#27 /../core/6.6.2/wp-includes/template-loader.php(106): include('/../wp-...')
#28 /../core/6.6.2/wp-blog-header.php(19): require_once('/../core...')
#29 /../core/6.6.2/index.php(17): require('/../core...')
#30 {main}
  thrown in /../plugins/woocommerce/9.3.3/includes/wc-template-functions.php on line 1724
``` 

### Expected behavior

No fatal errors when attempting to call $product->get_type()

### Actual behavior

Fatal errors when attempting to call $product->get_type()

### Steps to reproduce

We don't have steps to reproduce, but we observed 2168 instances of this problem on Fri Nov 1, 1200 UTC to 2359 UTC across more than 10 sites.

Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by albarin** [comment]
This was [already fixed](https://github.com/woocommerce/woocommerce/blob/abbe664879b7b530863655e6108b0681b6a43114/plugins/woocommerce/includes/wc-template-functions.php#L1857) in this PR https://github.com/woocommerce/woocommerce/pull/53167
