### ISSUE TITLE
[Fatal] PHP Fatal error: Uncaught WC_Data_Exception: Invalid or duplicated GTIN, UPC, EAN or ISBN. in /wordpress/plugins/woocommerce/9.3.3/includes/abstracts/abstract-wc-data.php:943

### ISSUE THREAD

**Issue by Stojdza** [woothemes/woocommerce#52842]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.3.3

[Link to code. ](https://github.com/woocommerce/woocommerce/blob/e66ab452634da522af668779bf98cd1a8adbe354/plugins/woocommerce/includes/abstracts/abstract-wc-data.php#L943)

```
PHP Fatal error:  Uncaught WC_Data_Exception: Invalid or duplicated GTIN, UPC, EAN or ISBN. in /wordpress/plugins/woocommerce/9.3.3/includes/abstracts/abstract-wc-data.php:943
Stack trace:
#0 /wordpress/plugins/woocommerce/9.3.3/includes/abstracts/abstract-wc-product.php(861): WC_Data->error('product_invalid...', 'Invalid or dupl...', 400, Array)
#1 /srv/htdocs/wp-content/plugins/seo-by-rank-math-pro/includes/modules/woocommerce/class-migrate-gtin.php(81): WC_Product->set_global_unique_id('15-')
#2 /wordpress/plugins/woocommerce/9.3.3/includes/libraries/wp-background-process.php(301): RankMathPro\WooCommerce\Migrate_GTIN->task(Array)
#3 /wordpress/plugins/woocommerce/9.3.3/includes/libraries/wp-background-process.php(447): WP_Background_Process->handle()
#4 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(324): WP_Background_Process->handle_cron_healthcheck()
#5 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /wordpress/core/6.6.2/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#7 /wordpress/core/6.6.2/wp-cron.php(191): do_action_ref_array('wp_gtin_data_mi...', Array)
#8 {main}
thrown in /wordpress/plugins/woocommerce/9.3.3/includes/abstracts/abstract-wc-data.php on line 943
```

### Expected behavior

No fatal errors when invalid or duplicated GTIN, UPC, EAN or ISBN.

### Actual behavior

Fatal errors when there are invalid or duplicated GTIN, UPC, EAN, or ISBN.

### Steps to reproduce

We don't have steps to reproduce, but we observed 1877 instances of this problem on Fri Nov 8, 0000 UTC to 2359 UTC across more than 10 sites.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by albarin** [comment]
Closing as this seems a valid exception not handled by the `seo-by-rank-math-pro`.
