### ISSUE TITLE
[e2e-tests] Fix broken merchant e2e tests with GB nightly

### ISSUE THREAD

**Issue by adimoldovan** [woothemes/woocommerce#53064]
More context: p1732215052573499/1732212403.315129-slack-C01BWDDTGKX

The following tests are failing with GB nightly since Nov 21

```
merchant/create-cart-block.spec.js
merchant/create-checkout-block.spec.js
merchant/create-page.spec.js
merchant/create-woocommerce-blocks.spec.js
merchant/create-woocommerce-patterns.spec.js
```

```
TimeoutError: locator.click: Timeout 20000ms exceeded.
Call log:
  - waiting for getByLabel('Add title')

    at fillPageTitle (/home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/utils/editor.js:56:62)
    at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/merchant/create-woocommerce-patterns.spec.js:48:4
```

Looks like the label changed to 'No title'

![Image](https://github.com/user-attachments/assets/03f8ef1b-542c-4ae1-a7f4-4f181f17ef09)

**Comment by rodelgc** [comment]
This issue can already be closed because it's been addressed in #53100
