### ISSUE TITLE
Potential bug in HPOS sync that causes loss of data when HPOS tables are authoritative and sync is enabled

### ISSUE THREAD

**Issue by kaushikasomaiya** [woothemes/woocommerce#53307]
I was investigating #9092642-zen and noticed a strange behaviour. When HPOS tables are authoritative and Sync is enabled:

- Let's assume a meta is deleted from wp_postmeta table 
- maybe_sync_order() deletes the meta from HPOS meta table 
- maybe_sync_order() seems to be called from order edit page but I am assuming there maybe other plugins who reads data through read_multiple() which triggers maybe_sync_order()
- If we do vice versa, delete meta from HPOS meta table, and refresh the order edit page, wp_postmeta is not affected, instead the deleted value is copied back to HPOS meta table
- So it seems like we're considering legacy tables as source of truth here?

In user's case something mysteriously is causing some of their orders to go pending without any status transition occurring or order notes. 

Considering the theory above, it is possible that incorrect data from legacy tables could get copied over silently or at worse all data is lost (see steps below)

- Setup a store, place a couple of orders, ensure HPOS is authoritative and sync enabled
- Disable sync checkbox and clear legacy data from tools
- Note that the orders under wp_posts table will be now marked "draft" status
- Go back to HPOS settings, you'll see pending orders to be synced 
- Open an order in a new browser tab, say Order # 123 - keep the order edit page open
- On HPOS settings page, Enable sync checkbox without pressing the sync now link, and press save https://d.pr/i/iMdFxY
- Quickly go back to the order edit page and refresh it
- See order # 123 turn to pending, and all meta data is lost 

![https://d.pr/i/pYhjef](https://d.pr/i/pYhjef+) 
Full Size: https://d.pr/i/pYhjef

Stack trace of the update below 

```

<pre>
INSERT INTO wp_wc_orders ( `billing_email`, `customer_id`, `date_created_gmt`, `date_updated_gmt`, `id`, `ip_address`, `payment_method`, `payment_method_title`, `status`, `tax_amount`, `total_amount`, `type`, `user_agent` )
VALUES ( '', 0, '2024-11-29 10:48:43', '2024-11-29 10:48:45', 15, '', '', '', 'wc-pending', 0.000000, 0.000000, 'shop_order', '' )
ON DUPLICATE KEY UPDATE `billing_email` = VALUES( `billing_email` ), `customer_id` = VALUES( `customer_id` ), `date_created_gmt` = VALUES( `date_created_gmt` ), `date_updated_gmt` = VALUES( `date_updated_gmt` ), `id` = VALUES( `id` ), `ip_address` = VALUES( `ip_address` ), `payment_method` = VALUES( `payment_method` ), `payment_method_title` = VALUES( `payment_method_title` ), `status` = VALUES( `status` ), `tax_amount` = VALUES( `tax_amount` ), `total_amount` = VALUES( `total_amount` ), `type` = VALUES( `type` ), `user_agent` = VALUES( `user_agent` )
 ###### #0 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/src/Internal/Utilities/DatabaseUtil.php(269): wpdb->query('\nINSERT INTO wp...')
#1 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(699): Automattic\WooCommerce\Internal\Utilities\DatabaseUtil->insert_on_duplicate_key_update('wp_wc_orders', Array, Array)
#2 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1892): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->persist_db_row(Array)
#3 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(2677): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->persist_order_to_db(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#4 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1537): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->persist_updates(Object(Automattic\WooCommerce\Admin\Overrides\Order), false)
#5 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1347): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->migrate_post_record(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WC_Order))
#6 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1255): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->maybe_sync_order(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WC_Order))
#7 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1208): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->read_multiple(Array)
#8 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->read(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#9 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(130): WC_Data_Store->read(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#10 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/includes/class-wc-order-factory.php(49): WC_Abstract_Order->__construct(15)
#11 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/includes/wc-order-functions.php(88): WC_Order_Factory::get_order(15)
#12 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php(361): wc_get_order(15)
#13 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php(167): Automattic\WooCommerce\Internal\Admin\Orders\PageController->setup_action_edit_order()
#14 [internal function]: Automattic\WooCommerce\Internal\Admin\Orders\PageController->handle_load_page_action('')
#15 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-content/plugins/woocommerce/src/Internal/Traits/AccessiblePrivateMethods.php(158): call_user_func_array(Array, Array)
#16 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\Admin\Orders\PageController->__call('handle_load_pag...', Array)
#17 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#18 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#19 /Applications/MAMP/htdocs/woogenerator/sites/wp-2357719/wp-admin/admin.php(237): do_action('load-woocommerc...')
#20 {main}

```

**Comment by barryhughes** [comment]
Labelling as a bug initially, though perhaps it's more of a task (at any rate, seems we need to explore and discuss).

**Comment by nicdwilson** [comment]
9509037-zd-a8c

**Comment by kaushikasomaiya** [comment]
I imagine considering wp_posts and wp_postmeta source of truth helps compatibility - say for instance a plugin updates legecy tables with the standard WP way -> read on order triggers a real time sync so that the updated data is used. However, in some cases this might cause outdated data to be copied to HPOS tables - this is the current suspicion with cases like 9509037-zen, 9638920-zen where HPOS + Sync enabled and something is intermittently causing silent order status changes. (Order notes say order was transitioned from pending to processing yet it appears to be "pending" due to silent DB update)

One theory I built around this is say for instance something tries to read orders (Stripe webhooks for example) right when legacy tables are about to be updated from pending to processing status 

```
$orders   = wc_get_orders(
				[
					'transaction_id' => 'chxxx',
					'limit'          => 1,
				]
			);
```

That might silently transition the status - In the trace below (which is manually generated) `maybe_sync_order` can be seen which is only triggered when Sync is ON

When order is paid, persist_updates() makes the DB update in HPOS. it has two routes:

1. persist_order_to_db() which updates HPOS table pending to processing
2. maybe_backfill_post_record() which updates legacy table pending to processing

What I am assuming is if something reads stale value from legacy before maybe_backfill_post_record() through wc_get_orders or wc_get_order, it might end up switching status in the HPOS table.  

```
2025-04-14T15:06:12+00:00 Info 
INSERT INTO wp_wc_orders ( `date_created_gmt`, `date_updated_gmt`, `id`, `status`, `type` )
VALUES ( '2025-04-14 14:51:11', '2025-04-14 14:51:29', 147, 'wc-pending', 'shop_order' )
ON DUPLICATE KEY UPDATE `date_created_gmt` = VALUES( `date_created_gmt` ), `date_updated_gmt` = VALUES( `date_updated_gmt` ), `id` = VALUES( `id` ), `status` = VALUES( `status` ), `type` = VALUES( `type` )

#0 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-includes/class-wp-hook.php(324): statuscatch('\nINSERT INTO wp...')
#1 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-includes/plugin.php(205): WP_Hook->apply_filters('\nINSERT INTO wp...', Array)
#2 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-includes/class-wpdb.php(2222): apply_filters('query', '\nINSERT INTO wp...')
#3 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/src/Internal/Utilities/DatabaseUtil.php(269): wpdb->query('\nINSERT INTO wp...')
#4 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(773): Automattic\WooCommerce\Internal\Utilities\DatabaseUtil->insert_on_duplicate_key_update('wp_wc_orders', Array, Array)
#5 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(2041): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->persist_db_row(Array)
#6 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(2882): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->persist_order_to_db(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#7 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1659): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->persist_updates(Object(Automattic\WooCommerce\Admin\Overrides\Order), false)
#8 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1469): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->migrate_post_record(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WC_Order))
#9 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1354): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->maybe_sync_order(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WC_Order))
#10 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(171): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->read_multiple(Array)
#11 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/includes/class-wc-order-factory.php(123): WC_Data_Store->read_multiple(Array)
#12 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(3079): WC_Order_Factory::get_orders(Array)
#13 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(224): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->query(Array)
#14 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/includes/class-wc-order-query.php(87): WC_Data_Store->__call('query', Array)
#15 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/plugins/woocommerce/includes/wc-order-functions.php(73): WC_Order_Query->get_orders()
#16 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/themes/storefront/header.php(62): wc_get_orders(Array)
#17 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-includes/template.php(810): require_once('/Applications/M...')
#18 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-includes/template.php(745): load_template('/Applications/M...', true, Array)
#19 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#20 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-content/themes/storefront/index.php(14): get_header()
#21 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-includes/template-loader.php(106): include('/Applications/M...')
#22 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/wp-blog-header.php(19): require_once('/Applications/M...')
#23 /Applications/MAMP/htdocs/woogenerator/sites/wp-8273050/index.php(17): require('/Applications/M...')
#24 {main}
```

**Comment by kaushikasomaiya** [comment]
One more side effect of this behaviour was seen on #9648924-zen 
Though this was more on Subscriptions end that it some how ended up generating multiple renewal order cache entries for the same subscription - the problem was that these stale entries were stored in postmeta and copied back over to HPOS not allowing subscriptions to recalculate the cache IDs correctly. The end result was renewals being attempted on incorrect order IDs. Just reporting for awareness and impact. 

![Image](https://github.com/user-attachments/assets/f225a4ab-9bd9-4c22-bf64-c9453c66f76e)

cc @woocommerce/chronos if we would like to consider always fetching original records instead of cached entries when the gateway renewal hook is triggered or any other improvement we can think of to prevent duplicate order IDs cache entries.

**Comment by barryhughes** [comment]
Interesting. I think there's a case for making things a little more robust/defensive.

As you'd expect, the cost of ignoring the cache increases according to the number of renewal orders (picture here a subscription that has been active for several years, and renews daily), so I'm not sure if we should always ignore/invalidate the cache during this event—but possibly we could try to detect obvious signs of corruption (such as multiple cache entries) and use that as a trigger to recalculate 🤔

**Comment by kaushikasomaiya** [comment]
@barryhughes I wonder what might have caused multiple entries in the first place - I think there is a code block that decides whether to add or update a cache entry, which might need investigation. When I deleted all cache entries in ordermeta HPOS table to allow subs to recalculate - it brought back the stale entries from postmeta (because of this core behaviour). Only when I deleted cache entries from both HPOS and legacy tables - it allowed subs to recalculate correctly

**Comment by nicdwilson** [comment]
9655067-zd-a8c - another ticket with silent status switching.

**Comment by barryhughes** [comment]
@kaushikasomaiya no problem if you haven't had an opportunity to check this aspect, but in case you did, does using **WooCommerce ‣ Status ‣ Tools ‣ Delete Related Order Cache** lead to a better outcome?

**Comment by kaushikasomaiya** [comment]
@barryhughes Great catch - this is the second time I found myself doing db updates without first checking the Tools area 😂 I think that should produce a better outcome if it wipes off data from both tables. I will test it and update the results on the Subs issue that was just created.

**Comment by barryhughes** [comment]
> the second time I found myself doing db updates without first checking the Tools area

Yep, similar … it's a little hidden/a little too far from the normal paths. I don't know for sure if it will solve this (and, even if it does, I guess we may still have some work to do). Worth exploring, though.

**Comment by kaushikasomaiya** [comment]
@barryhughes The tool did not help - probably because it has its own way of deleting cache entries (`delete_all_metadata_by_key()`) and only targets current authoritative tables? HPOS in this case. So it still brings back the stale values via postmeta by sync on read.
