### ISSUE TITLE
[Fatal] Uncaught TypeError: str_starts_with(): Argument #1 ($haystack) must be of type string, int given in | Products.php:304

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#53522]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

[link to code](https://github.com/woocommerce/woocommerce/blob/b9f31d8050f5d84704b949625d180eaf8d00d87c/plugins/woocommerce/src/StoreApi/Routes/V1/Products.php#L304)

```
PHP Fatal error:  Uncaught TypeError: str_starts_with(): Argument #1 ($haystack) must be of type string, int given in /../wp-content/plugins/woocommerce/src/StoreApi/Routes/V1/Products.php:304
Stack trace:
#0 /../wp-content/plugins/woocommerce/src/StoreApi/Routes/V1/Products.php(304): str_starts_with(0, '_unstable_tax_')
#1 /../wp-content/plugins/woocommerce/src/StoreApi/Routes/V1/ProductCollectionData.php(178): Automattic\WooCommerce\StoreApi\Routes\V1\Products->get_collection_params()
#2 /../wp-content/plugins/woocommerce/src/StoreApi/Routes/V1/ProductCollectionData.php(56): Automattic\WooCommerce\StoreApi\Routes\V1\ProductCollectionData->get_collection_params()
#3 /../wp-content/plugins/woocommerce/src/StoreApi/RoutesController.php(157): Automattic\WooCommerce\StoreApi\Routes\V1\ProductCollectionData->get_args()
#4 /../wp-content/plugins/woocommerce/src/StoreApi/RoutesController.php(82): Automattic\WooCommerce\StoreApi\RoutesController->register_routes('v1', 'wc/store')
#5 /../wp-content/plugins/woocommerce/src/StoreApi/StoreApi.php(30): Automattic\WooCommerce\StoreApi\RoutesController->register_all_routes()
#6 /../core/6.7.1/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\StoreApi\StoreApi->Automattic\WooCommerce\StoreApi\{closure}(Object(Gutenberg_REST_Server))
#7 /../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#8 /../core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /../core/6.7.1/wp-includes/rest-api.php(618): do_action('rest_api_init', Object(Gutenberg_REST_Server))
#10 /../core/6.7.1/wp-includes/rest-api.php(442): rest_get_server()
#11 /../core/6.7.1/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#12 /../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#13 /../core/6.7.1/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#14 /../core/6.7.1/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#15 /../core/6.7.1/wp-includes/class-wp.php(813): WP->parse_request('')
#16 /../core/6.7.1/wp-includes/functions.php(1336): WP->main('')
#17 /../core/6.7.1/wp-blog-header.php(16): wp()
#18 /../core/6.7.1/index.php(17): require('/../core...')
#19 {main}
  thrown in /../wp-content/plugins/woocommerce/src/StoreApi/Routes/V1/Products.php on line 304
``` 

### Expected behavior

No fatal error

### Actual behavior

Fatal error witnessed

### Steps to reproduce

We don’t have steps to reproduce, but 1150 Fatals of this type were observed on Fri Nov 29, 2024 across 1 site.
Hopefully, someone can dig in and apply a defensive check if appropriate. – To be updated after investigation

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nigeljamesstevenson** [comment]
On further investigation, we can see that a [defensive check has been added in 9.4](https://github.com/woocommerce/woocommerce/blob/5afd55098b0d1b2443be02c6cbcc24d1f9f04d96/plugins/woocommerce/src/StoreApi/Routes/V1/Products.php#L304) - this site must be using an older version - closing this issue!
