### ISSUE TITLE
[Fatal] PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in | CustomerEffortScoreTracks.php:465

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#53733]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Issue discovered in 9.4.3

link to code

```
PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in /../plugins/woocommerce/9.4.3/src/Internal/Admin/CustomerEffortScoreTracks.php:465
Stack trace:
#0 /../plugins/woocommerce/9.4.3/src/Internal/Admin/CustomerEffortScoreTracks.php(465): array_filter('', Object(Closure))
#1 /../core/6.7.1/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\Admin\CustomerEffortScoreTracks->maybe_clear_ces_tracks_queue('')
#2 /../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /../core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /../core/6.7.1/wp-admin/admin-ajax.php(45): do_action('admin_init')
#5 {main}
  thrown in /../plugins/woocommerce/9.4.3/src/Internal/Admin/CustomerEffortScoreTracks.php on line 465
``` 

### Expected behavior

No fatal error

### Actual behavior

Fatal error witnessed

### Steps to reproduce

We don’t have steps to reproduce, but 839 Fatals of this type were observed on Fri Dec 6, 2024 across 1 site.
Hopefully, someone can dig in and apply a defensive check if appropriate. – To be updated after investigation

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by mgozdis** [comment]
Additional user report here a week or so ago:
p1733488378246649-slack-C03TY6J1A

This is due to `woocommerce_ces_tracks_queue` being an empty string in the options table instead of an empty array or an expected array value. 

Adding an empty array value such as `a:0:{}` for the option is a workaround.
