### ISSUE TITLE
[Fatal] PHP Fatal error:  Uncaught Error: Call to a member function get_column_count() on null in | Packages.php:260

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#53932]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Fatal error witnessed in `9.4.3`

[link to code](https://github.com/woocommerce/woocommerce/blob/a78426da8062348c92f0cb81b2629c352a6c930b/plugins/woocommerce/src/Packages.php#L260)

```
PHP Fatal error:  Uncaught Error: Call to a member function get_column_count() on null in /../plugins/woocommerce/9.4.3/src/Packages.php:260
Stack trace:
#0 /../core/6.7.1/wp-includes/class-wp-hook.php(326): Automattic\WooCommerce\Packages::display_notice_for_merged_plugins('akismet/akismet...')
#1 /../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 /../core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /../core/6.7.1/wp-admin/includes/class-wp-plugins-list-table.php(1491): do_action('after_plugin_ro...', 'akismet/akismet...', Array, 'active')
#4 /../core/6.7.1/wp-admin/includes/class-wp-plugins-list-table.php(711): WP_Plugins_List_Table->single_row(Array)
#5 /../core/6.7.1/wp-admin/includes/class-wp-list-table.php(1712): WP_Plugins_List_Table->display_rows()
#6 /../core/6.7.1/wp-admin/includes/class-wp-list-table.php(1639): WP_List_Table->display_rows_or_placeholder()
#7 /../core/6.7.1/wp-admin/includes/ajax-actions.php(4834): WP_List_Table->display()
#8 /../core/6.7.1/wp-includes/class-wp-hook.php(324): wp_ajax_search_plugins('')
#9 /../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#10 /../core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /../core/6.7.1/wp-admin/admin-ajax.php(192): do_action('wp_ajax_search-...')
#12 {main}
  thrown in /../plugins/woocommerce/9.4.3/src/Packages.php on line 260
``` 

### Expected behavior

No fatal error

### Actual behavior

Fatal error witnessed

### Steps to reproduce

No clear steps to reproduce, but observed 303 instances of this problem on Fri Dec 6 on 113 sites.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by albarin** [comment]
@nigeljamesstevenson I think this issue was fixed some weeks ago with this PR: https://github.com/woocommerce/woocommerce/pull/53438/files
The `is_null( $wp_list_table )` condition avoids calling the `get_column_count()` on `null` which is the error (`Call to a member function get_column_count() on null`):
```php
$plugin_dir = basename( dirname( $plugin_file ) );
if ( ! self::is_package_enabled( $plugin_dir ) || is_null( $wp_list_table ) ) {
	return;
}

$columns_count = $wp_list_table->get_column_count();
```
