### ISSUE TITLE
REST API Webhook: Uncaught TypeError: Cannot access offset of type string on string in /var/www/html/wp-includes/rest-api/class-wp-rest-request.php:456

### ISSUE THREAD

**Issue by gronnmann** [woothemes/woocommerce#54055]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When trying to edit a Webhook through the REST API, I send the following request:

`DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:3000
send: b'PUT /wp-json/wc/v3/webhooks/13?oauth_consumer_key={redacted}&oauth_timestamp=1735260399&oauth_nonce=e27e6e430574e19d49a7f9adbae54b8a0d9d3fad&oauth_signature_method=HMAC-SHA256&oauth_signature={redacted} HTTP/1.1\r\nHost: localhost:3000\r\nuser-agent: WooCommerce-Python-REST-API/3.0.0\r\nAccept-Encoding: gzip, deflate\r\naccept: application/json\r\nConnection: keep-alive\r\ncontent-type: application/json;charset=utf-8\r\nContent-Length: 121\r\n\r\n'
send: b'"{\\"name\\":\\"Syncly Subscriber - Customer Update\\",\\"status\\":\\"active\\",\\"topic\\":\\"customer.updated\\",\\"secret\\":null}"'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'
header: Date: Fri, 27 Dec 2024 00:46:39 GMT
header: Server: Apache/2.4.62 (Debian)
header: X-Powered-By: PHP/8.3.15
header: X-Robots-Tag: noindex
header: Link: <http://localhost:3000/wp-json/>; rel="https://api.w.org/"
header: X-Content-Type-Options: nosniff
header: Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages, Link
header: Access-Control-Allow-Headers: Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type
header: Expires: Wed, 11 Jan 1984 05:00:00 GMT
header: Cache-Control: no-cache, must-revalidate, max-age=0, no-store, private
header: Content-Length: 1955
header: Connection: close
header: Content-Type: application/json; charset=UTF-8
`

I only send the non-read-only fields, as thats what seem to be used in the documentation.
The webhook is before the request configured as this:
<img width="737" alt="Image" src="https://github.com/user-attachments/assets/5e8591d1-e352-4cff-b180-8ac454899b61" />

### Expected behavior

The WebHook updating the data based on the request (changing from Paused to Active)

### Actual behavior

500 Internal Server Error
Trace is the following:
`{'code': 'internal_server_error', 'message': '<p>There has been a critical error on this website.</p><p><a href="https://wordpress.org/documentation/article/faq-troubleshooting/">Learn more about troubleshooting WordPress.</a></p>', 'data': {'status': 500, 'error': {'type': 1, 'message': "Uncaught TypeError: Cannot access offset of type string on string in /var/www/html/wp-includes/rest-api/class-wp-rest-request.php:456\nStack trace:\n#0 /var/www/html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version1/class-wc-rest-webhooks-v1-controller.php(452): WP_REST_Request->set_param('context', 'edit')\n#1 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1292): WC_REST_Webhooks_V1_Controller->update_item(Object(WP_REST_Request))\n#2 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1125): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc/v3/webhooks...', Array, NULL)\n#3 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))\n#4 /var/www/html/wp-includes/rest-api.php(449): WP_REST_Server->serve_request('/wc/v3/webhooks...')\n#5 /var/www/html/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))\n#6 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#7 /var/www/html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)\n#8 /var/www/html/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)\n#9 /var/www/html/wp-includes/class-wp.php(813): WP->parse_request('')\n#10 /var/www/html/wp-includes/functions.php(1336): WP->main('')\n#11 /var/www/html/wp-blog-header.php(16): wp()\n#12 /var/www/html/index.php(17): require('/var/www/html/w...')\n#13 {main}\n  thrown", 'file': '/var/www/html/wp-includes/rest-api/class-wp-rest-request.php', 'line': 456}}, 'additional_errors': []}
`

### Steps to reproduce

1. Create a Webhook (through the API)
2. Set the Webhook to Inactive
3. Send a PUT request, with all the non-Read-Only fields of the Webhook exactly as before, only changing `status`
From fast testing, this also appears to happen when only changing the `status` field.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost:3000
Site address (URL): http://localhost:3000
WC Version: 9.5.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.62 (Debian)
PHP Version: 8.3.15
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.15

SUHOSIN Installed: –
MySQL Version: 11.7.1-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.5.1
WC Database Prefix: wp_
Total Database Size: 5.28MB
Database Data Size: 3.56MB
Database Index Size: 1.72MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 2
product: 1
revision: 1
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooPayments: by WooCommerce – 8.6.1
WooCommerce: by Automattic – 9.5.1

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: NOK (kr)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 14 KB

### WC Pages ###

Shop base: #6 - /shop
Cart: #7 - /cart -  Contains the woocommerce/cart block
Checkout: #8 - /checkout -  Contains the woocommerce/checkout block
My account: #9 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/success.php

### WooPayments ###

Version: 8.6.1
Connected to WPCOM: ❌ No
Logging: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout

Daily Cron: ✔ Next scheduled: 2024-12-26 16:30:18 +00:00
Options: ✔
Notes: 58
Onboarding: completed

### Action Scheduler ###

Pending: 6
Oldest: 2024-12-26 16:30:19 +0000
Newest: 2024-12-26 17:22:15 +0000

### Status report information ###

Generated at: 2024-12-27 00:53:41 +00:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by gronnmann** [comment]
Think the tag is wrong here (community contribution) and not bug, no idea how to fix it

**Comment by gronnmann** [comment]
I think I figured the issue out.
I was sending a parsed json model into the 
`api.put` function in the woocommerce Python library.
This made the JSON data get parsed twice, and probably interpreted as a string.

The fix for those using the library with pydantic is using `model_dump` instead of `model_dump_json`


Sorry for this.

**Comment by samrat-biswas-git** [comment]
Hi @gronnmann - thanks for reporting this, and for the detail you gave.

I know this has been open a while, and I appreciate your patience. We're currently going through some older WooCommerce issues, identifying what still needs fixing, and tidying up what's already fixed or out of scope.

It looks like this has already been fixed, or it's no longer happening on trunk.

Here's what I found: The reporter later determined the failure came from double-encoding the JSON body before passing it to the WooCommerce Python client, which caused the request payload to be treated as a string. That makes this a custom integration usage problem rather than a confirmed WooCommerce core bug as written.

I'm going to close this one. If you're still facing this issue on a current version, please reply with steps to reproduce and we'll happily take another look.
